### ISSUE TITLE
Cleaning up the mobile site design

### ISSUE THREAD

**Issue by WebDevJL** [FWAJL/FieldWorkAssistantMVC#1036]
- in the mobile site, the map should take 100% of width
- the menu should push the content to the left.

**Comment by WebDevJL** [comment]
@bsaiken 

I have made a first dev to clean up the UI on the Mobile part. LMK if you like. I will release next week.

**Comment by bsaiken** [comment]
@WebDevJL 
Looks good.  No need to make any more changes
