### ISSUE TITLE
Store user projects in xml

### ISSUE THREAD

**Issue by WebDevJL** [FWAJL/FieldWorkAssistantMVC#133]
We currently store the user projects in session, called Session Projects. They are associative arrays of the following structure:

   *  array (
   *     "projectId_X" => array(
   *       "project_obj" => Project object,
   *       "locations" => array( of Location objects),
   *       "tasks" => array( of Task objects),
   *       "technicians" => array( of Technician objects)
   *     ),
   *     "projectId_Y" => array(
   *      "project_obj" => Project object,
   *      "locations" => array( of Location objects),
   *      "tasks" => array( of Task objects),
   *      "technicians" => array( of Technician objects)
   *    )
   *  )

We want to store the arrays in xml with one xml per array where the file name is the key "projectId_X" for instance.

More details to come...

**Comment by bsaiken** [comment]
Can this be closed?

**Comment by FWAJL** [comment]
@baiken : yes.

--
Jérémie Litzler
