### ISSUE TITLE
Add locations (/locations/uploadList) that include multiple fields including lat/long

### ISSUE THREAD

**Issue by FWAJL** [FWAJL/FieldWorkAssistantMVC#140]
From a csv file, add locations with the name, lat, long and all the other possible fields.

**Comment by bsaiken** [comment]
Right now, we can upload a long list of Locations from the UI:
Location > Upload List
It looks like this:

![screen shot 2015-02-26 at 3 51 52 pm](https://cloud.githubusercontent.com/assets/8228624/6403833/68739ea8-bdcf-11e4-80f3-31c7d023baa3.png)

Click "Add" and I the four Locations, (A, B, C D), will be inserted.

![screen shot 2015-02-26 at 3 53 13 pm](https://cloud.githubusercontent.com/assets/8228624/6403866/9af700b8-bdcf-11e4-9980-4e345b0f8176.png)

Now, I want to be able to insert the coordinates as well.  If I copy a table from either Pages or Numbers (the Mac equivalent of Word and Excel), this textarea input looks like this:

![screen shot 2015-02-26 at 3 41 46 pm](https://cloud.githubusercontent.com/assets/8228624/6403891/cd76ad90-bdcf-11e4-8bc7-d1d92ab2f106.png)

Now, when I click "Add", the four Locations should be inserted, along with the lat and long coordinates.
We would have to specify the order to be "Name, Lat, Long".

**Comment by FWAJL** [comment]
@bsaiken 

Additional info for the specification: the seperator is a ***TAB*** character.

**Comment by bsaiken** [comment]
@FWAJL 
Are you sure that it is *always* a tab character?

**Comment by FWAJL** [comment]
@bsaiken

We'll have to check (which I did). However a user could modify the data
after pasting it.
What do you do in that case?

--
Jérémie Litzler

**Comment by bsaiken** [comment]
We give them a tooltip telling them how it needs to be done.  If they 
don't follow the procedure, we will need to do some data validation to 
regent the submit.

I don't need to cover every option, just provide a couple common 
options.

Brian

**Comment by FWAJL** [comment]
@bsaiken 
That's grand.

**Comment by bsaiken** [comment]
@gsouvik @FWAJL 
Souvik,
We are going to need this for other instances, so I upped the priority to "very high".  This is related to what we were talking about with Issue #958.
In the admin UI, we have the ability to upload the Field Analytes and Lab Analytes.  However, there would currently be no way to upload the abbreviation for each.  But, if you could upload the analytes as comma separated values, or in a table, we could do it.
So, the entries would look like this:

trichloroethene, TCE
vinyl chloride, VC
 
So maybe when you prepare the code you could manage both cases.

**Comment by gsouvik** [comment]
@bsaiken 
I was actually looking at #965 to fix. So do you want me to stop that and start with this. Alternatively I can finish that and then start this immediately next.

**Comment by gsouvik** [comment]
@bsaiken @FWAJL 
From your last comment:
>In the admin UI, we have the ability to upload the Field Analytes and Lab Analytes. However, there >would currently be no way to upload the abbreviation for each. But, if you could upload the analytes as >comma separated values, or in a table, we could do it.

May be you wanted this feature for Analytes, and NOT locations? But this issue is for Locations, that's why I just wanted to confirm before I started, Thank you.

**Comment by bsaiken** [comment]
@gsouvik @FWAJL 
I want this for Analytes AND Locations.  Since it is a similar process (uploading comma separated values) I mentioned it here because I thought it might affect the way you wrote the code.

**Comment by gsouvik** [comment]
@bsaiken @FWAJL 
As described in the message thread if we enter data in the following format into the screen loation>uploadList:
Loc 1	22.5667	88.3667
Loc 2	18.9751	72.8258
where the separator is Tab (typically when copied from spreadsheet applications line Numbers or Excel), our application now splits it and treats the columns as location_name, location_lat and location_long.

I'm in process of implementing the same for the analytes section. Shall update you when it is done. Thank you.

**Comment by bsaiken** [comment]
@gsouvik 
I did an initial test - amazing!  Would this work if copied from a WORD table?

**Comment by gsouvik** [comment]
@bsaiken 
I tested with a Word table and it worked there too. Currently we are separating the columns with "Tab". If you wish we may include "multiple space" and "comma" as separators too.

**Comment by bsaiken** [comment]
@gsouvik 
I tried it with a table from Pages and it did not work.  We do not need it to work in every situation - we can tell the users what software will work.
Did you mean for this to go to code review, or are you waiting on the analyte section?

**Comment by gsouvik** [comment]
@bsaiken 
We may send this to code review now or wait till the analyte section is up as well. Both are fine. I didn't change the labels as I am still working on the analyte section.

**Comment by bsaiken** [comment]
@gsouvik 
Since you're part way done, finish the analytes so we can finish this Issue.  Then check your list, because I modified your priorities.

**Comment by gsouvik** [comment]
@bsaiken @FWAJL 
As per our discussion in #958 I've added a column `analyte_abbrev` and the lab/field analytes could now be uploaded in bulk similar to the locations. Included database script in this commit which adds the columns.

**Comment by bsaiken** [comment]
@gsouvik @FWAJL 
My comment from May 8 got lost in the mix.  I meant for this to be used in the admin UI for Common Field and Lab Analytes.  

I also have a question.  If you add new columns to the database, don't we need to modify the Dao classes?

**Comment by gsouvik** [comment]
@bsaiken @FWAJL 
Can you please let me know how I may test the admin end for the common field analytes. So this is not required for the `labanalyte/uploadList` and `analyte/uploadList` screens?

In fact I've changed the DAO classes. For example if you look at https://github.com/FWAJL/FieldWorkAssistantMVC/blob/eb96d31f089e313e35566c9dd7aaa083d7fc0748/Applications/PMTool/Models/Dao/Field_analyte.php you'll notice I've added a variable `analyte_abbrev`.

**Comment by bsaiken** [comment]
@gsouvik 
We have the admin UI up and running.  You can access it using username:password:
`admintest:1111`

> @gsouvik said:
> So this is not required for the labanalyte/uploadList and analyte/uploadList screens?

That is correct, but since you already did it, we won't take it away.

I am glad you are going to look at the Admin UI because I have some other important things I want done there, but let's finish this first.  I have some very high priority items for you (#974 and #984), then we can come back to the anaytes and admin topics and finish them out.

**Comment by gsouvik** [comment]
@bsaiken 
Out of #974 and #984 the later has high priority label set to it. So I'm taking that up now and later return to the analyte (adding `analyte_abbrev` to common field and lab analytes) and admin related other issues.

**Comment by bsaiken** [comment]
@gsouvik 
Sorry, that was a typo.  #974 is assigned to Damir.  I meant #973.  Still, doing #984 first is a good idea.

**Comment by bsaiken** [comment]
@FWAJL 
This is working on the live site.
