### ISSUE TITLE
Prevent the same PM to log at the same time

### ISSUE THREAD

**Issue by FWAJL** [FWAJL/FieldWorkAssistantMVC#250]
When the same PM logs at the same time, it can create inconsistencies in the data. Therefore, we need to prevent that to happen.

Using a log table, we verify that a PM is not currently logged in to authorized the PM to log in. 

Tasks to do:
- create table user_log: check with the lead dev for the table definition before moving the next steps.
- insert a log at every login event to the application (status of log: init)
- check logs to verify the pm trying to log is allowed to do so
  - update log status to success if pm was allowed
  - update log status to failed if pm wasn't allowed

**Comment by bsaiken** [comment]
@damirius 
Please consider this Issue when working on Issue #421.

**Comment by bsaiken** [comment]
@damirius @FWAJL 
After seeing the discussion for Issue #421, I am closing this Issue.  One of the things I would like to be able to do in #421 is to enable the Admin user to see what the user sees, for troubleshooting and training.  If we implement this Issue, we couldn't do it.

**Comment by FWAJL** [comment]
@bsaiken 

That is a really advanced task. Create an issue in the back log to do it later: https://github.com/FWM-Team/FWM-Backlog-Issues/issues/new

**Comment by bsaiken** [comment]
@FWAJL 
I don't think you read my comment.  This Issue is closed.

**Comment by FWAJL** [comment]
@bsaiken 

Yes I did and I think it is possible. The only different between the admin and the PMs is that the admin will have many PMs in session rather than one single PM.

Let's look at this later.

**Comment by bsaiken** [comment]
@FWAJL 
You are confusing this Issue with #421.  
I have decided I do NOT want to prevent multiple logins with the same user name at the same time.  This issue is closed.  No backburner.
