### ISSUE TITLE
Automatically set the Current Project.

### ISSUE THREAD

**Issue by bsaiken** [FWAJL/FieldWorkAssistantMVC#272]
If the PM has only one (active) Project, make it the current Project.

**Comment by bsaiken** [comment]
@FWAJL 
Too easy!
Some files (and one deleted file) got pushed unintentionally.  Sorry, I thought I set only the relevant files.  The other changes are OK, just not part of this Issue.  I'm trying to clean up my act.

**Comment by FWAJL** [comment]
@bsaiken

I wanted to show how to do it and while checking the data, I did the
code... Oops.

So I will write some sentences to explain what to do and let you code it.

If you can't figure it out or even if you can, and I'll show you my
solution.

What do you say?
--
Jérémie Litzler

**Comment by bsaiken** [comment]
@FWAJL 
Why are you doing anything?  I did it.  It works.  
Don't tell me you're bored and don't have enough to do...
Brian

**Comment by FWAJL** [comment]
@bsaiken

You asked me on Wednesday and I wanted to help you understand.

What is wrong with doing what you asked?

--
Jérémie Litzler

**Comment by bsaiken** [comment]
I also said I was going to try it again myself and send you an email if 
I needed further clarification.

It's true I still do not understand how to modify the ProjectController 
to accomplish this...

But then I had the inspiration for the JQuery solution.

Unless you have any compelling reason to dis my solution, we can leave 
it as it is.

Now, we still have to set the currentTask with only one active task.  
But, let me try to tackle that, too.  :-)

Brian

**Comment by FWAJL** [comment]
@bsaiken 

jQuery is a solution but it means you refresh the page by performing a redirect after request the setting the current project. That is 2 requests that can be avoided.

The PHP solution in the controller requires no additional request as it is done as part the initial project/listAll load.

To do the PHP solution, you need:
- to get the project arrays in session
- to get the pm array
- to get the project_ids from the pm array
- and if you have only project, set the project as current project.

I will commit the code tomorrow so I can leave you a day to figure it out.

I did not count the 10min I spent doing this in my worked time.

I hope you can understand the coding. I'm happy when you do.

**Comment by bsaiken** [comment]
@FWAJL 
You are being shortsighted.  The amount of time two server requests would take, compared to the amount of time a user would require to manually choose the current project (or task) is insignificant.  This is merely efficiency for the sake of efficiency.

The response I prefer is to table this as a backlog issue, since we have a working solution (albeit, less efficient).

**Comment by FWAJL** [comment]
@bsaiken 

Where do you see in my response that the PHP solution is the current one where the user selects a project in the contextual menu? I did not say that at all.

The selection is done as part of loading the project and project/listAll views (to cover all scenarios).

Maybe now you understand.

**Comment by bsaiken** [comment]
@FWAJL 
I see that we will need to discuss this in the meeting Wednesday.

**Comment by FWAJL** [comment]
@bsaiken 

This is live already.

**Comment by bsaiken** [comment]
I am nominating your for the longest method name of all time.

Brian
