### ISSUE TITLE
Make (single) activated Task the Current Task.

### ISSUE THREAD

**Issue by bsaiken** [FWAJL/FieldWorkAssistantMVC#278]

**Comment by FWAJL** [comment]
@bsaiken 

I can't find the line of code you are talking about. I think the file has evolved too much since.

Please clarify this:
- do you want to activate one task at a time? If so, this is already the case.
- do you want to limit the number of active task to one? 

In the previous comments, I'm not sure what you want.

Thank you.

**Comment by bsaiken** [comment]
@FWAJL 
Right now, the user needs to take an action to assign a value to $current_task.  What I am talking about is, if there is only one active task, assign this value automatically.  I make the same argument for Projects.

**Comment by bsaiken** [comment]
see Issue #272

**Comment by bsaiken** [comment]
@FWAJL 
I would like to modify this slightly.  I would like the currentTask set immediately when the user logs in (like the currentProject is).  That way, I can set up the "demo" login with one Project and one active task and users can navigate anywhere, without having to select a Project or a Task.

**Comment by FWAJL** [comment]
@bsaiken

Tasks are not loaded at the login like projects. They are loaded on the
task/listAll menu selection.

To do what you want, we need to load the tasks as well.
This additional requirements will not be a matter 5 min work.

Let me know the priority for this.

Thank you.

--
Jérémie Litzler

**Comment by bsaiken** [comment]
Yes, I would like you to prioritize this immediately after code reviews. 
  It is a small thing, but I think it will help new freelancers navigate 
the site and getting more manpower is the only hope I have on finishing 
on time.

Brian
