### ISSUE TITLE
Analytes UI

### ISSUE THREAD

**Issue by FWAJL** [FWAJL/FieldWorkAssistantMVC#287]
Should the UI look like the location UI? I remember that you said you could add analytes with a list of names.

Please confirm.

**Comment by bsaiken** [comment]
Yes, we do need to be able to edit and delete single analytes.  

Delete can be the same function.  

Edit changes only the analyte name (spelling).  We can handle that with a javascript prompt box.  I am going to write a SOW for the creation of a generic alert/confirm/prompt tool that will solve this issue.

**Comment by WebDevJL** [comment]
Done and released:

- Tab UI for show form
- Add list of analytes
- Tab UI for lists (similar to Services)
- List field and lab analytes
- Build the Project_field_analyte and Project_lab_analyte tables and dao classes
- Move analytes from list A (PM analyte) to list B (Project analyte)

Left to do:
- Delete a single analyte
- Edit a single analyte

**Comment by WebDevJL** [comment]
Done and released:

- Tab UI for show form
- Add list of analytes
- Tab UI for lists (similar to Services)
- List field and lab analytes
- Build the Project_field_analyte and Project_lab_analyte tables and dao classes
- Move analytes from list A (PM analyte) to list B (Project analyte)
- Bug fix in display when adding project analytes (v1.5.27)

Left to do:
- Delete a single analyte
- Edit a single analyte

**Comment by bsaiken** [comment]
Leave "Edit a single Analyte" for discussion.

**Comment by WebDevJL** [comment]
Delete a single analyte in issue #363

**Comment by WebDevJL** [comment]
Edit an analyte is left to discussion. See issue #365
