### ISSUE TITLE
Add prompt box for Task Name to add a Task

### ISSUE THREAD

**Issue by bsaiken** [FWAJL/FieldWorkAssistantMVC#334]
This will send the user directly to edit mode with the Task Name pre-populated.  
This should solve the navigation issue with the tabs.  :-)

**Comment by bsaiken** [comment]
This will be modified for Popup box tool task for freelancer.  SOW ready for review and discussion.

**Comment by WebDevJL** [comment]
@bsaiken : SOW reviewed.

**Comment by bsaiken** [comment]
This issue, and related issues, cannot be released unit the layout changes are completed.
