### ISSUE TITLE
Directories for technician and location documents.

### ISSUE THREAD

**Issue by bsaiken** [FWAJL/FieldWorkAssistantMVC#348]
This is a copy of location_document to upload technician photos.
We will also need new folder(s) created.  e.g.
Web/uploadfiles/
                       .../location_photos/
                       .../tech_photos/

The /uploadfiles/ folder can be used in the future for other docs as needed.

**Comment by WebDevJL** [comment]
@bsaiken : I think this folder creation needs to be done as part of the upload functionality. 

Why? Because the way the database table are built will allow this. The only part to do in this issue is to create the uploadfiles folder.

What do you think?

**Comment by bsaiken** [comment]
I thought we decided this in the meeting.  So I am removing the questions status.

**Comment by FWAJL** [comment]
@bsaiken: this is grand. Thank you.

--
Jérémie Litzler

**Comment by FWAJL** [comment]
@bsaiken 

This issue is not applicable anymore since the folders will be built dynamically.
I'm closing it.

Thank you.
