### ISSUE TITLE
Make scrollbar for lists draggable

### ISSUE THREAD

**Issue by bsaiken** [FWAJL/FieldWorkAssistantMVC#353]

**Comment by WebDevJL** [comment]
This is something built in the library jQuery UI by default. It is very likely to be a CSS tweak to perform.

**Comment by FWAJL** [comment]
@bsaiken : when the Analyte UI is done, we need to apply the same div <div class="scroll-bar"></div> to the list modules.

**Comment by bsaiken** [comment]
Unless you have already done this, I do not want you doing it.  This was to be assigned to a freelancer.
