### ISSUE TITLE
Editing a Task makes the task inactive.  Needs to stay active (or keep the same status).

### ISSUE THREAD

**Issue by bsaiken** [FWAJL/FieldWorkAssistantMVC#354]

**Comment by WebDevJL** [comment]
This means that there must be a checkbox input set to true by default on the task form.

**Comment by bsaiken** [comment]
This will not work.  If a user is editing a task that is inactive, the task needs to stay inactive.  
It is unusual to edit an active task, but it may happen.  This may need require a prompt box - I will add this to the agenda for discussion.

**Comment by FWAJL** [comment]
If it does, then it does because it is problably not loading the value "active" properly. Or maybe I'm missing something.

**Comment by FWAJL** [comment]
@bsaiken : fix is ready. It is done as I described.
