### ISSUE TITLE
Style updates.

### ISSUE THREAD

**Issue by bsaiken** [FWAJL/FieldWorkAssistantMVC#355]
Styling changes.
Increased left and right margins.
Changes to make the site more consistent for all UIs.

I would like to make the upload list button on the right active...see Location > Upload List

**Comment by WebDevJL** [comment]
@baiken :

please list the items to update. Or Let's create a milestone for CSS
updates. Each item will be an issue.

It's more efficient than creating an issue without details.

**Comment by bsaiken** [comment]
I have modified the forms to have a uniform look across all pages.

**Comment by WebDevJL** [comment]
Related to 7663799b0f87b27e87b94fae3941062fa9737076
