### ISSUE TITLE
Apply the Analyte and Service Provider javascript manager techniques to Project manager

### ISSUE THREAD

**Issue by WebDevJL** [FWAJL/FieldWorkAssistantMVC#356]
See analyte_manager.js and project_service.js files for implementation

**Comment by bsaiken** [comment]
The Analytes UI is not working properly, so why would you apply these techniques to Project manager?  Project manger is currently working fine - is this change necessary???

**Comment by FWAJL** [comment]
I'm not sure why you say it does not work. I wouldn't release something
that doesn't work.

It is necessary because the old method is too messy and creates a lot of
dead code.
It will be applied to the new functions. Old function will use it later.

--
Jérémie Litzler

**Comment by bsaiken** [comment]
Can we close this Issue?
