### ISSUE TITLE
Edit an analyte

### ISSUE THREAD

**Issue by WebDevJL** [FWAJL/FieldWorkAssistantMVC#365]

**Comment by WebDevJL** [comment]
We need a little specification for this since it will be done using a prompt box

**Comment by bsaiken** [comment]
@FWAJL 
We can close.  This will be done with Issue #481.

**Comment by bsaiken** [comment]
@FWAJL 
This is an example of what I think of as a duplicate Issue.  When you created Issue #481, this issue became redundant.  I would like to purge redundant or deprecated Issues as we go.
