### ISSUE TITLE
Test notification for Brian

### ISSUE THREAD

**Issue by WebDevJL** [FWAJL/FieldWorkAssistantMVC#366]
@bsaiken : please comment this if you received an email notification.

**Comment by bsaiken** [comment]
You will need to explain

**Comment by FWAJL** [comment]
@bsaiken <https://github.com/bsaiken> : Every time I do "@bsaiken
<https://github.com/bsaiken>", you should get an email notification...
Don't you?

--
Jérémie Litzler
