### ISSUE TITLE
Upload Location Photo

### ISSUE THREAD

**Issue by WebDevJL** [FWAJL/FieldWorkAssistantMVC#368]
Similar to issue #249.

**Comment by FWAJL** [comment]
@bsaiken <https://github.com/bsaiken>: why did you close this? We need to
talk about managing issues because I don't understand what you are doing...

--
Jérémie Litzler

**Comment by WebDevJL** [comment]
Related to #397 : table structure and more specifications.

**Comment by FWAJL** [comment]
Completed as part of issue #523 .
