### ISSUE TITLE
Add button doesn't work in upload list form

### ISSUE THREAD

**Issue by WebDevJL** [FWAJL/FieldWorkAssistantMVC#379]

**Comment by WebDevJL** [comment]
@bsaiken : you seem to have broken the code and the add button doesn't work anymore.

**Comment by WebDevJL** [comment]
@bsaiken : you changed the attribute name from "lab_analyte_name" to "lab_analyte_names" and the javascript doesn't find the values anymore.

**Comment by WebDevJL** [comment]
@bsaiken : also, since you remove the tab, there is no current to differentiate the field analytes textarea from the lab analytes textarea.

**Comment by WebDevJL** [comment]
Don't close issues that are not released. Please. Thank you.

**Comment by bsaiken** [comment]
You are making code changes to fix this issue and I may change the UI so that the fix you create is irrelevant.  This is why I did not create the issue myself.  This is also why I closed it.  You are having a squirrel moment.
