### ISSUE TITLE
Modify tabbed UIs to match Analytes List All structure

### ISSUE THREAD

**Issue by bsaiken** [FWAJL/FieldWorkAssistantMVC#384]
I have thought it through and the form layout you created for Analytes/listAll is exactly what I need for analytes/uploadList.  Brilliant.
I can do this no worries.
When I finish, there will be a l little back-end work to make it functional.
This layout resolves an issue I was having with the task/showForm layout as well.
I will also modify the project/showForm layout so that all tabbed layouts are consistent.

**Comment by bsaiken** [comment]
Question:  The  task ui has a different module for each tab.  That is not the way Analytes is set up - it's just one module for both tabs.  So it begs the question...should the task ui still have a separate module for each tab, or follow the analytes ui style with one module that holds all tabs.

**Comment by bsaiken** [comment]
Of course, this applies to the project ui - so I am going to stop until I know which way you want the modules built.

**Comment by FWAJL** [comment]
The Task UI has a lot of tabs. The Analyte UI has only two tabs. It is manageable to for the Analyte UI to have one view for the 2 tabs but the Task UI is too complex to do the same. At least right now, it is faster to built a view per tab for the Task UI.

**Comment by FWAJL** [comment]
The Project UI is also simple, even simplier than the Analyte UI because it doesn't have multiple tabs for ListAll view. The challenge with the Analyte UI was the dual list management. That's why it has its own list module and is not using the common modules

**Comment by bsaiken** [comment]
So that means a module for each tab for task ui and one module for project ui?

**Comment by FWAJL** [comment]
Yes.

**Comment by FWAJL** [comment]
@bsaiken : Same comment as #385 .

**Comment by bsaiken** [comment]
Project form is being displayed incorrectly.

**Comment by FWAJL** [comment]
@bsaiken: do you want me to correct it or will you do it?

--
Jérémie Litzler

**Comment by bsaiken** [comment]
@WebDevJL : Let's talk about who does it during our meeting.

**Comment by FWAJL** [comment]
@bsaiken : first bug was the closing on line 31 of Applications/PMTool/Views/Task/Modules/task_form.php. See the commit below.

**Comment by FWAJL** [comment]
@bsaiken : second bug was that you had duplicate code and add the 3 column-display too many times. The three files (project_info_lists.php, facility_info_lists.php, client_info_lists.php) are not useful at all. Look at the showForm view of Project now. That's all we need to do. See the commit below.

**Comment by bsaiken** [comment]
I don't understand this comment.  showForm of project view is not fixed.
![screen shot 2015-01-15 at 10 19 53 am](https://cloud.githubusercontent.com/assets/8228624/5762600/60be52fc-9ca0-11e4-8dad-db03c17ebeb9.png)

**Comment by FWAJL** [comment]
@bsaiken : unless I tell you I have *released *it, it is not live. Here, I
am informing you I have found the bug and I have fixed it in the code. I
also explain you what was wrong and you can see the commit for more
details. Do you understand?

--
Jérémie Litzler

**Comment by bsaiken** [comment]
I thought the status was "to review".  If it had been, then I would have followed the procedure correctly.  Not sure how I saw the status wrong...

**Comment by FWAJL** [comment]
@bsaiken : It was set to review but then we saw it was not complete so it was moved back to in dev. You can see it in the label history.

**Comment by bsaiken** [comment]
@FWAJL 
There are some minor css changes that needs to be fixed.  I will do them.  Brian
