### ISSUE TITLE
All buttons will be in the center of middle column

### ISSUE THREAD

**Issue by FWAJL** [FWAJL/FieldWorkAssistantMVC#385]
To apply on listAll and uploadList views.

**Comment by FWAJL** [comment]
@bsaiken : I don't understand the change of labels. You mark it as "status:to release" but there is no code submitted. 
Like I said, we need a priority and a version label. This is for me to be able to manage the release and the flow of updates. Please help me with that.

**Comment by FWAJL** [comment]
@bsaiken : you can add a reference to a commit by pasting the commit id (for ex: 6cace37a2bee00ca0ccb0b322234420530d13c88) if you didn't push the code with the issue number. It can happen but add this reference in the comments of issue like this one.

**Comment by bsaiken** [comment]
I made the changes that put the button s in the middle, so as far as I know the code is ready to release.

**Comment by FWAJL** [comment]
It is released since this morning.

**Comment by bsaiken** [comment]
@FWAJL 
There are some minor formatting changes that are needed (css).  I will take care of it.

**Comment by WebDevJL** [comment]
@bsaiken : ok. I saw the updates from #409
