### ISSUE TITLE
Create the common analytes tables

### ISSUE THREAD

**Issue by FWAJL** [FWAJL/FieldWorkAssistantMVC#387]
common_field_analytes:

   field_analyte_id
   field_analyte_name (varchar 50 - so there is room for field analtye name and units)

common_lab_analytes:

   lab_analyte_id
   lab_analyte_category (we will list lab analytes by category in the common lab analytes list to make them easier to find, but we will NOT list by category in any other analytes list.
   lab_analyte_name

These tables will not have an foreign keys as they are independent and usable by all PMs.

**Comment by FWAJL** [comment]
All the column name must follow the naming structure as the other tables, hence "common_" must be added.

**Comment by bsaiken** [comment]
Yes, of course.

**Comment by bsaiken** [comment]
I think I have done all I can do for the analytes/uploadList module until this is finish, so we can create the common analyte lists.

As an aside...I notice you use css styling like "class: hide" and style="display: none;"  until some condition is met.  Why hide things?  Are these really necessary?  I find them terribly annoying.

**Comment by FWAJL** [comment]
@bsaiken: see #393 for the answer.

--
Jérémie Litzler

**Comment by FWAJL** [comment]
@bsaiken : I released in version 1.5.29 the code you made but it is not
complete, you commented a few days ago. This task however is complete and
you can go ahead with the rest.

--
Jérémie Litzler
