### ISSUE TITLE
Update the listAll and uploadList titles

### ISSUE THREAD

**Issue by FWAJL** [FWAJL/FieldWorkAssistantMVC#388]
The <h4> headings for the analyze UI will be:

   analyte/listAll - Field Analytes tab: left side: "Analytes to be used for this Project" - no change
   analyte/listAll - Field Analytes tab: right side: "All your analytes (available for all projects)"
   analyte/listAll - Lab Analytes tab: left side: "Analytes to be used for this Project" - no change
   analyte/listAll - Lab Analytes tab: right side: "All your analytes (available for all projects)"

   analyte/uploadList - Field Analytes tab: left side: "Enter or paste a list of analytes here..."
   analyte/uploadList - Field Analytes tab: right side: "...or select from this list of common field analytes"
   analyte/uploadList - Lab Analytes tab: left side: "Enter or paste a list of analytes here"
   analyte/uploadList - Lab Analytes tab: right side: "...or select from this list of common lab analytes"

**Comment by bsaiken** [comment]
https://github.com/FWAJL/FieldWorkAssistantMVC/commit/b7070485987c154bb60c7e666bb33dcc78196114

**Comment by bsaiken** [comment]
I cannot verify this.  Content of page is being blocked with style="display: none;"

**Comment by FWAJL** [comment]
@bsaiken: I will do it as part of #384.

--
Jérémie Litzler

**Comment by bsaiken** [comment]
This is finished.  I may refine the text in the future, but it is good for now.
