### ISSUE TITLE
Use class="hide" instead of inline css

### ISSUE THREAD

**Issue by FWAJL** [FWAJL/FieldWorkAssistantMVC#393]
To avoid inline css, replace style="display: none" with class="hide".

**Comment by FWAJL** [comment]
@bsaiken : this is to answer your question from #387. Because in the Project UI and Analyte UI, we have  everything loaded at once, we can want to show everything. Only the active tab content will be displayed. The rest is hidden. Hence the default is "class=hide". 
It is necessary to do so otherwise the UI would be ok.

The style="display: none" (aka inline css) are not a good practice so I replaced them withe class="hide". In 3 cases, it is used to hide inputs not used at the moment. 

The JavaScript code (in tabs.js mainly) enables to switch the hide class from a tab to another, therefore it hides and shows according to the action.

**Comment by bsaiken** [comment]
The issue I have is that some things are getting hidden with a style="display: none" and I need to see everything during development.  For example, the checkboxes at the bottom of the task_info form were getting hidden, possibly because the tabs weren't ready yet.  I must be able to see everytihng, even if it is not ready.

**Comment by bsaiken** [comment]
Also...we use JQuery to hide the divs we don't want until they are selected. We already have a function written for that for the task ui, which we could also apply to the project ui.

**Comment by FWAJL** [comment]
The tabs are working for the Project UI already. Your updates weren't
correct and I pushed a fix ( see the comment I made in your commit ).

--
Jérémie Litzler

**Comment by bsaiken** [comment]
I still do not understand how this is fixed.  For the analyte/uploadList, there is still a style= "display:none"; even though there is no "hide" class.

![screen shot 2015-01-15 at 10 41 50 am](https://cloud.githubusercontent.com/assets/8228624/5762991/926b2a3e-9ca3-11e4-8b1f-3dd4ce20a18d.png)

**Comment by FWAJL** [comment]
@bsaiken: like my comment earlier says, this is not fixed but I have found
the solution and the fix has been applied all the list except the Analyte
lists. I will apply the fix to it as part of #384.

--
Jérémie Litzler

**Comment by bsaiken** [comment]
I am closing this Issue.  I will open a new Issue if it comes up again.
