### ISSUE TITLE
Create technician_document table (copy of location_document table).

### ISSUE THREAD

**Issue by bsaiken** [FWAJL/FieldWorkAssistantMVC#397]

**Comment by WebDevJL** [comment]
@bsaiken : After thinking about it, we will have one table for all the documents, which will be used to store:
- where the file it is (name of file),
- what type it is (this will be retrieve from the extension),
- what category it is (an image for  a location or technician for example).

The advantages: 
- no need to update the database later
- dynamic upload solution: you just specify the content type and category to know where to store the documents. This will prevent to add a constant for each category (location, technician, etc) and you will know when reading a file the type.
- less code to write and common interface to all documents.

What do you say?

**Comment by bsaiken** [comment]
@WebDevJL : Do it.

**Comment by FWAJL** [comment]
@bsaiken: it will be pushed tomorrow to the dev branch.

--
Jérémie Litzler

**Comment by bsaiken** [comment]
@WebDevJL  I am closing this, assuming the table "document" satisfies this issue.
