### ISSUE TITLE
Mapping UI questions

### ISSUE THREAD

**Issue by FWAJL** [FWAJL/FieldWorkAssistantMVC#399]
[>> Here are some questions regarding the mapping UI <<] (https://docs.google.com/spreadsheets/d/1QfO1nBDlqg8HweVqU0hY1QhbWlUnNxKy7Y6Lh42QKb0/edit?usp=sharing)

**Comment by bsaiken** [comment]
No questions - did you intent to attach a file?

**Comment by FWAJL** [comment]
See link above.

**Comment by bsaiken** [comment]
I am unable to edit the linked file.  
We have a few steps to go, but soon we will not be able to have a Project (Facility) that does not have lat/long coordinates.  This will become a requirement when creating a new Project.  Will be solved with my magic popups that you are going to learn to like.

Locations can be defined without lat/long coordinates.  The coordinates should NOT be 0,0 - unless the project is in the middle of the Atlantic off the coast of Africa.

**Comment by FWAJL** [comment]
@bsaiken : you should able to edit the file if you're connected to your Google Account.
