### ISSUE TITLE
Navigation button issues

### ISSUE THREAD

**Issue by bsaiken** [FWAJL/FieldWorkAssistantMVC#400]
I almost always need to press a button more than once to get a response.  Sometimes three times.

**Comment by FWAJL** [comment]
@bsaiken: give as many as occurences as you can because I'm not finding one
so far.

I have not had the time to look why the server online is slow. Maybe we
need an issue for that and I think that is why you are having problems on
button clicks.

--
Jérémie Litzler

**Comment by WebDevJL** [comment]
@bsaiken : possible lead => the javascript and css library take too long to load?

I think we need to include them differently in the header/footer template. When we are working locally, it is useful to have a local copy but online, we could CDN urls (hosted files on Google or other providers for free) or we could use the minified or gzipped version of the libraries.

Solution would be to have a config file that tells where the libraries come from depending on where the code is executed (local machine, online server).
We need a fallback for the online server where if a CDN resource is unavailable, we load the minified/gzipped copy instead.

**Comment by bsaiken** [comment]
@FWAJL 
So far, additional testing has shown the response is slow, not broken, so I am lowering this to low priority.

**Comment by FWAJL** [comment]
@bsaiken : ok. The improvement described above could be a lead. We'll see
later.

--
Jérémie Litzler

**Comment by bsaiken** [comment]
Hanging Error when clicking "add locations"

![screen shot 2015-01-19 at 2 46 04 pm](https://cloud.githubusercontent.com/assets/8228624/5808393/21789eac-9fea-11e4-9284-4b0ecfba778a.png)

Also happened when trying to edit technician info.

![screen shot 2015-01-19 at 1 14 20 pm](https://cloud.githubusercontent.com/assets/8228624/5808408/4fccee70-9fea-11e4-9872-934b7607aeb9.png)

**Comment by WebDevJL** [comment]
@bsaiken : added to agenda.

**Comment by bsaiken** [comment]
@FWAJL 
I'm confused how we can have priority:low and status: to be prioritized   at the same time.

**Comment by WebDevJL** [comment]
@bsaiken : status updated. Sorry for the confusion

**Comment by bsaiken** [comment]
Website hung up when trying to promote Project Locations to Task Locations.
![screen shot 2015-01-26 at 12 35 39 pm](https://cloud.githubusercontent.com/assets/8228624/5906836/104f0954-a558-11e4-9ed7-04bbec39da3a.png)

**Comment by FWAJL** [comment]
@bsaiken 

Did you click and nothing happened? I think we need to take care of this soon otherwise it will become a real inconvenience.
I think I need to change how the JavaScript and CSS libraries are loaded.

Let's add this to the agenda.

**Comment by bsaiken** [comment]
@FWAJL 
Check the timestamp on this one.  The site was working slowly.  This page took 3 seconds to load.

However, GIT also was slow, so maybe it is not our site after all.  

![screen shot 2015-02-11 at 11 40 23 am](https://cloud.githubusercontent.com/assets/8228624/6153587/e20a3b4e-b1e2-11e4-8b5f-5b84d639d54b.png)

**Comment by FWAJL** [comment]
@bsaiken 

The logs (query run on the live database: `SELECT * FROM `log` WHERE log_id in (4267,4268,4278,4279)`) show fast PHP response.

The map API shouldn't be loaded on every page (Issue created: #532).

Again, I think the amount of http requests (for each image, javascript and css files) is the next possible cause of the problem. Reducing the amount is an action to take (merging js files into one, same for css files) to start with.

The logs logged at the moment have shown that it is not the PHP code. These logs will not give us any more details for this current issue. However, we'll keep them in case they are needed.

Thank you.
