### ISSUE TITLE
Remove task location if the project location is set inactive

### ISSUE THREAD

**Issue by FWAJL** [FWAJL/FieldWorkAssistantMVC#401]
Scenario:
- you have a list of 10 project locations that are active.
- you had them to the task locations list
- you set 2 project locations (in location/listAll) as inactive

What happen to the task locations related to the 2 project locations just deactivated? I would say they must be deleted on the action of updating the project locations.

@bsaiken : please confirm the accuracy of this.

**Comment by FWAJL** [comment]
Related to #402

**Comment by bsaiken** [comment]
Only active locations can be used for a Task.  Same for Technicians.

**Comment by WebDevJL** [comment]
@bsaiken : ok so we need to fix this bug then.

**Comment by WebDevJL** [comment]
@bsaiken : to prioritized, please.

**Comment by bsaiken** [comment]
This will need to wait until we have active tasks.  Locations should not be made inactive while they are assigned to an active task.  Or, the task itself may render the Location inactive.

**Comment by FWAJL** [comment]
@bsaiken 

Do the same action as #402 to archive the issue to the Backlog
