### ISSUE TITLE
Remove task technicians if the technicians is set inactive

### ISSUE THREAD

**Issue by FWAJL** [FWAJL/FieldWorkAssistantMVC#402]
Same as #401 but technicians.

@bsaiken : same processing here?

**Comment by WebDevJL** [comment]
@bsaiken : to prioritized, please.

**Comment by bsaiken** [comment]
We will do this later, after Tasks can become activated, then the process of deactivating a technician will check first to see if the technician is assigned to an active task or is unavailable because they are on another active task that is happening during the same time..

**Comment by bsaiken** [comment]
@FWAJL 

I think this Issue, and #401, should be in the Backlog.  Is there a simple way to migrate Issue to and from the Backlog (without having to create a duplicate backlog issue and delete the Issue here)?

**Comment by FWAJL** [comment]
@bsaiken 

Just copy the title and the url and [create a new issue in the Backlog](https://github.com/FWM-Team/FWM-Backlog-Issues/issues/new) with this description:

"\[See this issue\]\(https://github.com/FWAJL/FieldWorkAssistantMVC/issues/{id_of_issue}\) for details"

**Comment by bsaiken** [comment]
I understand.  I knew this was an option, I just thought there might be 
a shortcut.

Brian
