### ISSUE TITLE
Active Task UI

### ISSUE THREAD

**Issue by bsaiken** [FWAJL/FieldWorkAssistantMVC#404]
@WebDevJL 
I have decided how to prepare a UI for Tasks that are activated, or "Live".
I know these will get broken down into separate issues, but here I am listing out the individual tabs.

### Task Status
This tab will display basic info about the task, but none of this will be editable.  Items on this page include:
- Task name
- Deadline
- Current Date
- Days Remaining
- List of Technicians working on the task - this will have a link that can send a txt message (or we may need a technicians tab that will be like the Services tab with a communication thread).
- The instructions/details box
- XXX

### Map

This tab will show a map of the Locations that are color coded.  
- Red = not finished;  
- Green = finished; 
- Yellow = in progress.  

The map will also show live positions of the Technicians (if known). 

### Forms

This tab will have a list of all the forms for this task.  The first items in the list will be the form templates (forms that have not been completed).  Then the list will include all completed forms with a link so that they can all be opened up and reviewed (and annotated, if appropriate).  The pdf form file names will follow this naming convention:  Taskname_date_location name.  The COC form is an exception, the name is Taskname_date_coc.  Note that this is COC is uneditable and static.

### Example of active form: Chain of Custody

This tab (only used if samples are collected for lab analysis) shows a "live" COC which has color coding for which samples have been collected.  Color coding is the same for the map: 
- Red = not finished;  
- Green = finished; 
- Yellow = in progress.

### Communication

This tab shows a dual list (like all our dual list pages).  The right hand side is all the Service Providers and Technicians that were used for this task.  The left hand side will be a communication thread between the service provider and the PM.  Clicking the Service Provider on the right brings up that communication thread.  We will need buttons to attach documents to the communication thread (e.g. a copy of the COC for labs).

**Comment by FWAJL** [comment]
Ok.

--
Jérémie Litzler

**Comment by bsaiken** [comment]
We need to leave this as preliminary until we create separate new issues for each phase, and then this will become a milestone.  I may refine this from time to time until it is formally set up.

**Comment by FWAJL** [comment]
The commit will be released as part version 1.6.7.

**Comment by bsaiken** [comment]
@damirius @FWAJL 
I noticed an error in the JQuery contextual menu selector for the Task UI.  This was to set up for the Active Task UI.
A child selector must be used (e.g. #inactive-list .select_item) instead of renaming the class because the active_list and inactive_list modules get re-used across multiple UIs.
I corrected this in my most recent commit, but it may take a few days for the fix to promulgate to the dev branch.

**Comment by FWAJL** [comment]
@bsaiken @damirius 

It is merged to dev. I will merge it to the other feature branches soon.

**Comment by bsaiken** [comment]
Prerequisites:
#437 
https://docs.google.com/document/d/1xMCbaX95BOehjDTYWIrFMkt5htb8UvcFDbsi3_UJ0Ss/edit

**Comment by bsaiken** [comment]
SOW in the process of being finalized.

**Comment by bsaiken** [comment]
Create Active Task Views - Milestones
Milestone 1(a) - Prepare activetask/showForm tabbed views. 
There are 4 tabs in our Active Task module:
Task Status; 
Map; 
Forms; 
Communications.

Each view uses a common bootstrap column structure. 
The views are all similar to the views we are already using for Tasks.
To review the Task Views, login under the “demo” username and navigate to Task > List All.  Then right click “Demonstration Task - Inactive” to bring up the contextual menu where you can view (“Edit”) the Task View. Note that the site is being developed so it is possible you will only be able to see the “Task Info”, “Technicians” and “Locations” tabs.  

The attached slides show a mockup of the Active Task views.

Milestone 1(b) - Prepare basic layout for each tab.  Use lorem ipsum contents only. 
Milestone 1(b) is to prepare each tab view structure only, with only lorem ipsum contents.  This will allow you to learn our MVC implementation structure. You will need to fill in the methods in the ActiveTaskController (similar to the TaskController methods), update the routes.xml file, and modify active_task.js as needed.  The Tab view should include the breadcrumb and column list headers.  

The task breadcrumb is coded on lines 4 - 8 of the Task “showForm.php” module.
The column list header should be similar to lines 14 - 16 of the “manageTechnicians.php” module.  You will need to create a new view module for the left hand column.   
This right hand column is prepared similarly.

Milestone 1(c) - Prepare Task Status tab contents.  
Tab contents are shown on Slide 1.  

The contents of the left hand column (Task Progress) are not editable, they include:
Task Deadline: [deadline].  [deadline] is stored here: task.task_deadline
Days remaining: [days remaining].  [days remaining] is calculated from the current date and the [deadline].
Percent Complete: [percent complete].  [percent complete] is a calculated value, but needs to be done at a later time.
Recurrence: [frequency].  This line appears only if task.task_trigger_cal=1. [frequency] is stored in task.task_trigger_cal.
Manual trigger: Yes.  This line appears only if task.task_trigger_pm=1. 
External Trigger: [specify].  This line appears only if task.task_trigger_ext=1  [specify] is stored in task.task_trigger_ext.
Textarea with [Instructions].  [Instructions] include the contents of task.task_instructions.

The contents of the right hand column (Notes) are editable.  This includes a single textarea.
The contents of the textarea [notes] shall be dynamically recorded in a table task_note where the columns will be task_note_id, task_id, task_note_category_type (project_manager_id) and task_note_category_value (id value of the category type).  You will need to request that this table be added to the database schema.
Milestone 1(d) - Prepare Task Map tab contents.  
Tab contents are shown on Slide 2.
The map will be similar to the taskLocations map, except that the markers will change color depending on their status.  Status can be “in process” or “finished”.  Status handling will be implemented at a later time, after the Field Technician module is created.  For this implementation of Milestone 1(c), simply include a view that loads the taskLocations module.

Milestone 1(e) - Prepare Task Forms tab contents.
Tab contents are shown on Slides 3 & 4.
The two columns will be populated by forms used for the Task.  Incomplete forms appear on the right. Completed forms will appear on the left side.  We have populated the database with template and completed forms in order to create the lists.  

Slide 3: The form elements are clickable.  Clicking the form will display the form.
Slide 4: The breadcrumb in the header updates with the selected form.

Milestone 1(f) - Prepare Discussion Thread tab contents.
Tab contents are shown on Slides 5 - 7. The right hand side will show the list of Service Providers and Technicians.  The Service Providers and Technicians are selectable.  

The Service Providers for the Task are identified where task.task_id = task_service.task_id and task.task_id is the selected task.   
The Technicians for the Task are identified where task.task_id = task_techncian.task_id and task.task_id is the selected task. 

Selecting one of the right hand side options opens the discussion thread (left hand side) and will set a session variable ($currentDiscussion) that will be used to control the discussion. 

Use a left arrow in the center column to select (“promote_buttons.php” module).

After selection, The breadcrumb in the header updates with the selected Technician or Service Provider.

There will be center column buttons to “Send” the new message and “Attach” files.  Use the “task_buttons.php” module as a template for the buttons.

Implementation of the Discussion thread will be a separate SOW.

**Comment by gsouvik** [comment]
@bsaiken @FWAJL 
All the related sub tasks related to this issue are closed. Just wanted to bring to your notice that it's still assigned to me. Let me know what should be the status of this issue now. Thanks.
