### ISSUE TITLE
Remove table inspection_question

### ISSUE THREAD

**Issue by WebDevJL** [FWAJL/FieldWorkAssistantMVC#408]

**Comment by bsaiken** [comment]
@FWAJL 
This table has not been dropped.  I tried to drop it, but it would not phpMyAdmin would not allow it due to a feign key restraint.  You will need to drop the table.

**Comment by FWAJL** [comment]
@bsaiken: for some reason, it didn't exist this morning when I run the sql
query (which is my job, you don't need to do). It was already deleted so
the task is done.

--
Jérémie Litzler

**Comment by bsaiken** [comment]
I just took a screen shot of our database - it is there.

![screen shot 2015-01-26 at 12 58 55 pm](https://cloud.githubusercontent.com/assets/8228624/5907302/26e92412-a55b-11e4-8c18-0e6eb6f2ffc6.png)

**Comment by FWAJL** [comment]
@bsaiken 

There was a second table related to the first. I have updated the script and ran it live. It is now done.
