### ISSUE TITLE
Analytes UI formatting

### ISSUE THREAD

**Issue by bsaiken** [FWAJL/FieldWorkAssistantMVC#409]
@WebDevJL 
I made the following changes:
nav.css
.content_left > li{
  display: block;
  padding: 2px;
  border-bottom: solid 1px #999;

This was done previously but not pushed to dev.  This allows all left menu items to appear on the screen (my laptop) without needing to scroll.

app-style.css
removed .high-textare class
(deprecated)

analyte form modules (.php)
changed .high-textarea to .list-panel 

Now all the panels are the same height.

I also had the logo updated.  That change is implemented here as well.

**Comment by FWAJL** [comment]
@bsaiken: I'll look into it.

--
Jérémie Litzler

**Comment by WebDevJL** [comment]
@bsaiken : I have merged your commit to dev. Are you done or have you got something left to commit?
