### ISSUE TITLE
Popups Discussion thread

### ISSUE THREAD

**Issue by bsaiken** [FWAJL/FieldWorkAssistantMVC#410]
@WebDevJL 
FYI:  I have hired the popups freelancer.

**Comment by FWAJL** [comment]
@bsaiken: OK

--
Jérémie Litzler

**Comment by FWAJL** [comment]
Hello @gsouvik,

Welcome to FWM. 

Please let me know if you need any help to start. Brian said you were having issue to view the branch? Is it still the case?
Also, I have added info to the database installation helper, to setup the user in particular.

Talk soon.

**Comment by gsouvik** [comment]
Hello @FWAJL ,

Thank you for your message. I've managed to setup the app on my localhost finally, I was having some issues initially.

I'll continue developing on the first milestone and shall definitely ask if I have more questions or need any help regarding the code/repo.

Thanks again,
Souvik

**Comment by FWAJL** [comment]
@gsouvik,

Please let me know what is missing from the initial installation on localhost as I would like to improve it if necessary

See issue #430 for the first milestone. You can ask question related to that milestone there. Otherwise, general question can be asked here.

Thank you.

**Comment by gsouvik** [comment]
@FWAJL 
The codebase in itself didn't have any issue. The routing was performed by the .htaccess on the root, which was hidden and I could not find it from the finder.

I think a note could be added in the wiki stating the app depends of mod_rewrite and the initial request is handled by the root .htaccess. It is quite obvious though, but someone coming in new might miss it. Just wanted to share my thought.

Thanks,
Souvik

**Comment by FWAJL** [comment]
@gsouvik : Good point. I'll add that. Thank you.

**Comment by FWAJL** [comment]
@gsouvik : please read [this document](https://docs.google.com/document/d/1COa-OrxiAMfBzTmQfwsDU2xYbwZBWwRpbOxLzmWKvW0). This will help you going forward with us.
