### ISSUE TITLE
Common lab analyes not displayed 

### ISSUE THREAD

**Issue by WebDevJL** [FWAJL/FieldWorkAssistantMVC#415]

**Comment by WebDevJL** [comment]
@bsaiken : I see them (see attached screenshot)
![screenshot_2015-01-20-08-12-49](https://cloud.githubusercontent.com/assets/3506074/5813368/b290893a-a07c-11e4-8d2a-08f424162f32.png)
. You can add some via http://dev.fieldworkmanager.com/analyte/uploadCommons

Make sure when you add some via the phpMyAdmin, you log in again.

**Comment by bsaiken** [comment]
The ability to add common analytes will be a feature we include when we 
create the login account for the admin user.

I opened an issue to start listing the items the admin user can do.  
Another thing they will be able to do is add/remove PMs.  List all PMs.  
View the data for any PM.  etc.

Brian

**Comment by WebDevJL** [comment]
@bsaiken : moved to the Admin User UI milestone.

**Comment by FWAJL** [comment]
@bsaiken : are you still having this issue?

**Comment by bsaiken** [comment]
I see them.  Closing this issue.
