### ISSUE TITLE
Build core file upload

### ISSUE THREAD

**Issue by WebDevJL** [FWAJL/FieldWorkAssistantMVC#420]
1) we need to upload files like describe in #397.
2) implement photo upload for locations to start.

**Comment by WebDevJL** [comment]
Resources: 
- http://www.w3schools.com/php/php_file_upload.asp
- http://www.dropzonejs.com/

**Comment by WebDevJL** [comment]
***Be careful of PHP.ini config:***
post_max_size is set to 8mo
upload_max_filesize is set to 2mo

@bsaiken : 
We have to limit the amount data uploaded at once. Can we define a size limit for each file?
Currently, we can upload a max of 4 files of less than 2mo each.

**Comment by bsaiken** [comment]
By "mo", do you mean "Mb"?  I think "mo" is french.

I checked our Hurray host plans and I do not see any limitations based on our plan type.  

We can talk about the upload files size we will need Wednesday.  Please add to agenda.

**Comment by WebDevJL** [comment]
@bsaiken : I meant Mb ;)

I will show how it is limited

**Comment by FWAJL** [comment]
@bsaiken: I changed the values.

post_max_size is set to 16mo
upload_max_filesize is set to 4mo

**Comment by bsaiken** [comment]
@FWAJL 
Version 1.6.1 has been released.  Is this ready to be closed?

**Comment by bsaiken** [comment]
@FWAJL
Version 1.6.1 has been released. Is this ready to be closed?

**Comment by FWAJL** [comment]
@bsaiken 

No.

**Comment by FWAJL** [comment]
Done as part of issue #523.
