### ISSUE TITLE
Modify contextual menu

### ISSUE THREAD

**Issue by FWAJL** [FWAJL/FieldWorkAssistantMVC#426]
Contextual menus to have only "Edit" and "Set". All other functions ("Save", "Delete" and "Copy") from center column buttons.

**Comment by bsaiken** [comment]
Contextual menus to have only "Edit" and "Set".  All other functions ("Save", "Delete" and "Copy") from center column buttons.

**Comment by bsaiken** [comment]
@FWAJL 
The changes I made in the commit, above:
https://github.com/FWAJL/FieldWorkAssistantMVC/commit/177ad335c9147638d9e7c9a794ef1749ac71fc52
have been lost on the feature_housekeeping branch.

**Comment by bsaiken** [comment]
I just completed the code for this.
