### ISSUE TITLE
Use arrows for activate and de-activate buttons.

### ISSUE THREAD

**Issue by bsaiken** [FWAJL/FieldWorkAssistantMVC#440]
Is there any reason not to use arrows over text for these buttons?  I prefer arrows.
I did the arrows for the Project UI, but the Title text does not appear.  Do you know why?

**Comment by FWAJL** [comment]
@bsaiken : I'm sure what you mean. Can you share a screenshot with a example? Thank you.

**Comment by FWAJL** [comment]
@bsaiken : I'm sure what you mean. Can you share a screenshot with a example? Thank you.

**Comment by bsaiken** [comment]
Here is the arrow.  

![screen shot 2015-01-26 at 9 59 20 am](https://cloud.githubusercontent.com/assets/8228624/5903952/06dfbf00-a542-11e4-9f26-f7f61a724c87.png)

**Comment by bsaiken** [comment]
It is working now.
