### ISSUE TITLE
RIght clicking is in Google chrome immediately redirects

### ISSUE THREAD

**Issue by bsaiken** [FWAJL/FieldWorkAssistantMVC#443]

**Comment by FWAJL** [comment]
@bsaiken 

I have tried all the contextual menus and right-click works and let me choose the option. 
Please be more specific and list where it happens.

**Comment by bsaiken** [comment]
@FWAJL 
It is only happening in Chrome.  I have tried everything I can think of to get rid of the issue.

Safari, Firefox, and Opera work correctly.

**Comment by bsaiken** [comment]
@FWAJL 
This is happening because in Chrome the contextual menu fires on the mousedown, and then it redirects on the mouseup.  Not supposed to, but the chromium folk won't fix it.
There is an easy work-around:
I added this to app-theme.css:
.context-menu-list{
    margin-left: 10px;
}
This way, on the mouseup event, the cursor is not hovering over the menu.  If you are OK with this fix, we can just keep it as is.
I had to made the change directly on Hurray Host because I do not get the error on my local machine.

**Comment by FWAJL** [comment]
@bsaiken 

Good find.

In the meantime, please don't change the code on the server like that.
If you can't push the updates, please ask me to do it and I will take care of it. 
Otherwise, it conflicts with my release and I have to discard the changes on the server and then I spend more time getting the code, committing and pushing it.

Thank you.

**Comment by bsaiken** [comment]
This was an unusual situation, where the problem only occurred on the 
server.  Your proposed course of action is absurd: Make changes on my 
local machine (which I have no idea of knowing if they will work), 
pushing them, waited for you to release the code, re-test...that may 
have taken weeks.

An alternative would have been for me to change the code on the server, 
then once I found the solution, deleted the code on the server and 
changed it on my local machine, then committed the code.

In this case, since it was just a small code change, I just left the 
change and advised you, knowing it would affect future releases.

Now, are you sure my approach in this case was inappropriate?

Brian
