### ISSUE TITLE
Update logo

### ISSUE THREAD

**Issue by bsaiken** [FWAJL/FieldWorkAssistantMVC#463]
I had the logo updated.

**Comment by bsaiken** [comment]
Question - why do we have a label "Assignee" when we can assign Issues another way (below Milesone is "Assignee"?

**Comment by WebDevJL** [comment]
That was for your use originally. I kept it but I don't personally use it. I assign tasks directly to the appropriate person when applicable. 

So if you want to remove the labels Assignee, go ahead

**Comment by WebDevJL** [comment]
@bsaiken 

I'll check on Monday if the logo has been released. If not I'll make sure it is.

**Comment by bsaiken** [comment]
The logo release is a low priority.  Just a slight tweak.  Whenever is 
fine.

Brian

**Comment by bsaiken** [comment]
I don't know what happened, but the logo did not update.  I uploaded the correct logo to Hurray Host.
