### ISSUE TITLE
Clean up app-style and app_theme css files

### ISSUE THREAD

**Issue by bsaiken** [FWAJL/FieldWorkAssistantMVC#465]
App-theme: colors/fonts/border style
App-style: position/margins/widths/heights

**Comment by FWAJL** [comment]
@bsaiken 

added heights to the style.

**Comment by bsaiken** [comment]
@FWAJL 
What happens when we need to apply a border style a margin to a class or id?

**Comment by FWAJL** [comment]
@bsaiken 

You have to show me because I don't understand "a border style a margin to a class or id". Is there a missing work?

**Comment by bsaiken** [comment]
@FWAJL 
What happens when we need to apply a border style and margin to a class or id?

**Comment by FWAJL** [comment]
@bsaiken 

For margin, it goes into app-style.css

For border,

- In app-theme.css, you add the css to the classes:
`border-color: #ff0000;`

- in app-style.css, you add the following css to the classes:
`border: 5px solid;` (where there is no color, just size and style of border)

**Comment by bsaiken** [comment]
@FWAJL 
So you split them.  I was starting to do that, but just wanted to make sure.

**Comment by FWAJL** [comment]
@bsaiken 

that way, it is consistent to what I told you. Thank you for spotting this details.

**Comment by bsaiken** [comment]
@FWAJL 
Is the class "legend" ever used?  There are some css styles, but the only place I see .legend used is in the index.php modules, and I can't see where any of those are used.  Aren't all the index.php modules and the .legend class deprecated?

**Comment by bsaiken** [comment]
@FWAJL 
If we have this css:
.ui-selecting { background: #FECA40; }
.ui-selected { background: #F39814; color: white; }

Is the css below redundant?:
#group-list-right .ui-selecting, #group-list-left .ui-selecting { background: #FECA40; }
#group-list-right .ui-selected, #group-list-left .ui-selected { background: #F39814; color: white; }

**Comment by FWAJL** [comment]
@bsaiken 

To first question:

Do a Command+Shift+F to find in the whole project where the word legend is used. It looks like it is not used.
I don't think we use any index.php view indeed. You deleted them if you want.

To second question:
You can put the css proposed instead the second that is redundant indeed.

**Comment by bsaiken** [comment]
@FWAJL 
Of course I did a search for .legend before I asked.  There are number of apparently deprecated classes.  Also, sometimes classes are amended or inserted with scripts, so it is not always easy to tel, even with a search.  That's why I was asking you.
I found a number of deprecated files.  I am going to test the site tomorrow and then I will commit changes with the deprecated files deleted.
As far as your answer to the second question - your sentence is gibberish. Can you please reply again.

**Comment by FWAJL** [comment]
@bsaiken 

To second question:
You can put the css you have suggested instead the second and current css. The latter is redundant indeed.
