### ISSUE TITLE
Analytes UI Specs

### ISSUE THREAD

**Issue by bsaiken** [FWAJL/FieldWorkAssistantMVC#466]
The specs for the Analytes UI is here:
https://docs.google.com/open?authuser=baiken.rides%40gmail.com&id=1onrElsC4W4lGtn-o2hXM1CrwevL7d_wPwguOuiNLJj0

**Comment by bsaiken** [comment]
@FWAJL 
I changed the status to "very high".  This will need to be done for Milestone D in the popup work, and Souvik is moving ahead quickly.

**Comment by FWAJL** [comment]
@bsaiken 

SOW doc reviewed. You can comment the docs to answer my questions. 
I'll create the issues for the updates.

Thank you.
