### ISSUE TITLE
Milestone B – Confirm Boxes

### ISSUE THREAD

**Issue by FWAJL** [FWAJL/FieldWorkAssistantMVC#479]
@gsouvik  

Commit code for the milestone B under this issue. 

Thank you.

**Comment by FWAJL** [comment]
@gsouvik 

Please read the [Workflow document](https://docs.google.com/document/d/1COa-OrxiAMfBzTmQfwsDU2xYbwZBWwRpbOxLzmWKvW0/edit) to help us organize the git issue. Let me know if something is unclear.

Thank you.

**Comment by gsouvik** [comment]
@FWAJL 
Thanks for sharing the document. I shall follow the steps outlined in that doc for the future tasks starting with milestone B.
Thanks again.

**Comment by gsouvik** [comment]
@bsaiken @FWAJL 
I've changed the way the confirm box was behaving initially. In this commit:
1) The confirm box is no longer tied to the the <li>, it could now be attached with any event, with bit of code addition.
2) The confirm box now works from the contextual menu, the delete button on the view screen (showForm) and while you "Activate" back any entity. For example if an inactive technician is activated, the confirm box appears during the process and proceeds on users action. I assume by "Activate task" you meant this.
3) Currently this is implemented only for the "projects" and "technician" screens.
Please review and let me know your feedback.
Thank you.

**Comment by gsouvik** [comment]
@bsaiken @FWAJL 
The confirm box is removed from the activate event for project/technician section. I tried implementing it for the Task but when I'm accessing the Task section I get the following warning:

Warning: Invalid argument supplied for foreach() in <My local physical path to webroot>/FieldWorkAssistantMVC/Applications/PMTool/Helpers/TaskHelper.php on line 73 Fatal error: Call to a member function project_id() on a non-object in <My local physical path to webroot>/FieldWorkAssistantMVC/Applications/PMTool/Controllers/TaskController.php on line 158 

I assume it's in development. I shall wait and do a pull after some time and see if I can access the section. I'll implement the confirm box for Task activation and update you.
Thank you.

**Comment by FWAJL** [comment]
@gsouvik 

Basically, you need a project selected to view the tasks (same for locations, analytes, services). 
In a way, it will be your task in the next milestone, I think. Using a popup, the user will be warned to select a project to view certain sections of the application.

You can work by just selecting a project in the project list. Then you will be able to view the Task list.

Let me know if you have any other issues.

**Comment by FWAJL** [comment]
@gsouvik 

Your code is clean and I think you have a good aptitude to follow how we have coded the application. 
Also, it is very nice that you follow the instructions about making the code reusable when applicable.
So I validate the commit fd16c909f1d64972e9368eb80fc423752a17719d

Thank you for that.

**Comment by gsouvik** [comment]
@FWAJL 
Thank you for the information that I would have to select a project in order to view the tasks section. Now I can access it. Also thank you for your comments regarding my code. For me It's always great to be part of new ways of coding style and project structure and I'm really excited to be able to contribute to it.

Thanks again,

**Comment by gsouvik** [comment]
@bsaiken @FWAJL 
Confirm box added to the event "activate task". Please review and let me know so that I may proceed to the next milestone.

Thank You

**Comment by FWAJL** [comment]
@gsouvik @bsaiken 

Looks good to me. Thank you.

**Comment by bsaiken** [comment]
@FWAJL @gsouvik 

Please move on to Milestone C.

Thanks

Brian
