### ISSUE TITLE
Milestone C – Alert Boxes

### ISSUE THREAD

**Issue by FWAJL** [FWAJL/FieldWorkAssistantMVC#480]
Decription:
Prepare a widget to display alert boxes at specified locations as shown in Attachment A. The text to be displayed by the alert boxes are to be in an editable xml file. Alert boxes in this context are being used for data validation. The function will need to check the content of the form for correct values before continuing.

@gsouvik  

Commit code for the milestone C under this issue. 

Thank you.

**Comment by gsouvik** [comment]
Hello @bsaiken @FWAJL
 
I've done the coding for milestone C and pushed to the feature_popup branch. In this commit:
1) As per attachment A, when adding a project the app checks if the project name and facility name are left empty. Further it checks if the project name entered is already there in the database. In each of those cases it displays an alert box. The content of the same comes from the xml file.
2) As per attachment A, exactly as in case of projects, the service provider section too checks for provider name, category and uniqueness of the name and shows the alert.

Please review and let me know if this is in accordance to the requirement.
Thank you.

**Comment by bsaiken** [comment]
@FWAJL @gsouvik 
On the front end, you applied the condition to the Facility Name, not the Facility Address.  The Facility Name can be empty, but they must enter a Facility Address.

**Comment by gsouvik** [comment]
@bsaiken @FWAJL 
I've excluded the facility name from the validation and have added the facility address. Please note that there was a previous layer of validation (a red toast message is shown on top right corner) which still checks for facility name. I haven't touched that logic. Please let me know if that needs to be modified too.
Thank you.

**Comment by bsaiken** [comment]
@gsouvik @FWAJL 

Thanks Souvik.

Yes, of course I know about the toastr messages.  We are using them during development.  Your popup work will eventually replace them, where needed.  

The front end is correct.  I will let you know, after we check the coding, when we will be ready to do Milestone D.

**Comment by bsaiken** [comment]
@gsouvik @FWAJL 
Souvik,
I talked to Jeremie, and I want you to move on to Milestone D.  However, we do want some code modifications.  You can modify C while you work on D as it is the same issue.   
You can retrieve session data, rather than querying the database, for alert and prompt boxes.  We revised our Wiki to better explain:  https://github.com/FWAJL/FieldWorkAssistantMVC/wiki/6.-How-to-code-in-the-FWM-code-base

Jeremie is preparing some more specific comments for you, so if you are not sure, wait for his input.

Thanks!

Brian A

**Comment by gsouvik** [comment]
@bsaiken @FWAJL 
I shall wait for the more detailed comments before proceeding into milestone D. 
Thanks,
Souvik

**Comment by FWAJL** [comment]
@gsouvik @bsaiken 

I won't have time to explain nor write the specific comments today. I'm sorry.

**Comment by bsaiken** [comment]
@gsouvik @FWAJL 
Souvik, There is no need to wait.  You may move on to Milestone D.  
Do keep in mind that much of the data you may need to retrieve is held in session arrays.  Using the session arrays is preferred, but not mandatory.

**Comment by gsouvik** [comment]
@FWAJL @bsaiken 
I've tested the Session object and found the projects there, I shall refactor the code for milestone C to remove the ajax call and continue with milestone D tomorrow. Shall keep you updated. 
Thank you.

**Comment by FWAJL** [comment]
@bsaiken 

Let's not close this just yet. I have not released the code.

**Comment by FWAJL** [comment]
@gsouvik @bsaiken 

Please read [this document](https://docs.google.com/document/d/1Uhx4JUmiApVc1szbA62tHKc8SJgOHZTsGAxmQwR4ueo/edit?usp=sharing) and then move on to the following:

For the projects, as you login, they are automatically stored in the Session Projects. So the step 2 will be true.
To find the project, you will call `FindObjectByStringValue` in CommonHelper class like this:

`$match = `
`        \Applications\PMTool\Helpers\CommonHelper::FindObject(`
`                "Project 358", "project_name",`
`                \Applications\PMTool\Helpers\ProjectHelper::GetSessionProjects($this->user()),`
`                \Library\Enums\SessionKeys::ProjectObject`
`        );`

For the services, you will need to perform the query to the database as we don’t load the data list in Session at login but rather on an on-demand basis.
So you keep what you have done with querying the database but only when `PmSession[PmServices]` is not set.
After querying the database, you store in Session, and perform the logic you wrote.
find the service, you will call in `FindObjectByStringValue` CommonHelper like this:

`$pmSession =`
`        \Applications\PMTool\Helpers\PmHelper::GetCurrentSessionPm($this->user());`
`if (array_key_exists(Library\Enums\SessionKeys::PmServices, $pmSession)) {`
`            $services = QueryTheDB();`
`        $pmSession[Library\Enums\SessionKeys::PmServices] = $services;`
`            Applications\PMTool\Helpers\PmHelper::SetSessionPm($this->user(), $pmSession);`
`      }`
`$match = \Applications\PMTool\Helpers\CommonHelper::FindObject(`
`    "Service Name", "service_name",`
`$pmSession[\Library\Enums\SessionKeys::PmServices]`
`);`

Please let me know if you understand all this. If not, I am more than willing to clarify.

**Comment by gsouvik** [comment]
@FWAJL 
Thank you for the documentation and the code snippet. However when I tried using it I got a fatal error stating "FindObject" not found. Then I changed that to "FindObjectByStringValue" and now I'm getting the following:

Notice: Undefined variable: prop_name in /Library/WebServer/Documents/FieldWorkAssistantMVC/Applications/PMTool/Helpers/CommonHelper.php on line 147

Fatal error: Method name must be a string in /Library/WebServer/Documents/FieldWorkAssistantMVC/Applications/PMTool/Helpers/CommonHelper.php on line 147

I did a GIT pull around 1 hour back before starting my work.

Also before your mail, I did the following code snippet which was checking the project name from Session and was serving the purpose: 
        
        $result['record_count'] = 0;
	if(isset($_SESSION[\Library\Enums\SessionKeys::UserSessionProjects]))
	{
		foreach($_SESSION[\Library\Enums\SessionKeys::UserSessionProjects] as $the_project)
		{
			//echo $the_project['project_obj']['project_name'] . ' and ' . $project;
			if($the_project['project_obj']['project_name'] == $project->project_name())
			{
				//already exists
				$result['record_count'] = 1;
				break;
			}
		}
	}
Please suggest if I should keep my code or use the one you provided, if the later is the case, please suggest how I might eliminate the errors.

Thanks,

**Comment by FWAJL** [comment]
@gsouvik 

What you wrote works but it would be better to use the logic I suggested.
I have committed a fix for the error. Please `git pull` and it should work.
Let me know. 

PS: Thank you for your progress understanding this custom framework.

**Comment by gsouvik** [comment]
@FWAJL 
It works now, shall use the methods you provided. Shall ask questions if I face any issues further.
Thank you.

**Comment by gsouvik** [comment]
@FWAJL 
I need a bit of help from you. I'm suddenly experiencing a peculiar problem when I'm accessing the following URL:
http://localhost/FieldWorkAssistantMVC/service/listAll

The controller must be "ServiceController" and the action is "executeListAll". But peculiarly not a single change I'm making to that action reflects on the frontend. I've gone as far as renaming the controller itself to something else. While all other actions start giving fatal error, the listAll action continues to show a page.

Is there any caching mechanism built into the app which might be causing this issue, or could it be git? Any help would be greatly appreciated.  

Thank you.

**Comment by FWAJL** [comment]
@gsouvik 

There is no caching. However, the url ~/service/listAll is rooted to ProjectServiceController, action manageServices.
I think that is why you don't see your updates reflected on the web page.

I hope that solves your issue.

**Comment by gsouvik** [comment]
@FWAJL @bsaiken 
I've refactored the code for milestone C to read from session if the data is available there first. I have pushed it to the feature_popup branch. Proceeding to milestone D.
Thank you.

**Comment by FWAJL** [comment]
@gsouvik @bsaiken 

I shall look at it tomorrow.

One last question: was my documentation about reading data clear? Do you understand how to use the Session data now? Please always ask if you are not sure, just like you have been doing so far. It is refreshing.

Thank you.

**Comment by gsouvik** [comment]
@FWAJL @bsaiken 
Yes the documentation explained the process. When solving a problem, mostly I'm trying to follow similar code blocks already existing in the system. I shall definitely ask about helper methods and general paradigm, if I sense that it could probably have already been implemented.
Thanks,
Souvik

**Comment by FWAJL** [comment]
@bsaiken @gsouvik 

The updates are fine. I will release on Monday.

**Comment by bsaiken** [comment]
@FWAJL @gsouvik 
This is working correctly on the live server.
Thank you
