### ISSUE TITLE
Rework the listAll UI for Analytes

### ISSUE THREAD

**Issue by FWAJL** [FWAJL/FieldWorkAssistantMVC#488]
[Slides here](https://docs.google.com/file/d/0B0NK6kSZhZ2BMzBOLTBhYVkwVE0) and [Answers to points here in the doc](https://docs.google.com/document/d/1onrElsC4W4lGtn-o2hXM1CrwevL7d_wPwguOuiNLJj0/edit).

This applies to both tabs.

1. No duplicates are allowed for Analytes (either side)
See Slide 3.  

2. The only button available is the the “Activate” button.
See Slide 4.

3. No contextual menus will be used.  Edit and delete will be available through a popup.

**Comment by FWAJL** [comment]
@bsaiken 

In point 2, please explain how does the user remove an analyte from the project list if you can only activate ?

Also I have a problem understanding the point 3. How do you initiate the edit and delete action without a contextual menu?
For me the options in the contextual menu when clicking an item will trigger the popup instead of loading the showForm view. 
Does it make sense to you and do you want this implemented (as part of issue #541)?

Thank you

**Comment by bsaiken** [comment]
@FWAJL 
Point 2: This refers to the uploadList url, not the listAll url.
Point 3: I just meant the standard contextual menus we have been using, which create a redirect.  We will use contextual menus to access the popup prompt box.

**Comment by FWAJL** [comment]
@bsaiken 

Thank you for the clarification.

**Comment by bsaiken** [comment]
@FWAJL 
This look done - is ti ready for unit testing?

**Comment by FWAJL** [comment]
@bsaiken 

It is not released, as per status. It will be in version 1.6.6.

Thank you.
