### ISSUE TITLE
Bluehost setup

### ISSUE THREAD

**Issue by bsaiken** [FWAJL/FieldWorkAssistantMVC#493]

**Comment by mehedee1** [comment]
Hi, 
I have checked http://dev.fieldworkassistant.net which is working partially. It seems to me project, Technicians, location section is working well. But getting error for Task > add > Location or technicians.
Forms field, Service provider > add > Location or technicians. 
Errors are undefined variable, non- object. 

Do you see same error or anything else? 

In addition the php is 5.4

**Comment by bsaiken** [comment]
@mehedee1 @FWAJL 
The site is working perfectly on Bluehost.  Thank you for setting this up.  The errors you are seeing are actually not errors.  In order to enable some of the menu items, the user must first select a Project.  We are in the process of implementing alert boxes to advise the user of this need.  
Nothing related to forms is working yet.  That is because this is the part of the site I am asking for your help with.
I set up the new user "pdf" with password "pdf" so you you can use the site.
I am off today, so tomorrow I will be able to discuss with you your first step to enable forms on the site.
