### ISSUE TITLE
Modify Layout to 5 - 1- 5 - 1 (12) and left margin increase

### ISSUE THREAD

**Issue by bsaiken** [FWAJL/FieldWorkAssistantMVC#506]
![project ui revision - google slides_page_1](https://cloud.githubusercontent.com/assets/8228624/6179997/73401cd8-b2dc-11e4-84ba-92f0a8f97c08.png)
![project ui revision - google slides_page_2](https://cloud.githubusercontent.com/assets/8228624/6179998/734401fe-b2dc-11e4-8d0f-fe2fef502141.png)
![project ui revision - google slides_page_3](https://cloud.githubusercontent.com/assets/8228624/6179999/734620a6-b2dc-11e4-8d89-d2c335259e70.png)

**Comment by bsaiken** [comment]
@FWAJL 
I started mapping out the DIV structure of all our pages:
https://docs.google.com/document/d/1qIjBqQrEeCugH4pJHewCdZHZSlqSBIkYSiI39ZjyCTM/edit
There are some inconsistencies and I think we can create a template that applies to all pages.
Take a look at this and we can discuss at our next meeting.

**Comment by FWAJL** [comment]
@bsaiken 

What are the inconsistencies according to you?
To me, the map view is an obvious exception.
The rest is consistent. Please prepare a list for the cases you think it is not.

Thank you

**Comment by bsaiken** [comment]
@FWAJL 
I changed the layout by just changing lg-md-2 to lg-md-1.  This also but some white space on the right, with I wanted.
A few minor other margin changes.
I also changes the forms so the text boxes and areas are uniform and use the space.
A few deprecated files were removed.
