### ISSUE TITLE
Mapping - Milestone E

### ISSUE THREAD

**Issue by bsaiken** [FWAJL/FieldWorkAssistantMVC#524]

**Comment by bsaiken** [comment]
@damirius 
Isn't this complete?  I reviewed it an it worked...

**Comment by damirius** [comment]
@bsaiken

This was pushed and reviewed together with Milestone D. So we can close this issue.

**Comment by FWAJL** [comment]
@damirius 

Next time, can you please push to the appropriate issue? This way, we can track what is done or not. Thank you.

**Comment by damirius** [comment]
@FWAJL

Commit was for both issues at the same time. I'll mention both in the first comment if it comes to that again.

**Comment by FWAJL** [comment]
@damirius 

Yes, I saw it in the comment of the commit. But I prefer you commit the code in the appropriate issue still.
Also, keep in mind that small commits are easier to review, check and so on than commits with large amount of updates and files updates.

Thank you for taking this into account for the future dev. I will really appreciate.

**Comment by bsaiken** [comment]
@damirius 
I tested the code on the live site.  There is bug in Milestone E.

I added a new Project, and gave it the Facility Address: "12 Market Street, San Francisco, CA"

The new Project was created (Project 875), but the coordinates are the default coordinates.  

Although I did not intend it, this is a real address, and the coordinates should be: 37.7943919,-122.3948491.

**Comment by damirius** [comment]
@bsaiken

It doesn't work, because the code is gone somehow from the branch. You can see it in my commit here:
https://github.com/FWAJL/FieldWorkAssistantMVC/commit/272da25e5987200f0daff3da15e90699bc60e33a under project_manager.js. I can't find it on the current version of the branch.

**Comment by bsaiken** [comment]
@damirius @FWAJL 
Good grief - it's not on the live site yet.  Jeremie has not released it.  My bad!

**Comment by damirius** [comment]
@bsaiken

The thing is that I did all that in one take, because we talked about that and you said you need everything done over the weekend, so everything was done in one commit.
If that isn't there than all the other stuff from Milestone D shouldn't be there as well, info windows for locations and task locations, photo upload, highlighting markers and so on.

**Comment by bsaiken** [comment]
@damirius 
I don't know all the details of the merge process.  I think code can get lost if there are conflicts.  It happens to me all the time.
In this case the code was committed under the wrong Issue, so that may be why - not sure.
I'm sure no work is lost, we just need Jeremie to sort it out.

**Comment by damirius** [comment]
@bsaiken

I've added the project_manager.js code back on my local version of the branch and luckily it's just that missing from the first look. So if needed we can add it as the separate commit.

**Comment by FWAJL** [comment]
@damirius 

Please commit it here since it is the right place and let's be careful about commit that are too big. They will always create problems.

Sorry for causing the problem with the merge.

Thank you for your help.

**Comment by damirius** [comment]
@FWAJL 

I've added the code back in the project_manager.js and tested it by adding new projects. I don't know if we want to put this on the function review again or not so I left it like this.

Thanks

**Comment by FWAJL** [comment]
@damirius 

Merge done. Moving to release step.

**Comment by bsaiken** [comment]
@FWAJL @damirius 
I am confused where this code resides.  I wanted to check function, but I can't find it on any branch.

**Comment by damirius** [comment]
@bsaiken

You can see it in my referenced commit above, it's in project_manager.js on feature_mapping branch now: https://github.com/FWAJL/FieldWorkAssistantMVC/commit/10f74fb407e073b8063c670f565ef5b795835963

It's used for geocoding address for new projects.

**Comment by bsaiken** [comment]
@damirius @FWAJL 
More unit testing needed, but I am closing now and if I see strange behaviors we will make a new Bug Issue.
