### ISSUE TITLE
Promote Project Locations to Task Locations not working.

### ISSUE THREAD

**Issue by bsaiken** [FWAJL/FieldWorkAssistantMVC#529]
Error Loading Tasks

**Comment by FWAJL** [comment]
@bsaiken 

I tested it and it works. Please provide more details about your context.
Is the site slow loading page? Are you having Internet connection problems? 

Thank you.

**Comment by bsaiken** [comment]
@FWAJL 
I was using internet explorer.  First time I have tested with that browser.

**Comment by FWAJL** [comment]
@bsaiken 

Ok, two solutions:

1. Have someone take care of IE support.
2. Have someone to add a message for IE users to use either Chrome or Firefox.

I find a lot of issues with IE with my main job and it will be time consuming to solve all of them.

Thank you.

**Comment by bsaiken** [comment]
@FWAJL 
I checked IE again this morning - it is working.  I will be doing more IE tests in the future.  So, for now, I will keep this issue open at low priority.
