### ISSUE TITLE
Move the Maps API js file so it doesn't load on every page

### ISSUE THREAD

**Issue by FWAJL** [FWAJL/FieldWorkAssistantMVC#532]
Add it to the map routes only.

**Comment by FWAJL** [comment]
@bsaiken 

Already live.

**Comment by damirius** [comment]
@FWAJL 

I know this is closed, but I just want to say that adding version number on the end of every external script will break few things.
Take a look at this link https://maps.googleapis.com/maps/api/js?libraries=drawing,geometry?v=1.6
If you remove ?v=1.6 it will work properly and geometry library will be properly loaded.
Is there a reason to add the version for external scripts?

**Comment by FWAJL** [comment]
@damirius 

I will remove the version from the external librairies.

Thank you for spotting that.
