### ISSUE TITLE
Task Services UI

### ISSUE THREAD

**Issue by bsaiken** [FWAJL/FieldWorkAssistantMVC#555]
Same as Technicians, Analytes, etc.  Very simple.  Just promote from Project Services to Task Services.

I know we talked about other functions, but I just realized the other functions won't be here - that will be in the Task Monitoring UI.

The Task UI only builds (inactive) tasks.

**Comment by gsouvik** [comment]
@bsaiken @FWAJL 
The requirement is not clear to me, could you please share a user requirement document explaining step by step what needs to be done.

**Comment by bsaiken** [comment]
@gsouvik 
The Task Services tab is very similar to the "Technicians" and Locations" tabs.  Let me walk you through each.

If you navigate to Technicians > List All, you will see two columns: Available Technicians and Unavailable Technicians.  Available Technicians could be thought of a "Project Technicians".  These Technicians can work on any Project (or any Task).  A Technician might be unavailable because they are on vacation, or working on another project. 
Now, if you navigate to the task technicians tab (Task > List All >> Edit > [Technicians]) there are two columns: Task Technicians (left) and Available Technicians (right).  The Available Technicians in the task tab are the same as at Technicians > List All (right column).  
Now, to build a Task, I can chose which Technician(s) will perform the Task from the Available Technicians.  If you click on one or more names in the right hand Available Technicians column, the left arrow will appear and you can "promote" these Technicians to be Task Technicians.  This is who will perform the work.

Similarly, if you navigate to the URL: /locations/listAll, there are two columns: Active Locations and Inactive Locations.  Work can only be performed at Active Locations.  So, when you navigate to the url /task/locations, you see two columns: Project Locations (right) and Task Locations (left).  Project Locations are the same as Active Locations - maybe I will change the header text to make this clearer.  Now, to continue to build the Task, I choose from the Active Project Locations (on the right) and "promote" them to Task Locations.  Task Locations is where the work for that task will happen.

Task Services UI follows the same logic.  If you click on Service Providers > List All you will see two columns: All Service Providers (right) and Service Providers for this Project (left).  Only Project Service Providers will appear on the /task/services tab (right) and from this list, the user can select Service Providers that will be needed for the Task (Task Services, in the left hand column).

I am trying to keep the logic as uniform as I can for each UI, so that the user only has to learn one way of doing things.  There will be a Task Forms tab, and it will behave the same way.

If that is unclear let me know, I will make mockup slides of the Services tab.

**Comment by gsouvik** [comment]
@bsaiken Thank you for explaining the requirement so clearly. I've understood it, shall complete and update.

**Comment by gsouvik** [comment]
@bsaiken 
I've completed the primary round of coding for the Task services screen. The code is pushed to "feature_devsupport".

I did notice one issue which I'm not sure if it was a requirement from the beginning, so would like to ask you about. The task service Tab opens only when "Outside Resources required" is checked. Even if I check it and save the task, it is not recorded in the database. Let me know how this should work.

@FWAJL 
Could you please give me a hint from where the task tabs are controlled. I mean how can I choose which one to show. 

Thank you.

**Comment by bsaiken** [comment]
@gsouvik 
The Issue you have identified is Issue #437 and has been assigned to someone else.  Once this is complete, the box will stay checked.  For now, you could just disable the JQuery that hides the tab: tabs.js line 88.  While you are at it, correct the typos and add semicolons at the end of the lines.

**Comment by bsaiken** [comment]
@gsouvik 
The promotion feature works correctly.  
You need to change the modules from "group_list_" to "categorized_list_".

**Comment by gsouvik** [comment]
@bsaiken 
1) Lists changed from "group_list_" to "categorized_list_". Changed all relevant coding involved.
2) JS code switched off to keep "services" tab always visible. Added semicolons and code formatting wherever applicable.

**Comment by bsaiken** [comment]
@gsouvik @FWAJL 
Thanks - you don't need to wait for this task to be reviewed to start the next one, like before.  Just make sure the commits are separate for each Issue.
