### ISSUE TITLE
Task COC UI

### ISSUE THREAD

**Issue by bsaiken** [FWAJL/FieldWorkAssistantMVC#558]
Use task_coc_info_form.

**Comment by gsouvik** [comment]
@bsaiken 
I've completed the primary round of development of the Task COC UI. While developing I found the table is having a foreign key dependency with services table. I've added a "service_id" field on the UI to provide the service id manually for the time being while we are testing. I'm not sure how we can let the user select a service provider on this screen.
Please review and let me know the changes if any, and I shall modify accordingly.
Thank you.

**Comment by bsaiken** [comment]
@gsouvik 
This is a good start.  I need to give you some more specs on this to continue, so let's table this for now.

**Comment by bsaiken** [comment]
@gsouvik 
Instead of the form field "Service Id", add a select list before Sample Type.  

The Select list Label is "Laboratory".

To create the select list options, use Service Providers that have "Laboratory" as the category.  The Laboratories should be in the task_service list.  
The default select list value is "Select".

Change the "Send Results To" header to <h4>.

The following form fields should have the specified default values:
`name="results_to_name"` -->  `project_manager.pm_name`
`name="results_to_company"` -->  `project_manager.pm_comp_name`
`name="results_to_address"` -->  `project_manager.pm_address`
`name="results_to_phone"` -->  `project_manager.pm_phone`
`name="results_to_email"` -->  `project_manager.pm_email`

**Comment by bsaiken** [comment]
@gsouvik 
The "Send Results To" header should be h4, not h3.

**Comment by gsouvik** [comment]
@bsaiken 
1) "Laboratory" select added. It lists all the service providers which are categorized as "Labs" and are associated with the Task in question.
2) "Send results to" section is now populated with current project manager data as default values.
3) The send results to header is changed to H4 from H3.

Thank you.

**Comment by bsaiken** [comment]
@FWAJL @gsouvik 

Jeremie,
This tab is working in terms of displaying info and pre-populating fields.  This is not finished, but I would like Souvik to move to the next Issue, #728, as it is a bottleneck.

Please complete this Issue before releasing (a bit of coding for you!).  

* Save the form data to the database when the user clicks "Save".  
* Make sure that, when loading the form, to look first at the values in the `task` table, then, if form fields listed above are empty or NULL, use the values in the `project_manager` table.

I know the form needs to be cleaned up.  For example, the select list text needs to be put into resx files.  I can do that later.  I need this right away to continue with forms development.

Thanks.

**Comment by FWAJL** [comment]
@bsaiken 

I use FWAJL for general use like release, code review in the GitHub website.

When I set WebDevJL, it means I'm coding in the issue. So please don't change the assignment. 
This doesn't change anything for you, I believe. Otherwise tell me.

Thank you.

**Comment by bsaiken** [comment]
@FWAJL 
Ohhhh.  I wondered why you had two.  Makes sense.

**Comment by FWAJL** [comment]
@bsaiken 

One is the architect / project manager. The other is the developer.

**Comment by FWAJL** [comment]
@bsaiken 

See the database update on issue #945. The Service select list is removed.

You can now test from the dev branch.

Thank you.

**Comment by bsaiken** [comment]
@WebDevJL 
I am still seeing required fields (which should not be required) and it is not saving.  

![screen shot 2015-05-04 at 1 58 19 pm](https://cloud.githubusercontent.com/assets/8228624/7462368/c170b5de-f265-11e4-8185-3364cd960350.png)

![screen shot 2015-05-04 at 1 58 29 pm](https://cloud.githubusercontent.com/assets/8228624/7462372/cb7ed754-f265-11e4-9a41-6f502fc8e117.png)

**Comment by bsaiken** [comment]
@WebDevJL 
Now, I have had some trouble on my local machine getting things working and they work fine on the live site.
So, if you are sure this is working, I am OK with you pushing the code and I will enjoy seeing it live.

Yes, I did do the database update and pulled an update from the DEV branch, so that is not it.

**Comment by FWAJL** [comment]
@bsaiken 

Please run this locally:

```
USE `baiken_fwm_1`;

ALTER TABLE `task_coc_info`
MODIFY COLUMN `service_id` int(11) NULL COMMENT 'Lab ID number';
```

and do a git pull for the required field update.

Then it will work as you want.

Thank you.

**Comment by bsaiken** [comment]
@FWAJL 
Yes, thanks.
