### ISSUE TITLE
Modify tooltips

### ISSUE THREAD

**Issue by bsaiken** [FWAJL/FieldWorkAssistantMVC#560]

**Comment by bsaiken** [comment]
@FWAJL 
I am preparing to modify the tooltips so they appear on the list header glyphicon instead of each item.  I also want the tooltips universally available and editable (html enabled).  

As an aside: In working on the tooltips I found some mistakes in the css files, which I corrected.

These commits are ready to release.

But before going forward I have a question.  I am comparing the code for the active_list.php and inactive_list.php.  These two modules are different.  Too many lines vary to list.  Which is the correct coding method?

**Comment by FWAJL** [comment]
@bsaiken 

Use what is done in the active_list module.

I have unified the 2 modules to be consistant.

**Comment by FWAJL** [comment]
@bsaiken 

So far the code is done to add the "i" and "?" glyphicon.

**Comment by bsaiken** [comment]
@FWAJL 
This is all going to get redone entirely.
This change is just a sample for Souvik to follow.

**Comment by FWAJL** [comment]
@bsaiken 

I understand. I will release it then.
