### ISSUE TITLE
Refresh cache on client side to solve js and css files update issues

### ISSUE THREAD

**Issue by FWAJL** [FWAJL/FieldWorkAssistantMVC#571]
Add version number to js and css files path when building each page.

**Comment by FWAJL** [comment]
@bsaiken 

It looks like it is working for me. Hopefully it will for everyone too in the live url.

**Comment by bsaiken** [comment]
@FWAJL 
I have had no problems, so I will close and re-open if it starts again.
Getting rid of the Google maps API on every page made a bid difference.

**Comment by FWAJL** [comment]
@bsaiken

I'm glad you are happy with the solution.

Thank you.

--
Jérémie Litzler
