### ISSUE TITLE
Revised Popups SOW - ToolTips

### ISSUE THREAD

**Issue by bsaiken** [FWAJL/FieldWorkAssistantMVC#587]
@gsouvik 
Re-write active_list.php and inactive_list.php to remove the tooltips from the listed items.  I already made archive files active_list_archive.php (etc.) so the work is not lost.

Replace with tooltips as shown in revised popups sow.pdf.  I have modified the Project > List All UI to show the proper application.  Except, I did not complete the tooltip - I just have a span title as a temporary substitute.  
The tooltip content is not important - I can edit the xml file later.  Please insert some "dummy" text.

**Comment by gsouvik** [comment]
@FWAJL @bsaiken 
I have a question which is common for all the tasks I would be working on in the coming days. I was unsure where to post it, so I just put it here. Do I continue developing on the feature_popup branch for this task and the other ones like "autocomplete"?
Thank you.

**Comment by FWAJL** [comment]
@gsouvik 

Yes, keep working on it, please.
Thank you.

**Comment by gsouvik** [comment]
@FWAJL @bsaiken 
Just a small status update - New tooltip coded till row 10 of "Revised Popups SOW". Shall complete the rest and commit again.
Also, this issue too has multiple parts, for example tooltips, alerts, confirm and prompt boxes. Wondering if it's a good idea to break those into different issues.
Thank you

**Comment by bsaiken** [comment]
@gsouvik @FWAJL 
Whether or not to make separate Issues is up to you and Jeremie.  I don't need it to track progress.  Also, since you are now hourly I do not need it to track payments.  Still, I understand that for Jeremie's review, it may be beneficial.

**Comment by bsaiken** [comment]
@gsouvik @FWAJL 
I have created the attached file to aid in tracking.  I added item numbers, so you can identify which you have done.  I have already highlighted the one I see you have completed.
![revised popups sow - progress_page_2](https://cloud.githubusercontent.com/assets/8228624/6435667/0cc92594-c060-11e4-847b-723fc8dd0dc0.jpg)
![revised popups sow - progress_page_3](https://cloud.githubusercontent.com/assets/8228624/6435668/0cce717a-c060-11e4-9df7-6c18adc31e16.jpg)
![revised popups sow - progress_page_1](https://cloud.githubusercontent.com/assets/8228624/6435669/0cd1749c-c060-11e4-9ecb-cca1aaa63f26.jpg)

**Comment by FWAJL** [comment]
@gsouvik @bsaiken 

Since the work has already started, please do a single commit for each item under this issue.
- Do a `git add` for the files of a given item in the list
- Do a `git commit -m "Issue #587" -m "item X"` to commit the item in the list individually.

I would understand if you already committed everything locally.

Thank you.

**Comment by bsaiken** [comment]
@FWAJL 
Jeremie, the control file (in case you would like to see it) is here:
https://docs.google.com/document/d/1nBIZciJDj5_M6JgzYy7q1YdgY8h1Kx3BKXxwGkw795o/edit

**Comment by FWAJL** [comment]
@bsaiken 

Thank you for sharing

@gsouvik 

After looking at the whole list just now, I have created a separate for each popup type (Alert, Prompt, Confirm, etc). This issue 587 is for the ToolTip since you've started already.

Keep committing the code I have described above in the all issues please.

Confirm: issue #591
Alert: issue #592  
Prompt: issue #593 

Thank you.

**Comment by gsouvik** [comment]
@FWAJL @bsaiken 
Thanks, now that we have separate issues I'll commit under those. If a task is partially complete, I'll commit it under the relevant issue with list of items in the message.

**Comment by gsouvik** [comment]
@bsaiken @FWAJL 
I just noticed a requirement which might be conflicting each other, so I wanted to confirm. For item 18 and 29, a tooltip and an alert box is required. But the trigger in both the cases is click() on the same icon. Does that mean, clicking on that glyphicon both the tooltip and the alert box would show up? We would also have to keep in mind, the alert box dims the background. Please let me know.
Thank you.

**Comment by bsaiken** [comment]
@gsouvik 
You are correct.  I made a mistake.  item 18 should be on hover().  The tooltip will say "Click to see map legend".

**Comment by gsouvik** [comment]
@bsaiken @FWAJL 
According to Revised popup SOW no 15, 16 and 17 we have to add the tooltip to the div with id=map-info-ruler-icon. When added, it looks like this
![inner_div](https://cloud.githubusercontent.com/assets/2292482/6444206/044135a2-c122-11e4-9c8e-a7c53dc6c0b9.png)

But if it is added to it's outer div (map-info-ruler), it looks like the following:
![outer_div](https://cloud.githubusercontent.com/assets/2292482/6444208/084ae8d2-c122-11e4-8271-c93ea9e6d260.png)

I think as it is wrapped within another div, the tooltip is not getting enough space to display correctly when added in the inner div. Please let me know where we should add it. In any case it is configurable with the controller / xml combination in terms of parameter.

Thank you.

**Comment by bsaiken** [comment]
@gsouvik 
In fact, all the tooltips should be on hover - it was just a typo.

**Comment by bsaiken** [comment]
@gsouvik 
With respect to the map sidebar tooltips, this will need to be re-formatted as the icons and the entire side bar is too large.  I suggest you skip this for the moment and I will look today at the formatting.

**Comment by gsouvik** [comment]
Thanks @bsaiken for the info.

**Comment by bsaiken** [comment]
@gsouvik 
I looked at the mapping layout and it may take some time to fix this.  
So, I would hold this until the end.  
In the mean time, think about using the "container" option
http://stackoverflow.com/questions/19630749/how-to-make-bootstrap-3-tooltip-work-with-parent-div-with-overflowhidden

or, we could just use a title, as shown in the screen shot, whihc would be an acceptable solution for me.

![screen shot 2015-03-02 at 11 25 49 am](https://cloud.githubusercontent.com/assets/8228624/6447376/fc61804c-c0ce-11e4-8650-45e375a12677.png)

**Comment by gsouvik** [comment]
@bsaiken 
The container option would let us attach the tooltip to any container of our choice which is parent to the control where the tooltip is added. Which is similar to the case where we directly add it to it's parent div i.e. map-info-add. It doesn't break the UI and looks good (shared a screenshot earlier). It might be a solution for the time being. Let me know your thoughts.

**Comment by bsaiken** [comment]
@gsouvik 
Whatever Firefox Inspector does to add it's tooltips, it looks just like I would want.  The tooltip is on top (out of the way) and the w to the icon.  Can we do that?

![screen shot 2015-03-02 at 12 14 51 pm](https://cloud.githubusercontent.com/assets/8228624/6448260/ed327a7a-c0d5-11e4-9b74-d465f9dc49ef.png)

**Comment by gsouvik** [comment]
@bsaiken 
Understood, this is how it looks like when we apply the tooltip to it's parent container and place it on top. I've added both the screenshots for double line and single line. Please review and let me know, if you don't prefer this, we can set the basic title as suggested by you previously.

![single_line](https://cloud.githubusercontent.com/assets/2292482/6448616/41e7c280-c141-11e4-8ab5-63f8ff6d2fd5.png)
![double_line](https://cloud.githubusercontent.com/assets/2292482/6448618/43a2d894-c141-11e4-99e7-2cc389318c93.png)

**Comment by bsaiken** [comment]
@gsouvik 
Looks great.

**Comment by gsouvik** [comment]
@bsaiken @FWAJL 
The remaining items for the tooptip issue is completed. Points 15, 16 and 17 from the SOW are implemented only for the map/allProjects screen, as we discussed that the UI might change for that section on all the relevant pages. Let me know if I should add this to the other pages too, and I shall do the same.

For the screens "Task > List All >> Edit > Technician tab" and "analyte/uploadList" both tabs, somehow the bottom and top margins for the span.h4 is not taking any effect. It seems we have to add some CSS fix for those. Let me know if I need to look into those.

Thank you.

**Comment by bsaiken** [comment]
@gsouvik @FWAJL 
Yes, I will need to add a span class there as well as for the Service Providers view.
I'll take care of it today.  Jeremie will likely be able to push the change to your branch tomorrow.

**Comment by bsaiken** [comment]
@gsouvik 
The problem is not css.  We have an inconsistency in our div structure for the technician and location tabs.  In order to match the div structure, you need to add two divs before col-lg-5, like this:

<div class="content-container container-fluid">
  <div class="row">
  <div  class="col-lg-5 col-md-5">

Then you need to close out the divs at the bottom of up_field_analyte_lists (and _lab_).
I also found a typo and one of the </div> is missing the end bracket (</div).

I actually made the fix but accidentally did it on the feature_popup branch.  Since you were working at the same time, there are conflicts and I can't push the changes.

I have save a file showing my changes, which includes some related formatting items, and uploaded it to eLance.  In case you want to look.

**Comment by bsaiken** [comment]
@gsouvik @FWAJL 
Let's use this Issue now instead of #615. 
I will fix the div structure.
Outstanding items:
13a
14a
15
16
17

**Comment by gsouvik** [comment]
@bsaiken @FWAJL This is completed as per issue #615.
