### ISSUE TITLE
Revised Popups SOW - Confirm  Boxes

### ISSUE THREAD

**Issue by FWAJL** [FWAJL/FieldWorkAssistantMVC#591]
All the details here: 
https://docs.google.com/document/d/1J4FdPNLQT8Wls87Cybk6pvmHp2sZeOdAj-_ehFex4zc/edit

**Comment by gsouvik** [comment]
@bsaiken @FWAJL 
The confirm boxes are complete as per requirement defined in Revised_Popups_SOW_3_4_2015.
Thank you.

**Comment by bsaiken** [comment]
@gsouvik 
Please apply confirm box to:  id="btn_delete_task"

**Comment by gsouvik** [comment]
@bsaiken 
Confirm box applied to  id="btn_delete_task".
Thank you.
