### ISSUE TITLE
Revised Popups SOW - Prompt  Boxes

### ISSUE THREAD

**Issue by FWAJL** [FWAJL/FieldWorkAssistantMVC#593]
All the details here: 
https://docs.google.com/document/d/14P3Q-WD4BhlufjOs6wlgxQxDYD42CeV8hjMcifcWOXQ/edit

**Comment by gsouvik** [comment]
@bsaiken 
For the requirement described on row 34 of the SOW (3-4-2015) what happens if a project is not selected at first place? In that case showing a list of task doesn't make sense as the tasks themselves are project specific.

Please specify how the system should behave, should it first prompt for selecting projects and then tasks?

Thank you.

**Comment by gsouvik** [comment]
@bsaiken 
Sorry for sending this as a separate message from the earlier one. I have a question for row 35 and 36 as well for SOW (3-4-2015).

The requirement states "On <Ok>, check to see if location_name/location_name(s) is unique."
I assume by OK you mean the "Add" buttons on the respective pages. In other words user fills up data in the field "location_name" and clicks "Add" and our alert should say "Location Name is taken". Please let me know if my understanding is correct.
Else please explain the correct flow of events which should show the prompt/alert box.
Thanks!

**Comment by bsaiken** [comment]
@gsouvik 
For row 34, add a second popup (34a) that asks the user to select a Project first, then direct them to select a Location.

**Comment by bsaiken** [comment]
@gsouvik 
Clicking <OK> would be in the Prompt box.  The user is adding a new Location, and we need to verify the Location name is unique.  I may have worded it in an awkward way.  The intention is to verify that Location names are unique, the same way we verify that Project names are unique.  Item 36 is a bit more complex because you need to check that all the Location names are unique.  I am not sure how that is done, so I am relying on you to determine the best way.

**Comment by gsouvik** [comment]
@bsaiken 
I've completed the items described on row 31, 32 and 33 of the Revised SOW 3-4-2015. 
Steps to test:
1) Clicking on Analytes > List All, if a project is not set as current project yet, the user is shown a list of projects on a prompt box. Selecting a project and clicking OK, takes the user back to Analytes > List All.
2) Clicking on Map > Selected Project, if a project is not set as current project yet, the user is shown a list of projects on a prompt box. Selecting a project and clicking OK, takes the user back to Map > Selected Project.
3) Clicking on Map > All Project location, if a project is not set as current project yet, the user is shown a list of projects on a prompt box. Selecting a project and clicking OK, takes the user back to Map > Selected Project.

@FWAJL @bsaiken 
I've also worked on row 34, but it's not functional perfectly. It shows the list of Tasks. But somehow on my feature_popup branch the code "task_manager.set(<list_element>)" is not working. In other words the code to set a task as "current task" is not working on my branch. I noticed it is working on dev. @FWAJL please suggest if I'm doing something wrong or it is not yet to be merged into my branch from dev.

Thank you.

**Comment by bsaiken** [comment]
@gsouvik 
As a stopgap measure, you can set the current Task by editing the task.  The set current Task buttons are functional, but may not be pushed to your branch.  However, I as I stated, editing a Task sets it as the current Task, so it's a temporary workaround to keep your work going.

**Comment by bsaiken** [comment]
@FWAJL 
OK to code review all but Items 35 & 36.
https://docs.google.com/document/d/14P3Q-WD4BhlufjOs6wlgxQxDYD42CeV8hjMcifcWOXQ/edit

**Comment by gsouvik** [comment]
@bsaiken 
Yes, editing a task would set it as current, but from the context of #593 row 34, it won't be much help. I need to have the "set as current task" functionality working, so that the user can select the task from the prompt box.

@FWAJL I tested this morning too, and found the functionality is working on dev but not on my branch. I hope it's not yet merged to my branch. I'll continue with the other tasks and shall wait for your confirmation so that I can revisit to this task.

Thank you.

**Comment by FWAJL** [comment]
@gsouvik 

It is. Just fix it and I'll merge the fix.
Just take the code on the dev branch before the merge (https://github.com/FWAJL/FieldWorkAssistantMVC/commits/dev) and add the right code again.

Thank you.

**Comment by gsouvik** [comment]
@FWAJL @bsaiken 
Completed row 34 of #593 Revised SOW 3-4-2015. 
Clicking Map > Task Location checks if a project is set as current, else shows a prompt box to select one. Next it checks if a task is set as current task, else shows a prompt box to select task. If user selects a task, returns to map/taskLocations.
Thank you.

**Comment by bsaiken** [comment]
@FWAJL @gsouvik 
Only items remaining are 35 and 36.

**Comment by gsouvik** [comment]
@bsaiken 
Row 35 completed. While adding locations if you click on the field 'location_name' if shows the prompt box to enter the new location name. Clicking on OK would check if the name is unique, else it would show the alert box letting the user know about the same. If a unique name is entered, the same is added and the screen redirects to showForm with that location loaded for editing. 

Started with row 36. I read your explanation on this point earlier in the thread, but after going through the requirement I still have the following points:
1) Going by the logic of row 35, clicking on the textarea 'location_name' should open up a prompt box with a textarea in it. This is where the user types in location names separated by new lines (by pressing Enter key). Clicking on OK, the system checks for uniqueness of the locations just entered and redirects to upload location screen with the location names which are not unique, highlighted as red. The problem with this approach is, location_name field is a textarea, I cannot show rich content like highlighted text on it.
1) Secondly, if the prompt box is actually used for entering data, the location_name textarea becomes pointless.

I have the following suggestion to overcome the above two points:
1) Let's allow users entering data into the main "location_name" textarea. 
2) When they click on "Add" let me check for the uniqueness of the location names just entered. If duplicate names are found, let me just show an alert box with the names highlighted in red in a list box and ask them to correct those in the main location_name field.
3) They correct the names and click 'Add' again. This time if no duplicate names are found, the new location names are added to the system.

This way the UI works with fewer steps and redirects, and we make sure, all the location names are always unique. 
Let me know your thoughts.

Thank you.

**Comment by bsaiken** [comment]
@gsouvik 
I will admit to you that I did not know what would be required to accomplish this item, so my instructions are vague.  It sounds as though you have worked it out - I would like to see your proposed solution.

Duplicate Location names (under a single Project ID) are forbidden.  I believe in this scenario, the most likely user response would be to simply delete all duplicate entries, so we could save them the time: 

* accept and add Locations that are not duplicates 
* advise the user (alert box) that duplicate Location names were not added.  We could show them this list, or not.

**Comment by gsouvik** [comment]
@bsaiken Thanks, I'll code and push the changes shortly.

**Comment by gsouvik** [comment]
@FWAJL I just pulled feature_popup and again my finished code is not there. Issue #593, row 32 and 33 is not working on my branch. This has been tested and in fact released in the earlier version. Now it's gone. I think the feature_mapping branch is not updated with latest code from feature_popup regularly. 

@bsaiken Just updating,  I've to again go back to previous version of my branch and re-work the fix.

**Comment by FWAJL** [comment]
@gsouvik 

I'm sorry. I think there was too much code difference in the mapping branch and git didn't perform the merge properly. I also possibly made a few mistakes in the merge conflicts, that were numerous and complex.

The mapping branch is indeed up-to-date now.

I will do my best to avoid this in the future. Thank you.

**Comment by gsouvik** [comment]
@FWAJL No worries, I just updated the status, I'm re-doing everything on my branch now and push later tonight. Thank you.

**Comment by gsouvik** [comment]
@bsaiken 
I've implemented the solution I proposed yesterday for row 36. Here are the steps to test it:
1) Add locations in the textarea as you would normally do.
2) Click on "Add", it checks for uniqueness of the data.
3) If location(s) found to be duplicate, alert shows with message and list of locations which are duplicate.
4) User can manually delete the duplicate locations and click Add again to normally add all the locations into the system.

Please review and let me know if this works good.
Thank you.

**Comment by gsouvik** [comment]
@bsaiken 
With reference to eLance document  Popups Issue 593 - 3-11-2015.pdf, 35 and 36 are working on feature branch, 35 was pushed yesterday and 36 today few hours back.

35 is dependent on list of locations for project already in Session. So if the list is not initialized on Session, 35 might have some issue. Let me know if I need to load location list into session first and then check for duplicate values, if it's already not available.

Thanks.

**Comment by bsaiken** [comment]
@gsouvik @FWAJL 
I have not completed my function review of items 35 and 36 yet.  We got pretty backed up, but I will have these reviewed by the end of the day.  I did a preliminary review and I'm not sure I liked the implementation.  So, let's not fix any bugs until I make a final decision.

**Comment by bsaiken** [comment]
@FWAJL @gsouvik 
I did not like the implementation of items 35 and 36, so I am closing this issue and I will create separate Issues for items 35 and 36.  This really falls into the category of data validation, and I was planning to create a data validation milestone/Issue set later.  Also, this application is clearly more complex than others, and it requires further thought on my part as to how to implement that data validation part.
