### ISSUE TITLE
Milestone A – Tooltips

### ISSUE THREAD

**Issue by FWAJL** [FWAJL/FieldWorkAssistantMVC#615]
@gsouvik 

Commit the code under this issue the last 2 items.

Thank you.

**Comment by bsaiken** [comment]
Outstanding items:
13a
14a
15
16
17

**Comment by gsouvik** [comment]
@bsaiken 
I'm in the process of coding those, shall update after a short while. For 15, 16, 17, i assume those needs to be updated to all the map related pages. Currently it is done only for the allprojects page.

**Comment by gsouvik** [comment]
@bsaiken @FWAJL 
Outstanding tooltip items completed. Comprises of 13a, 14a, 15, 16 and 17 from SOW.
Thank you.

**Comment by bsaiken** [comment]
@FWAJL 
https://docs.google.com/document/d/1Ps3FB3CJXtVRnn5tB2p41jO2lsi1M0WKqYLhs78lXDY/edit
