### ISSUE TITLE
Mapping Bug Fix

### ISSUE THREAD

**Issue by bsaiken** [FWAJL/FieldWorkAssistantMVC#623]
@damirius 

I was working with the website and I found an item that has not been corrected.
I added a new Project.  This Project was given coordinates in Austin, Texas.
The map/allProjects and map/currentProject URLs worked fine.
However, when I added new Locations, ones without coordinates, the URL map/currentProjectLocations should zoom to the coordinates of the Project coordinates.  However, this is not happening.

I created this scenario for you under your login name (mapping).  

This is under the Project "Demo Project".  Project > List All >> Select
This Project has two Locations, neither of which have coordinates.  Location > List All

If you click Map > All Project's Locations, the center of the map is not Austin.  The Project coordinates should be the map center.  Then, when I want to use the sidebar to place the Locations on the map, I am in the vicinity.

**Comment by damirius** [comment]
@bsaiken

Commit pushed to feature_mapping branch

**Comment by bsaiken** [comment]
@damirius 
The same fix should apply to the /map/taskLocations URL.  The default map center, whether you are mapping Project or Task Locations, should be the Facility coordinates.  After Milestone E is complete, every Facility should have coordinates, but if it does not (say the user deletes them), then the default is the center of the USA.

**Comment by damirius** [comment]
@bsaiken

done

**Comment by bsaiken** [comment]
@damirius @FWAJL 
Yes, Thank you.

**Comment by bsaiken** [comment]
@damirius 
I have found another bug.

When I navigate to the URL /map/taskLocations, the map is showing Task and Project Locations.  The map is supposed to show only Task Locations.

Also, I am preparing a map legend, and there is something wrong with the image "measle_blue.png".  It does not line up with the other icons.  I think this may have to do with the naming convention.  Other images use a dash and _maps (e.g. purple-stars_maps.png).  I was having trouble getting the src url to work with this icon.

**Comment by damirius** [comment]
@bsaiken

In SoW for Milestone A part 3 it was stated in notes that all project locations should be displayed.
"Task mode shows all Project locations, but the Task Locations have a different marker."

It was weird for me to use that marker for inactive locations since it's totally different from others. Anyway it isn't lining up because it is 7x7px while others are 32x32. I'll edit it to be 32x32 like others.
I have another commit for some changes for highlighting markers and some other stuff so I'll add it there. Just want to see what we gonna do about that Task map.

**Comment by bsaiken** [comment]
@damirius 
You are right - I did ask for Task and Project markers on the Task map.  Now that I am using it, i can see the folly in that.   I did go back to look at the scope and I missed that - funny, since I wrote it. 

Let's stick to the scope so we can finish the job.  I knew I would want some changes once I had the map and start using it, so we can deal with all changes later.

**Comment by FWAJL** [comment]
@damirius @bsaiken 

Ready for release.
