### ISSUE TITLE
Discussion Thread UI

### ISSUE THREAD

**Issue by bsaiken** [FWAJL/FieldWorkAssistantMVC#646]
Prerequisites: 

1. #404

Questions:

1. ***[ANSWERED]*** We need to discuss document handling methodology: Locations photos are stored in /Locations/[location_id]-[file_name].[ext]
  - How will you differentiate Location forms, when we start using forms, by the [ext], e.g. pdf?

Tasks (one issue per task please):

1. Implement the current discussion
2. Add "message" table

**Comment by FWAJL** [comment]
@bsaiken 

1. A location has a unique ID so you will have:
~/location/1_guid1.jpg
~/location/1_guid2.jpg
~/location/1_guid3.pdf
~/location/1_guid4.png
~/location/1_guid5.pdf

Each file is unique thanks to the GUID and you can find all files by document_content_type (which is similar to the extension).
