### ISSUE TITLE
When a Task is deleted, it remains the current Task.  Current task session variable must be cleared.

### ISSUE THREAD

**Issue by bsaiken** [FWAJL/FieldWorkAssistantMVC#666]

**Comment by damirius** [comment]
@bsaiken @FWAJL 

Current task should be unset if deleted task is the current task, that happens anyways since deleting task requires editing the task and editing the task makes that task the current one. Is there any other way to delete the task so I can add the check there too?

**Comment by bsaiken** [comment]
@damirius @FWAJL 
I do not have a link to delete an active task.  Only inactive tasks can be deleted.
Does that answer your question?
I checked the function, and it works.

**Comment by damirius** [comment]
@bsaiken @FWAJL 

Yea, we can't delete active tasks, just inactive ones. Just wanted to make sure.
