### ISSUE TITLE
Popup bugs

### ISSUE THREAD

**Issue by bsaiken** [FWAJL/FieldWorkAssistantMVC#689]
I am using the live site and noticing some popup bugs, so I just opened a new Issue.  I will list all bugs here as I notice them.

**Comment by bsaiken** [comment]
Bug: When I navigate to Locations > Add, and then click in the `Name:` field a popup automatically comes up.  This is incorrect.  The popup should not be called until after the user clicks the "Add" button.  Then the popup checks to see if it is a duplicate entry.

Bug: I am able to delete a Location.  There should be a confirmation popup box any time a "Delete" button is clicked.  It is not working for Locations, but I would check all "Delete" buttons.

**Comment by FWAJL** [comment]
@bsaiken 

If there are several bugs, the better solution to report them is to create a separate issue for each using the Milestone "Bugs".

That way we can identify better the bug.

Thank you.

**Comment by FWAJL** [comment]
@bsaiken @gsouvik 

For the current bugs reported above, we will keep them under this current issue. Any new bug will need a new issue.

Thank you.

**Comment by gsouvik** [comment]
@FWAJL 
Noted. Thanks.

@bsaiken 
1) the unique check feature for location add is removed from location_name to Add button.
2) The location delete confirmation box was not working. Fixed. Checked all other delete button confirmation boxes, found them to be working on branch 'feature_devsupport', as on this moment .
3) For analytes screen the alert and the redirect is removed. Instead the message is not displayed on the tooltip. Please review the message and confirm if it looks ok.

Thank you.

**Comment by bsaiken** [comment]
@FWAJL @gsouvik 
Items 2 & 3 are ready for code review.
I did not explain item 1 clearly, so I made a new Issue, #709.

**Comment by FWAJL** [comment]
@bsaiken @gsouvik 

Ready for release.
