### ISSUE TITLE
Location > Add Popup

### ISSUE THREAD

**Issue by bsaiken** [FWAJL/FieldWorkAssistantMVC#709]
Navigate to Locations > Add.  After clicking the Add Button, check to see if there is a Location name (not NULL) and if the Location name is unique.  If the Location Name is not unique, or is NULL, a popup prompt will appear with the text "You must enter a unique Location Name", and allow the user to enter a Location name.

**Comment by gsouvik** [comment]
@bsaiken 
Please review and let me know if the prompt box logic looks ok.
Thank you.

**Comment by bsaiken** [comment]
@gsouvik @FWAJL 
Yes, that's it.
Brian
