### ISSUE TITLE
Prepare Active Task views 

### ISSUE THREAD

**Issue by bsaiken** [FWAJL/FieldWorkAssistantMVC#724]
Part 1 of Issue #404 
The tabs have already been prepared.  
Task Status;
Map;
Forms;
Communications.

This Issue is just to create the Active Task structure - columns with headers and the breadcrumb.

**Comment by gsouvik** [comment]
@bsaiken 
When I right click a task and click the contextual menu 'Check Task Status' I see the Active task screens.
Do I have to create the UI / structure of the screens for each of those Tasks as a part of this issue? In other words just creating the dummy structure as shown in the slide #725, #726 etc?
Thank you.

**Comment by bsaiken** [comment]
@gsouvik 
I prepared the tabs so that It would make the mockups look better.

This Issue only has you putting the breadcrumb on the page, the bootstrap columns, and the column headers.  The Task Status tab column headers are "Task Progress" and "Instructions and Notes".

I originally prepared this milestone thinking it would be someone unfamiliar with our coding structure that would do it.  So, for you, this may be a trivial Issue.

**Comment by gsouvik** [comment]
@bsaiken Have understood now, thanks.

**Comment by gsouvik** [comment]
@bsaiken 
Basic structure of Active Task views prepared. The Tab is made dynamic in terms of selection. All view files organized in module files.

Thank you.

**Comment by bsaiken** [comment]
@gsouvik 
Please add a tooltip with glyphicon-info-sign to the left columns and glyphicon-question-sign to the right columns.  The content is not important at this time.

**Comment by gsouvik** [comment]
@bsaiken 
Tooltips with proper glyphicon sign added on all Active task related pages.
Thank you.

**Comment by bsaiken** [comment]
@gsouvik 
Souvik,
When you commit code for review, please remember to change the status to "function review" and make me the assignee - that way it is clear what needs to be done.

**Comment by bsaiken** [comment]
@gsouvik @FWAJL 
Great!

**Comment by gsouvik** [comment]
@bsaiken 
Actually I assigned you, but didn't change the status to "function_review" as it was already set as "ready for release". I was not sure if I should downgrade the status to "function_review" again, but shall do that from here on.

Thank you.

**Comment by bsaiken** [comment]
@gsouvik 
You are correct that you did assign me.  This Issue go messed up because you finished, I did a function review, then I added more work to this Issue, rather than create a new Issue.  Jeremie is trying to break me of this bad habit, with limited success, apparently.
It was just a reminder to make the correct label and assignment changes.
Great work!
