### ISSUE TITLE
Active Task - Task Status tab.

### ISSUE THREAD

**Issue by bsaiken** [FWAJL/FieldWorkAssistantMVC#725]
Part 2 of Issue #404.

Prepare Task Status tab contents.

![screen shot 2015-03-20 at 11 14 15 am](https://cloud.githubusercontent.com/assets/8228624/6757978/49185dc6-cef2-11e4-8b69-77ffc63e1b89.png)

The contents of the left hand column (Task Progress) are not editable, they include:
Task Deadline: [deadline]. [deadline] is stored here: task.task_deadline
Days remaining: [days remaining]. [days remaining] is calculated from the current date and the [deadline].
Percent Complete: [percent complete]. [percent complete] is a calculated value, but needs to be done at a later time.
Recurrence: [frequency]. This line appears only if task.task_trigger_cal=1. [frequency] is stored in task.task_trigger_cal.
Manual trigger: Yes. This line appears only if task.task_trigger_pm=1.
External Trigger: [specify]. This line appears only if task.task_trigger_ext=1 [specify] is stored in task.task_trigger_ext.
Textarea with [Instructions]. [Instructions] include the contents of task.task_instructions.

The contents of the right hand column (Notes) are editable. This includes a single textarea.
The contents of the textarea [notes] shall be dynamically recorded in a table task_note where the columns will be task_note_id, task_id, task_note_category_type (project_manager_id) and task_note_category_value (id value of the category type). You will need to request that this table be added to the database schema.

**Comment by gsouvik** [comment]
@bsaiken 
I have some questions on the textarea part.
1) How should be the content recorded dynamically? In the sense, the moment the user takes the focus off the textarea, do you wish to save the content to the database?
2) I understand the data would go in a new table "task_note", I'm not sure about the "task_note_category_value" field. Which data should this field contain? I mean do we have a table whose primary key should behave as a foreign key here.
3) Also once the above points are clear to me, should I create the table and upload the schema or ask @FWAJL for the same.
Please let me know, and i shall start with this task next.
Thank you.

**Comment by FWAJL** [comment]
@gsouvik 

2) `task_note_category_value ` is the pm_id value or the technician_id value.
3) I'm going to create the script for the new table.

**Comment by bsaiken** [comment]
@gsouvik 
Let's use two separate divs, like you did for the Communications tab. I liked that.  The top div has the header "Instructions", and is the contents of `task.task_instructions`.

The lower div has the header "Notes".  I should not have said "dynamically recorded" - sorry about that.  Nothing would get saved until the user clicks the "Save" button.  Insert a "Save" button in the center bootstrap column.  This is like almost all the other views.  I see you added an active_task_buttons module, so just add a "Save" button.  The user would not see the "Save" button until they click inside the "Notes" text area.  

We also need "Refresh" button.  It is always visible.  If a FT has saved a note it will not appear on the page until the PM refreshes the page.  Add a tooltip after the "Notes" header so I can instruct the user what the "Refresh" button is for.

While a Task is "Active", the Project Manager or one of the Field Technicians can add to the notes.  We want to be able to identify who added the note.  I got the idea from the eLance message interface.  Each message in eLance also identifies the sender.  After the "Save" button is clicked, the note is saved as well as the sender info.  Then, when it is displayed, the note would be displayed withe the PM of FT name.  Like this:

Brian: This is my note.
Souvik: Yes, I see your note.
Souvik: I also see that I have been identified as the person posting the note.
Brian: Excellent!

Since we have both PMs and FTs adding notes, the `task_note_category_type` identifies if it is a pm_id or technician id, so the only two possible values are `pm_id` or `technician_id`.  Then, the  numerical value saved to `task_note_category_value` is not ambiguous - it is either the pm_id or the technician_id.  Since you are working only on the PM interface, the `task_note_category_type` will always be `"pm_id"`.

You can create the table and the necessary scripts for you to develop on your local machine and for me to do a function review.  Save the table creation script to /Database/Scripts and give me the file name when you request the function review.  Only Jeremie can modify the Hurray Host database (live site).

**Comment by FWAJL** [comment]
@gsouvik 

Script created: https://github.com/FWM-Team/FWM-Backlog-Issues/issues/10#issuecomment-86643312

**Comment by gsouvik** [comment]
@bsaiken 
Thank you for the clearly chalked out details of the task, I understand it clearly now. Just one last question, where does the history of the "Notes" and "Instructions" shown, is it on this same page or we just need to record it here; the history would be displayed elsewhere.

@FWAJL Thank you for the table and the DAO.

**Comment by bsaiken** [comment]
@gsouvik 
Instructions does not have a history.
There are new notes, and notes history, so maybe we need three divs?

**Comment by gsouvik** [comment]
@bsaiken 
Ok

**Comment by gsouvik** [comment]
@bsaiken 
I've completed the coding for this issue. The development contains the following functionality:
1) The page loads and populates the left hand section from the Session, the right hand data (notes history) is fetched and rendered using Ajax.
2) Entering data into the Notes textarea makes the Save button visible. Clicking the Save button would save the note.
3) Clicking on Refresh button would fetch all the notes again for this task and render.
Please review and let me know your feedback.
Thanks.

**Comment by bsaiken** [comment]
@FWAJL @gsouvik 
This works great.  I even checked it with a note Technician note I added directly tot he database.
Thanks

**Comment by bsaiken** [comment]
@gsouvik @FWAJL 
Souvik,
Since the site is becoming more complex, function review and unit testing is also becoming more complex.  Therefore we are asking you to do one additional step when submitting code for a function review.  
Add the function test requirements to this file:  
https://docs.google.com/spreadsheets/d/19pvUh4dv2spQyTybsQHOSReDNdapnNrVkDBoDgLpyZE/edit#gid=2044822335
You will want to save this link for future work.
I have already added the line for this Issue.  See the `Active Task UI` tab, `Test 1`.
The reason I am asking you to do this is that the function review may more in-depth testing than just just a single line item.  You can add any additional lines, as necessary.  In each case, reference the github Issue in the comment column.  In some cases, you can just make a comment for an existing unit test item.  For example, to properly test this Issue, Task Status, it would be helpful for me to also "test" `Task UI`, `Test 6`.  This way, I can make sure the information displayed on the `/task/showForm`, `Task Info` tab (when the Task is inactive) displays correctly on the `/activetask/showForm`, `Task Status` tab.
Please let me know if you have questions - we will be adding this to our Wiki so we wan the Wiki instructions to be clear.

**Comment by gsouvik** [comment]
@bsaiken Thanks for sharing the document. I might have some questions regarding it and the processes involved. Shall ask those very shortly and start using it.
Thanks

**Comment by bsaiken** [comment]
@gsouvik 
I gave you the wrong link.  You do not have edit privileges yet.
Try this.
https://docs.google.com/spreadsheets/d/1lNhCFAW1PXiS6QDUDzWfAAbJG5VTZr-jQchaeWhRgXk/edit?usp=sharing_eid
