### ISSUE TITLE
Active Task - Map tab

### ISSUE THREAD

**Issue by bsaiken** [FWAJL/FieldWorkAssistantMVC#726]
Part 3 of Issue #404.

Prepare Task Map tab contents.

![screen shot 2015-03-20 at 11 16 45 am](https://cloud.githubusercontent.com/assets/8228624/6758048/a2ed29c6-cef2-11e4-988d-2e912b8bcafb.png)

The map will be similar to the taskLocations map, except that the markers will change color depending on their status. Status can be “in process” or “finished”. Status handling will be implemented at a later time, after the Field Technician module is created. For this Issue, simply include a view that loads the taskLocations module.

**Comment by gsouvik** [comment]
@bsaiken @FWAJL 
While I wait for @mehedee1 to provide me with a link (and a bit of code) where I may review how fancyapp is used to open PDFs (for #727), should I start with this issue?

**Comment by bsaiken** [comment]
@gsouvik 
Please do.  If you get stuck, proceed on any assigned to you that are `ready to start`.

**Comment by bsaiken** [comment]
@gsouvik 
Souvik,
This is also a high priority item.  Where are we on this Issue?

**Comment by gsouvik** [comment]
@bsaiken 
As per your very first comment on this issue, I've just reused the modules from `/map/taskLocations` and simply used a view which loads them to show the map. I'm unaware of the requirements for map related tasks so could not test any functional details.

Please review and let me know about any changes and I shall make those. Thanks.

**Comment by bsaiken** [comment]
@FWAJL @gsouvik 
This may be a bug...but it may be related to this Issue.  Please handle this accordingly.

When I now choose `Map > Task Locations`, and the Task has not yet been selected, I get a Prompt box asking me to select a Task.  The problem is, the list shown in the Prompt box is only Active Tasks.  This must be the complete list of Tasks (Active and Inactive) that are related to the current Project.

**Comment by gsouvik** [comment]
@bsaiken @FWAJL 
When I developed that prompt box I used the already created action `task/getlist` to get the list of tasks for a project. That action is not changed while working on this issue. So this must be due to some problem with that action, we need to correct how it fetches and stores tasks for a project in order to fix it.

**Comment by bsaiken** [comment]
@gsouvik 
This was Issue #593, and this particular feature was done on March 9, in case you are curious.  
I think what happened was, at the time we did not have the Active Task UI started yet.  
Anyway, it's not really that important.  The corresponding list for `Map > Task Locations` should be all Tasks (active and inactive) for the current Project.  I will make a new Issue and assign it to you, Souvik.  :-)
