### ISSUE TITLE
Add alphabetization for Locations lists

### ISSUE THREAD

**Issue by bsaiken** [FWAJL/FieldWorkAssistantMVC#729]
Location lists sort should apply everywhere, including map sidebar.

**Comment by damirius** [comment]
@bsaiken

I've added sort for locations, on `location/listAll`, `task/locations` and on maps. Few notes about maps sort, for first map with all facilities shown, we are pulling projects but showing facility names, so I had to sort them in my MapHelper function, in any case they should be sorted in the sidebar by name.
For Task Location map, I know that we want to implement some changes there, but in any case task locations and non-task locations are separated, so I am showing task locations sorted by name first (red markers), then after them I'm showing other locations that aren't linked to the current task.

**Comment by bsaiken** [comment]
@damirius @FWAJL 
Excellent - thanks!

**Comment by bsaiken** [comment]
@damirius @FWAJL 
Damir,
Since the site is becoming more complex, function review and unit testing is also becoming more complex.  Therefore we are asking you to do one additional step when submitting code for a function review.  
Add the function review requirements to this file:  
https://docs.google.com/spreadsheets/d/19pvUh4dv2spQyTybsQHOSReDNdapnNrVkDBoDgLpyZE/edit#gid=2044822335
You will want to save this link for future work.
I have already added a line for this Issue.  See the `Location UI` tab, `Test 14`.
The reason I am asking you to do this is that the function review may require more in-depth testing than just just a single line item.  You can add any additional lines, as necessary.  In each case, reference the github Issue in the comment column.  In some cases, you can just make a comment for an existing unit test item.  For example, to properly test this Issue, `Add alphabetization for Locations lists`, it is also necessary to review `Map UI`, `Test 19`.  You can also add a comment to any of the existing units test line items.  
Please let me know if you have questions - we will be adding this to our Wiki, and we want the Wiki instructions to be clear.
