### ISSUE TITLE
Add alphabetization for Projects lists

### ISSUE THREAD

**Issue by bsaiken** [FWAJL/FieldWorkAssistantMVC#730]

**Comment by damirius** [comment]
@bsaiken @FWAJL 

Added sorting for projects by name. I tried adding new line for testing in that test google doc, but it seems I don't have necessary rights for editing the file.

**Comment by bsaiken** [comment]
@damirius @FWAJL 
I gave you the view only link.  Sorry about that.  Try this:
https://docs.google.com/spreadsheets/d/1lNhCFAW1PXiS6QDUDzWfAAbJG5VTZr-jQchaeWhRgXk/edit?usp=sharing_eid
Sorting looks good.

**Comment by bsaiken** [comment]
@damirius @FWAJL 
I had given you the wrong link for the unit testing file.  
There are two unit test files, one is for the function review.  It has the file name `LOCAL_unit testing`.  This is the file I want you to modify.

https://docs.google.com/spreadsheets/d/1lNhCFAW1PXiS6QDUDzWfAAbJG5VTZr-jQchaeWhRgXk/edit?usp=sharing_eid

The other file is for unit testing of the server.  Don't modify that one.  Right now, they are the same because I am just setting this all up.  But they will diverge this week.
