### ISSUE TITLE
Add alphabetization for Tasks lists

### ISSUE THREAD

**Issue by bsaiken** [FWAJL/FieldWorkAssistantMVC#731]

**Comment by damirius** [comment]
@bsaiken @FWAJL 

Added sorting by name for tasks.

**Comment by bsaiken** [comment]
@damirius @FWAJL 
These do not appear to be sorting...
![screen shot 2015-04-08 at 2 03 56 pm](https://cloud.githubusercontent.com/assets/8228624/7055438/2caafac6-ddf8-11e4-99d5-4fb4dbff6993.png)

**Comment by bsaiken** [comment]
@damirius @FWAJL 
Sorry - my bad - I did not see I clicked the link to the Bluehost site.
