### ISSUE TITLE
Add alphabetization for Analytes lists

### ISSUE THREAD

**Issue by bsaiken** [FWAJL/FieldWorkAssistantMVC#732]

**Comment by damirius** [comment]
@bsaiken @FWAJL 

Added sorting by name for analytes list and task analytes list.

**Comment by bsaiken** [comment]
@damirius @FWAJL 
It seems these are not sorted?

![screen shot 2015-04-08 at 1 58 16 pm](https://cloud.githubusercontent.com/assets/8228624/7055310/6c42ae46-ddf7-11e4-913f-36e7ffa1d5a9.png)

![screen shot 2015-04-08 at 1 58 04 pm](https://cloud.githubusercontent.com/assets/8228624/7055311/6c472f2a-ddf7-11e4-96d1-cd99926a85c2.png)
