### ISSUE TITLE
Add alphabetization for Forms lists

### ISSUE THREAD

**Issue by bsaiken** [FWAJL/FieldWorkAssistantMVC#733]
The categories are *not* alphabetized.

**Comment by damirius** [comment]
@bsaiken @FWAJL 

Sorting for form list and task form list.

**Comment by bsaiken** [comment]
@damirius @FWAJL 

It seems as though these are not sorted...

![screen shot 2015-04-08 at 1 55 50 pm](https://cloud.githubusercontent.com/assets/8228624/7055256/00c3bba6-ddf7-11e4-8481-9a3f82b48da1.png)
