### ISSUE TITLE
Update user table to store session id

### ISSUE THREAD

**Issue by FWAJL** [FWAJL/FieldWorkAssistantMVC#745]
Change the column `user_is_logged` to `user_session_id` where the value is hashed for security reasons.

**Comment by damirius** [comment]
@FWAJL

I must change this as the part of Issue #421, since I need to populate our new `user` table with data from `project_manager` table. Do you want to expand this Issue to cover that `user_session_id` checks and that session clearing script we talked about before?

**Comment by FWAJL** [comment]
@damirius @bsaiken 

To answer Damir about the following:

> Do you want to expand this Issue to cover that user_session_id checks and that session clearing script we talked about before?

Let's treat this when needed, e.g. when we will need to worry about security and preventing multiple login of the same user --> issue #758

**Comment by bsaiken** [comment]
@FWAJL @damirius 
I stated this is Issue #250, and now in Issue #758:
I do NOT want to prevent multiple log-in of the same user.
