### ISSUE TITLE
Issue 421 - Step 4 - Build the PM list UI

### ISSUE THREAD

**Issue by FWAJL** [FWAJL/FieldWorkAssistantMVC#746]
From #421 :

Admin user shall be able to:

PM > List All
> Add
Can add, edit, delete PMs.
Link to email PMs

Project > List All

Can Edit (view) and Delete Projects

Technicians > List All
Can edit and Delete Technicians.
Can set/unset current PM to limit Technician List.
Breadcrumb to display Current PM

Locations > List All
Can edit and delete Locations.
Can set/unset current PM and current Project to limit Location List.
Breadcrumb to display Current PM, current Project

Map > All Projects
Map > All Locations
Can set/unset current PM and current Project to limit Project and Location Lists.
Breadcrumb to display Current PM, current Project

Tasks > List All
Can edit and delete Tasks.
Can set/unset current PM and current Project to limit Task List.
Breadcrumb to display Current PM, current Project

Analytes > Upload Common
Can Add, Edit and Delete common Analytes.
Can set/unset current PM to limit Technician List.
Breadcrumb to display Current PM

Analytes > Upload Common
Can Add, Edit and Delete common Analytes.

Field Forms > Upload
Can Add, Edit and Delete standard form templates.

Service Providers
Can Add, Edit and Delete recommended Service Providers. Note - there is no table or interface for this yet. Just being thorough.

Completed Tasks
Can view, edit delete all completed tasks.
Can set/unset current PM and current Project to limit Completed Task List.
Can package and completed forms and other Task info for delivery (email?) to PM.

**Comment by damirius** [comment]
@bsaiken @FWAJL 

See #811

**Comment by bsaiken** [comment]
@damirius 
So, this Issue can be closed, yes?

**Comment by damirius** [comment]
@bsaiken

We can leave this one open if you wish since we will need to update user list page for admins with new roles. Or we can use other issues for that, however you wish.
Thanks

**Comment by bsaiken** [comment]
@FWAJL 
I am closing this - I would rather create new Issues.
