### ISSUE TITLE
Bug with valid address check

### ISSUE THREAD

**Issue by bsaiken** [FWAJL/FieldWorkAssistantMVC#751]
Popup Alert box checking for correct popups up before Project name Prompt box.  The Popup alert box should not fire, because the address must be valid, or at least, we have coordinates since we are copying an existing Project.

**Comment by damirius** [comment]
@bsaiken @FWAJL 

This should be fixed now. Only "new project name" prompt will open up instead of every prompt we have on the page. Existing address and coordinates will be used for the new project(facility).

**Comment by bsaiken** [comment]
@FWAJL @damirius 
WORKS.  I even tested with a single quote in the Project name.  No issues.

**Comment by bsaiken** [comment]
@FWAJL 
This did not work.  I think it is related to the requirement to have the client email address.  The client email address requirement must be removed.

**Comment by bsaiken** [comment]
@WebDevJL 
This still has a bug.
![screen shot 2015-05-06 at 7 17 32 am](https://cloud.githubusercontent.com/assets/8228624/7495006/08dad4e4-f3c0-11e4-81eb-0cc06e664f14.png)

**Comment by WebDevJL** [comment]
@bsaiken 

Please prepare the test case. Is it related to client address still?

**Comment by WebDevJL** [comment]
@bsaiken 

Disregard my last comment. The attachment took long to load. Sorry. 

Let's discuss it during our talk.

**Comment by FWAJL** [comment]
@bsaiken 

You indadvertedly deleted data you shouldn't have... All the clients we add for each project have been deleted. However, we have no mechanism to add a client to an existing project. In fact, only when creating a project that a client is added too. To add a client when not existing for an existing project (same for the facility), we need new functionality.
Or we can add the clients back, thank you my backups.

What do you want to do?

**Comment by FWAJL** [comment]
@bsaiken 

If you want to add the data back, here is the last backup data that had clients:

```
INSERT INTO `client` VALUES 
(1,1,'Comp','','','',''),(2,2,'Field Work Manager','Austin, TX','Brian Aiken','','baiken@fieldworkmanager.com'),
(4,4,'Storm Water Helper','Austin, TX\nCountry','Brian Aiken','','baiken@fieldworkmanager.com'),
(9,9,'Field Work Manager','Austin, TX','BSA','',''),
(33,33,'Field Work Manager','Prescott Valley, AZ','Brian Aiken','','baiken@fieldworkmanager.com'),
(41,41,'Client 870','870 Av of There\nCity\nCountry','','800064358',''),
(42,42,'Field Work Manager','Austin, TX','Brian Aiken','','baiken@fieldworkmanager.com'),
(112,125,'Client 583','583 Av of There\nCity\nCountry','','714380018',''),
(117,130,'Client 875','875 Av of There\nCity\nCountry','','50198322',''),
(124,137,'Client 97a','97 Av of There\nCity\nCountry','a','331075364a','a'),
(127,140,'Client 494','494 Av of There\nCity\nCountry','John Halloran','312863482','john.devtechnosys'),
(128,141,'Client 831','831 Av of There\nCity\nCountry','Nr. Mane','918644496',''),
(136,149,'Field Work Manager','','Brian Aiken','5123004278',''),(137,150,'Client 51','51 Somewhere','','549166566',''),
(138,151,'Client 125','125 Somewhere','','978483322','A@b.net'),
(139,152,'Client 84','84 Somewhere','','446017336','client@client.com');

```

**Comment by bsaiken** [comment]
@FWAJL 
That was not inadvertent.  We are now creating client users when we add a new Project.  
It's a good point, though.  I will go back and delete the Projects and Facilities as well.
I want all the Projects to have Client users.  I'll work on purging the database this weekend.  The only thing I won't get rid of is the existing users, so everyone an still log in.

**Comment by WebDevJL** [comment]
@bsaiken 

We have built functions to delete projects and the rest from the website. Please use that instead of using the database access of hurray host. 

What you did create data inconsistencies and bug that don't happen because a client is deleted when the project is from the site. 

Let me know if you understand. 

The users can't be deleted from the database using the website. Only via hurray host you can do it.

**Comment by bsaiken** [comment]
@FWAJL 

I was testing a theory (I supposed I could have asked): if I delete the client user info, then go into Project edit mode and add Client info, would a user then get created?  I see that is not how it works.  Client user creation is a one-time thing.

Your deletion routines don't cover all the situations we now have.  For example: if I go into the admin UI I have the ability to delete a Client user.  Does that also delete the Project?  Nope.  How then would that Client user get added back into the system?  We can't do that right now.

I think we have created a lot of potential inconsistencies we will need to clean up.
Maybe it's too early, but purging the database is going to be a good idea in the near future.



So - it's a bit complicated.

**Comment by FWAJL** [comment]
@bsaiken 

The reset script in Database/Scripts is the database purge solution which removes all the data and add only the necessary admin and pm to start using the site.

Just catalog these requirements in your features to build someday in that new document you made.

**Comment by bsaiken** [comment]
@FWAJL 
Can we set up the reset so that it does not purge users?

**Comment by FWAJL** [comment]
@bsaiken

Yes, we can include all the users into the reset script.

--
Jérémie Litzler

**Comment by bsaiken** [comment]
@FWAJL 
Super.  Let me know when it is ready and I will do a reset and re-enter only the Project data I want.

**Comment by FWAJL** [comment]
@bsaiken 

Here it is: https://github.com/FWAJL/FieldWorkAssistantMVC/blob/36b21df0f1c76bcbdea1d84a4543e23a4f6c5f91/Database/Scripts/baiken_fwm_1_db_reset.sql

Thank you.
