### ISSUE TITLE
Delete technician photo when the Technician is deleted.

### ISSUE THREAD

**Issue by bsaiken** [FWAJL/FieldWorkAssistantMVC#761]
@damirius 
Since you just fixed the photo upload function, it makes sense to do this now.

**Comment by damirius** [comment]
@bsaiken @FWAJL 

I've added new file controller method which can remove multiple photos.
Go to Locations->List All, choose some location.
Add some pictures or use location with existing pictures. Delete location, images should be removed from document table and from location directory.

**Comment by damirius** [comment]
@bsaiken @FWAJL 

There is a new commit for technician photo removal now too. Since I pushed last one on this issue too by mistake since they are essentially the same issues. Sorry about that.
