### ISSUE TITLE
Enable Task Info checkboxes to display the correct Task Tabs

### ISSUE THREAD

**Issue by bsaiken** [FWAJL/FieldWorkAssistantMVC#763]
Details to follow...

**Comment by bsaiken** [comment]
@gsouvik 
This Issue is related to #556 and #557, and helps explain more comprehensively what behaviors I want.  I want some of the tabs on the Task UI (/task/showForm) to appear only when they are needed.
The only tabs that appear all the time are `Task Info` `Technicians` and `Locations`.

I had written the JQuery in tabs.js, line 47, but this will need to be modified (replaced, more likely) now that we have refined the required behaviors.

![screen shot 2015-04-08 at 3 01 00 pm](https://cloud.githubusercontent.com/assets/8228624/7056425/58aa7d74-de00-11e4-9c52-7d07c7d08369.png)

The tab `Services` should appear only when the checkbox `service_providers_box` is checked.
The tab `Forms` should appear only when the checkbox `insp_note_box` is checked.
The tab `Field Analytes` should appear only when the checkbox `field_data_box` is checked.
The tabs `Lab Analytes` and `Chain of Custody` should appear only when the checkbox `lab_sample_box` is checked.

The tabs `Field Matrix` and `Lab Matrix` are a bit more complicated. 
The tab `Field Matrix` shall appear only when the checkbox `field_data_box` is checked.
However, as we discussed in #556, this tab doesn't display properly unless we have at least one Location and one Field Analyte.  
 
Same for Lab analytes of course.

I hope that helps tie everything together.

**Comment by gsouvik** [comment]
@bsaiken 
The task tabs now remains visible or hidden based on the checkboxes as described in your your last message. Please note that on the `task/showForm?mode=edit` screen you have to SAVE the form after changing the checkboxes in order to make the tabs work throughout all the screens.

The analyte matrix tabs are further dependent on if location/analyte is associated with this task. Even if analyte/location is associated but the relevant checkbox is unchecked on the main edit form, the matrix tab doesn't show.

Please review and let me know if the behavior of the tabs is as you expected.

Thank you.

**Comment by bsaiken** [comment]
@gsouvik 
I do not want to click SAVE every time there is a change to the checkboxes.  Can't you reload the page each time a checkbox is selected?  
If the problem is the dependent behavior of the matrix tabs, then we can remove the dependent matrix tab behavior and show an "empty" matrix if locations or analytes are missing.

**Comment by gsouvik** [comment]
@bsaiken 
Yes I can reload it every time the checkboxes are toggled. It is not the matrix tabs. As the other tabs are altogether different pages, there is no way to track the checkbox status on the edit page on those pages, unless the edit page is saved. Reloading the edit page whenever the checkboxes are toggled would solve that problem.

**Comment by bsaiken** [comment]
@gsouvik 
Great.  Let's reload the page.

**Comment by gsouvik** [comment]
@bsaiken 
The edit page now reloads whenever the checkboxes are toggled. Please review and let me know.
Thank you.
