### ISSUE TITLE
When editing an analyte, add a prompt box if not unique and ask for unique name.

### ISSUE THREAD

**Issue by bsaiken** [FWAJL/FieldWorkAssistantMVC#767]

**Comment by gsouvik** [comment]
@bsaiken 
Lab and Field analyte Edit now has 'unique check' functionality. When editing, the system checks if the name is not unique and alerts the same.

**Comment by bsaiken** [comment]
@gsouvik 
I get a toastr message, but no popup.  Where exactly is this implemented?

**Comment by gsouvik** [comment]
@bsaiken 
Taking the example of lab analytes on my local, here is how the screen looks
![screen shot 2015-05-30 at 1 46 04 am](https://cloud.githubusercontent.com/assets/2292482/7891874/b2cb65ee-066d-11e5-8dfb-879afd7e76ea.png)

Let me try and Edit "Lab 8"
![screen shot 2015-05-30 at 1 46 56 am](https://cloud.githubusercontent.com/assets/2292482/7891893/d4980006-066d-11e5-8b25-85cbb93592f1.png)

Let me try and set the name to "Lab 5" and click OK
![screen shot 2015-05-30 at 1 48 19 am](https://cloud.githubusercontent.com/assets/2292482/7891909/f9e20f28-066d-11e5-8e52-d44511361a93.png)

Popup alert shows and alerts me that the name is not unique
![screen shot 2015-05-30 at 1 48 41 am](https://cloud.githubusercontent.com/assets/2292482/7891918/1adb4a50-066e-11e5-8943-6705b3965a7d.png)

I change it to "Lab 8 e"
![screen shot 2015-05-30 at 1 49 59 am](https://cloud.githubusercontent.com/assets/2292482/7891927/343039c0-066e-11e5-83d7-6225e0549860.png)

It edits the name and reloads with the change
![screen shot 2015-05-30 at 1 50 33 am](https://cloud.githubusercontent.com/assets/2292482/7891939/4ac18a5e-066e-11e5-85ec-2aae75068a12.png)

All the code is pushed to "feature_devsupport" branch.

**Comment by bsaiken** [comment]
@gsouvik @FWAJL 
 I see.  I was testing the function when trying to add a new analyte.  This is set up to edit analytes.
