### ISSUE TITLE
Enable viewing of PDF template forms

### ISSUE THREAD

**Issue by bsaiken** [FWAJL/FieldWorkAssistantMVC#777]
@mehedee1 @FWAJL 

Normally, we have developers work on a feature branch with github.  However, yours is a unique and special case.  For the time being, I will have you put your edits directly on Bluehost.  Let me know if you need anything (e.g. Bluehost ftp account/password) to set that up. 

All your Issues, which I will prepare this weekend, will be under the Milestone "PDF Form Integration".

I have set up a sample Task on the http://dev.fieldworkassistant.net site.  To view the site, log in with
username = test
password = test
Navigate to the Task by clicking Task > List All, right click on `PDF Task` and click edit, then click the `Forms` tab.
You will see the form "Well Purge".  

Right click to see the contextual menu with the option to "View" the form.  

Clicking on "View" shall open the form.  We are using lightbox to view photos, so if you can use lightbox, that would be preferred.

You will need to modify task_form.js to add the contextual menu.  Most controllers have contextual menus, so you should be able to easily find the js code snippet for a contextual menu.
If you are able to use lightbox to display the pdf, a good controller file to find code snippets (if appropriate) would be technician_manager.js.

Let me know if you need any assistance with this Issue.

**Comment by bsaiken** [comment]
@mehedee1 
In case you saw the last message, I added the contextual menu as this was quite easy.

**Comment by bsaiken** [comment]
@mehedee1 @FWAJL @damirius 

Mehedee - I realized that the three forms in the table `master_form` had not been uploaded.  So, I uploaded these three forms into the directory /uploads/master_form.  We are delayed getting the interface to upload master (template) pdf files.

Damir and Jeremie - I uploaded these three forms onto Hurray Host so that the two sites would be consistent.  We are using Dropzone to upload the pdf files - can we use this to also make the files viewable?

**Comment by FWAJL** [comment]
@bsaiken @damirius @mehedee1 

Brian, you need to create an issue to develop this. Only user form are being uploaded. I think the viewing mode is also to be developed.
@damirius : can you confirm?

Thank you.

**Comment by bsaiken** [comment]
@FWAJL 
This Issue, #777, is to view pdf files.  Uploading pdf master files is Issue #421.
Since #421 is not finished, I manually uploaded the files.

**Comment by bsaiken** [comment]
@damirius 
Can we use Dropzone or lightbox to view pdf files?

**Comment by mehedee1** [comment]
Sorry for delay reply. I will see. If need any help I will ask.

**Comment by bsaiken** [comment]
@mehedee1 
How is progress going?  I did some checking and this plugin might work for our purposes.  This would display the pfd form for the Project Managers.  It works on mobile devices, but I don't know if that means you could fill in and save a fillable pdf form.  But, for this Issue, it would work.
http://davidpaulhamilton.net/orangebox/

**Comment by mehedee1** [comment]
Pdf file can be seen in lightbox but you cannot work for interaction, just view.

**Comment by mehedee1** [comment]
I have created a tested action outside your framwork. Now you can view and get action in the lightbox. 

http://fieldworkassistant.net/m_test/viewpdf.php

If this one is OK, I will work on contextual menus if need.

**Comment by bsaiken** [comment]
@mehedee1 @FWAJL 
I am not able to see the pdf file in Firefox, but I asked Jeremie, and he can see the pdf in Firefox.  
We both tested Chrome and Safari and both work.
This is acceptable for allowing Project Managers to view the pdf file.
Please do go ahead and incorporate the link with the contextual menu.

**Comment by mehedee1** [comment]
I have set up facny box to view pdf form in contextual menu. It is static.

But I am not clear how I can it dynamic. That means how I can get WellPurge name and open corresponded file. If you would explain it would be better for me.

**Comment by mehedee1** [comment]
If you can show me relation between form name on web and pdf name, I could figure out.

**Comment by bsaiken** [comment]
I'm not sure I understand your question. 

I am away from my computer and can look at this tomorrow. Can you explain again your question?

**Comment by mehedee1** [comment]
Please see the comments http://screencast.com/t/PEJOgrE9WQ

**Comment by bsaiken** [comment]
@mehedee1 
I understand the problem now.  
First of all, the link to view the pdf file is great.  that's just what I want.
Please add a contextual menu to the forms listed at `/form/listAll`.

Now, as for making the link dynamic.  I see that we are a little behind where we need to be for this.  We have manually placed the document in the database, but we did not upload them so that we have fully populated all the database tables - making it possible to find the files.  

I might able to manually fill in the tables, but if not I will make sure it the first priority next week.  I will let you know either way.

Brian

**Comment by bsaiken** [comment]
@mehedee1 
I might have the answer to your question.
The database table `master_form` should give you the information you need to make the link dynamic.
Here is a screen shot of the source code for the page:

![screen shot 2015-04-03 at 7 47 52 pm](https://cloud.githubusercontent.com/assets/8228624/6991193/c25f3ec2-da3a-11e4-8be6-c68039a24292.png)

If you look at the table `master_form` where `form_id=2`, you will see the following corresponding entries:
`content_type` = pdf
`value` = FWM_L-WellPurge.pdf
`title` = Well Purge
`category` = NULL

The corresponding items in the source code are:
`data-taskform-id="2"` - This is the corresponding attribute for `form_id`.
`data-object="master_form"` - This is where the form is locationed, in this case, the form is in the directory "/web/uploads/`master_form`". - Note that the database table name is the same as the attribute name.
The li text is "Well Purge" - This came from the `title`.

**Comment by mehedee1** [comment]
Cool!
Now all dynamic. /form/listAll and /task/forms

**Comment by bsaiken** [comment]
@mehedee1 
Excellent.
I noticed your contextual menus have "View" and "Delete".  Please remove the "Delete" from the contextual menu.

**Comment by mehedee1** [comment]
Done

**Comment by bsaiken** [comment]
Please provide me a record of the code changes you made so I can have them incorporated into the main site.

**Comment by mehedee1** [comment]
OK, I am telling what I have done.
for pop up box
1. /Web/fancyapps
2. Added link in /Applications/PMTool/Templates/header.php

For contextual menu interacting with database
1. /Web/includes
2. task_form.js
3. form_manager.js

**Comment by bsaiken** [comment]
@mehedee1 
I saw that you commented your code.  That will work.  Please add a comment at the end of the inserted code so it is easier for me to find.

popup box 1.
Fancy box is a js library, so it belongs here: /Web/js/addons/fancyapps
popup box 2.
The js files do not belong in the header.  Only js files that are needed for every page go in the header.  You can insert the js files in /Applications/PMTool/Config/routes.xml.  Please add the files to the Form module, after line 643, and the TaskForm module after line 561.

interacting with database 1.
I understand we will have to leave this for now.

interacting with database 2.
Please either comment or give me the line numbers, for example:
task_form.js: added lines 8 - 25

interacting with database 3.
same as above

**Comment by bsaiken** [comment]
@mehedee1 
I notice that when I open the pdf files in chrome, I am able to type in the fillable fields.  I do NOT want Project Managers filling out forms.  Is there a way to display the pdf form so that the fields are not editable?

**Comment by mehedee1** [comment]
Before I provided you how we can easily make read-only. Just keep button on the pdf form. When need editable fields, after clicking on buton and type password you can get editable fields.
Did you see?

With php we may do but it needs additional library which is costly.

**Comment by mehedee1** [comment]
http://fieldworkassistant.net/m_test/FWM_L-WellPurge.pdf

On top right you will see lock/unlock button. Password: test

**Comment by bsaiken** [comment]
@mehedee1 
This is not what I had in mind, but it will work.  Can we add the button without the password?

**Comment by mehedee1** [comment]
Yes

**Comment by bsaiken** [comment]
OK - let's do that.

**Comment by mehedee1** [comment]
Done
