### ISSUE TITLE
Generate the Location-specific pdf forms and populate the Location field in the new forms.

### ISSUE THREAD

**Issue by bsaiken** [FWAJL/FieldWorkAssistantMVC#781]
Follow-on to #778.

**Comment by bsaiken** [comment]
@mehedee1 
I got your comment to Issue 778.  I appreciate you being candid about this.  You have already generated code that will create multiple copies of the template forms.  This task would add the location_name to the location field in each form.  This is a simple task, but I would get to see the pdftk utility in action.

**Comment by mehedee1** [comment]
Generally I use pdftk for inserting data into pdf form and then automatically new files will be generated. As you wanted to see copy of pdf form, I did with core php.

**Comment by bsaiken** [comment]
@mehedee1 
Yes, you can use your method to copy files.  I just want to see pdftk in action.

**Comment by bsaiken** [comment]
@mehedee1 
I see that the copies of the master files are being created.  But you have not inserted the location fields yet, have you?

**Comment by mehedee1** [comment]
I have added pdftk method in location_copy.php

Copied file does not follow guid_id as you wanted to do with fileupload methods. Just I have used what did before. I have not stored output file name in document. You can see pdftk code and then imply with your fileupload method.

I do not know whole data map between pdf form and database. So I have used just "Location 1" and Location 2 to show pdftk function. If I could proper data mapping I could insert all data into pdf form and then copy.

If any confused let me know.

**Comment by bsaiken** [comment]
@mehedee1 
I see that the copied form was populated with the Location field.  Now we need to copy the forms correctly so the selection of the forms can be dynamic.  We just completed the form copy feature on the main site, so give me a couple days to transfer the updated site to Bluehost.

**Comment by bsaiken** [comment]
Mehedee,

We now have the form copy function working on the Bluehost site.  Can you please look at it.  I have set up a sample task, `Populate`.  If you activate this Task, three forms will be created (one form for each Location).  The Locations are: `Avery`, `BSA`, `Curry`.  What I would like you to do is insert the code necessary to put the Location name on the three new forms that are created.

The dropdown menu function `view` is not working.  I would like to have this dropdown menu functional in all modes so I can look at the form.

**Comment by mehedee1** [comment]
I see the status on hold. Should I work as per previous requirements?

**Comment by bsaiken** [comment]
@mehedee1 
Sorry about that.  Charge ahead!

**Comment by mehedee1** [comment]
I have set up a sample task, Populate
>>>
I am not clear. Where is it?

The Locations are: Avery, BSA, Curry
>>>
These data will be inserted into pdf form? or file name will be with this name?

**Comment by bsaiken** [comment]
@mehedee1 
I'm not sure I understand this question.  I found this Task, "Populate", straight away.  
I made a copy of this Task, `Populate-demo` and activated it.  
Now I have three forms:
![screen shot 2015-05-10 at 8 35 58 am](https://cloud.githubusercontent.com/assets/8228624/7554956/f0141e38-f6ef-11e4-8f11-d4acd88da111.png)

The Locations are supposed to be inserted into `Well ID` on the each form:
![screen shot 2015-05-10 at 8 36 57 am](https://cloud.githubusercontent.com/assets/8228624/7554963/217bbd96-f6f0-11e4-9082-87dcf0b4af54.png)

This will always be the case.  There will always be on or more fields on the pdf form that corresponds to Location(s).  For now, we are doing forms that have only one Location.

**Comment by mehedee1** [comment]
I was logging with test. That is why I could not see. with pdf log in it is OK.

Now location name is inserted into pdf form. You can see. I am working on viewing pdf form in all mode.

**Comment by mehedee1** [comment]
now you can view pdf on two pages:
1. /task/forms
2./activetask/forms?task_id=70
If need such view option on any other pages, please specify.

**Comment by bsaiken** [comment]
@mehedee1 
I just ran a test and I am not able to view the pdf files.
Also, I downloaded and looked at the file that was created, and the Well ID field was not populated.
![screen shot 2015-05-11 at 9 36 56 am](https://cloud.githubusercontent.com/assets/8228624/7569986/76494254-f7c1-11e4-92e9-3947bbf475fb.png)

**Comment by mehedee1** [comment]
I am not sure we are on the same page. So I have created screen video for you.
http://screencast.com/t/oUhGWTXtsNUr

**Comment by bsaiken** [comment]
@mehedee1 
This is working for me now.  I saw from the video that you scrolled to Lab Analytes > Upload List before you viewed the pdf files.  When I did that, it started working.  Is this a required step in the process?  Because Lab Analytes have nothing to do with the form population.

**Comment by mehedee1** [comment]
On two places you can see pdf form.
1. /task/forms
task > list all > inactive task > edit > forms > now you can view master form

2./activetask/forms?task_id=70
task > list all > active task > check task status > forms > Forms used for this task > now you can view copied location pdf form.

If any where you want to view pdf form, please let me know. I will apply this function on that page.
If not clear please let me know.

**Comment by mehedee1** [comment]
What I have done:
1. I have changed script as new data table:  
Web/includes/location_copy.php
Web/js/other/interact_pdf.js

2. To view master pdf form
Web/includes/masterform_link.php
js/app/controller/task_form,js (view callback)

3. To view copied location form
Web/includes/active_task_form_link.php
js/app/controller/active_task.js (view callback)

**Comment by bsaiken** [comment]
@mehedee1 
I just tested this and I got the new forms, and I see they are populated, and I can view them.
However, I am seeing some "forms" that do not belong there, the `.jpg` files.  Where did they come from?
![screen shot 2015-05-12 at 1 15 27 pm](https://cloud.githubusercontent.com/assets/8228624/7597527/fad6a29a-f8a8-11e4-833c-af21bb994ad8.png)

**Comment by mehedee1** [comment]
I do not see on  Populate Demo 1. But remains on  Populate Demo 2.

My script just copy files files and open related pdf form. It will better to ask your lead developer why those here. I think some extra data updated in database. That is why those are here.

**Comment by bsaiken** [comment]
@mehedee1 
Why have you added a copy function?  The forms should already be being copied.

**Comment by mehedee1** [comment]
When I was developing view function, I need copied file name. I do not see copy function is working. 
Also during copy, location name is inserted into fields. That is why I updated.

**Comment by bsaiken** [comment]
@mehedee1 

That is odd.  I will look into it.  Please keep you work save and I will re-upload the site with the copy function already working.

**Comment by mehedee1** [comment]
OK, I have saved.
