### ISSUE TITLE
Generate a COC form with all required fields populated.

### ISSUE THREAD

**Issue by bsaiken** [FWAJL/FieldWorkAssistantMVC#785]
Prerequisites:
#556  #557

**Comment by bsaiken** [comment]
@mehedee1 
Let's skip directly ahead to this Issue.  I will add the COC form, and I want you to populate the relevant fields once the task is activated.
On the COC form, add the following fields:
Sample Name(s): Location Name(s)
Analytes: Lab Analytes
Project Name: `project.project_name`
Project Manager: `project_manager.pm_name`
Client Name: `client.client_contact_name`

There are other fields that can be populated, but this is a good start.

**Comment by mehedee1** [comment]
Ok I will do

**Comment by mehedee1** [comment]
I see status hold. Should I stop now?

**Comment by bsaiken** [comment]
@mehedee1 @FWAJL 
I just wanted #781 done first, that's all.
