### ISSUE TITLE
Change the name of the relation table `task_form` to `task_template_form`.

### ISSUE THREAD

**Issue by bsaiken** [FWAJL/FieldWorkAssistantMVC#787]
See recent comments to Issue #727.
The methods populating this table will also need to be updated.

**Comment by FWAJL** [comment]
@bsaiken 

I have renamed the table and renamed the Dao class. 

However I'm not sure to understand what you mean by "The methods populating this table will also need to be updated."
Can you please describe it more?

Thank you.

**Comment by bsaiken** [comment]
@FWAJL 
If you renamed the Dao that may do it.  Do any methods driectly reference the table?

I just did not want Mehedee attempting this because it was not as simple as a table name change.

**Comment by WebDevJL** [comment]
@bsaiken 

I have replaced all the old reference to `Task_form` class to use the new one in the application. Since I just changed the name of the table and its related Dao class, my commit is sufficient.

**Comment by bsaiken** [comment]
@FWAJL 
Great.  Thanks
