### ISSUE TITLE
Discussion Thread Milestone A - Setup

### ISSUE THREAD

**Issue by bsaiken** [FWAJL/FieldWorkAssistantMVC#802]
Welcome Nadir,

Here are some review guidelines.
Once you have submitted code, change the label to "Function Review" and set the assignee to "bsaiken".  Add a line item to this document:
https://docs.google.com/spreadsheets/d/19pvUh4dv2spQyTybsQHOSReDNdapnNrVkDBoDgLpyZE/edit?usp=sharing_eid
All your work is on the "Active Task UI" tab.  Include a new item number, a description of what I need to review, and the link to the github Issue.  The document (LOCAL_Unit testing) had a comprehensive list of all the site behaviors.  If your code may impact an existing behavior, add the github Issue link to that Item number as well.
If I have questions or Issues, I will notify you.  If the code passes the function review, I reset the label to "code review" and set the Assignee to FWAJL.  Jeremie checks to make sure the code is consistent with our coding methods.  After Jeremie approves the work, I will release payment as assign the next Issue.

**Comment by bsaiken** [comment]
@nadirhamid
Please let me know if you receive this message.

**Comment by nadirhamid** [comment]
Hi. I have reviewed and received I'll keep you posted and come back should I have questions

**Comment by bsaiken** [comment]
@nadirhamid @FWAJL 
I think Jeremie needs to add you as a contributor.  That should happen tomorrow.

**Comment by FWAJL** [comment]
@bsaiken @nadirhamid 

Added.

**Comment by bsaiken** [comment]
@FWAJL 
Oops, sorry about my Issue #4 comment....

**Comment by bsaiken** [comment]
@nadirhamid 
I think you are all set up and ready to start.  Please let me know if you have any questions.

**Comment by bsaiken** [comment]
@nadirhamid 
Nadir,
I have added user login credentials for you.
username: thread
password: thread
Please use those during development.  This way, if I need to add a test case of any kind, I can add it here and you can see it without having to sift through other people's projects.  I am adding a Project, Task, Technicians and Service Provider to the live site so you should be ready to go as "thread".

**Comment by nadirhamid** [comment]
Update:
I was able to login with thread/thread on live as well as set up the SQL, config locally

**Comment by FWAJL** [comment]
@nadirhamid @bsaiken 

Good! 

Don't forget to add the @mention with the persons you are talking to. @bsaiken only receives notifications when the mention is added.

Thank you.

**Comment by nadirhamid** [comment]
@bsaiken task should be marked as complete i've done the steps and
am on the post to technician issue

**Comment by bsaiken** [comment]
@nadirhamid @FWAJL 
Thanks.  I see that you changed the status to function review.  Also, make the assignee "bsaiken".  I do the function reviews.
There is really nothing to do for this Issue since it was just to familiarize you with our guidelines.
So you will see I removed function review and the assignee and changed the status of Issue #803.
that's all we wanted for this Issue.

**Comment by FWAJL** [comment]
@bsaiken 

Closing this then.
