### ISSUE TITLE
Disscussion Thread Milestone C(1) - Send message to Service Provider

### ISSUE THREAD

**Issue by bsaiken** [FWAJL/FieldWorkAssistantMVC#805]
This is similar to the requirements for Field Technicians.  However, messages with Service Providers will often need to include attachments.  We are using lightbox to handle document uploads.  Use the same methods we have already implemented, if possible.

The attachments will be sent as “links”: the user will:
click a button to select a document
select a document in a list in a prompt popup. Selection of a document will create a link to download this document by anyone with the link. This link will be added as part of the message (at the end)
click “Send Message”

Another case will be that the user wants to select a file on his machine. The flow will be:
click a button to upload a file or drag&drop a file into an area. Selection or drag&drop of a document will create a link to download this document by anyone with the link. This link will be added as part of the message (at the end)

You will need to create a discussion attachment entry to then use the standard document method (we already have functionality setup demonstrating how it works).

**Comment by damirius** [comment]
@bsaiken

Can you tell me in the first case where attachments aren't uploaded from the user's machine, which documents exactly is PM selecting to send? Are they on the server already? Since you said that he needs to select a document from "a list in a prompt popup". From where we are fetching that list?

**Comment by bsaiken** [comment]
@damirius 

There are two possible sources for attachments: 
1) Files that are on the user's machine (obviously) 
2) Forms that are associated with the Task.  So these form are already on the server.

The forms associated with the task will be listed at `/activetask/forms`.  Populating this view is ongoing: Issues #778 and #727.  Any of the forms that will be listed on this tab may be attachments.  You could read through the comments, or hopefully we will have this complete before you get to Issue #808.

**Comment by damirius** [comment]
@bsaiken

Clear as day.

**Comment by damirius** [comment]
@bsaiken

I know that you said that we will probably have /activetask/forms popup ready before I start doing issue #808, but I see that we will need it for this one too right?

**Comment by bsaiken** [comment]
@damirius @FWAJL 

Well, we ran into this snag.  What do we do if we try to communicate with someone who does not have an email address?  I do not want to make email addresses required.  I say it's not "required" but it is completely impractical if a PM sends a message to a FT and they are unaware of it.   At least, entering the email address should not be required to enter data into the system.  I want to be able to add a Field Technician without being required to enter the email address.  Similarly, I want to be able to add a Service Provider without needing their email address.  Or, add a Project, without being required to enter the Client's or the Facility Manager's email address.  

The problem then becomes:
1) How can these user's log in?  In other words, how do we give them login credentials?
2) How can we communicate with them?

The answer to both of these questions is they must have an email address.  Because, even if we gave them login credentials (say, we used the `technician.technician_name`, which is a required field) - how do we notify them that they are a registered user?  And, in the future as part of our improved security, they will need to confirm their email address to become a registered user.

So here is what I propose - and I am interested in your input as to whether this is the best way to implement this.  
It seems that we can control site access through the communications page. So, instead of listing (on the right hand side of the Communications page), Field Technicians and Service Providers, we have a primary heading of "Registered Users" and "Unregistered Users".  We can carry on communications with Registered Users.  So, this would be the same as we have set up now.  For Unregistered users, we provide a link to register them.

So it would look something like this:

![screen shot 2015-04-29 at 2 16 31 pm](https://cloud.githubusercontent.com/assets/8228624/7401616/6e4ac8c0-ee7a-11e4-8f96-ea9a7b979f1b.png)

I realize this is not a very efficient way of making the lists, and now takes up way too much space.  But it's the idea.

Then, we can communicate with Registered Users because they will have user credentials and an email address.  We can still automatically create a new user IF their email address is entered, either through the ADD of EDIT function.  If the PM adds a new Service Provider, for example, and the PM does not include their email address, they are still listed in the Task Communications tab, just as an unregistered user.

Interestingly, we currently don't have the email address of the PM as a requirement yet...but eventually we will because if I add a new customer (user) they will have had to go through the Registration process, which includes confirming their email, and problem solved.  

For the unregistered users, we just have a dead link for now and we can work out later how to get them registered from this stage.  I don't know if we will have time to do this before the end of May.  For this, and any other links links we have to leave dead, we can just a popup alert message that says "Not available".

**Comment by WebDevJL** [comment]
@bsaiken @damirius 

In your proposal, I see that, in the end, we will need an email value. So why not make it mandatory now so we are sorted? 
Issue #916 takes care of this. But if you don't want email required now, we can still add the user row with a dummy email so that we can later just update the email value.
The default email value could be "user_type + user_value @test.com" which will be unique. The password will be the hashed value of the email.

Therefore, I think that adding a user for each PM, FT, Client and Service provider now (which is done already) is quicker than coding a Registered/Unregistered separation which is something that we really need to see if it is necessary.

Let me know your opinions.

**Comment by bsaiken** [comment]
@WebDevJL @damirius 
Yes, this is a great idea.  However, instead of `@test.com`, let's make it `@fieldworkmanager.com", that way, I can catch and be notified of the site activity.  So, I say go with the default email value.

**Comment by FWAJL** [comment]
@bsaiken @damirius 

This is done in above commit. 
1. Client and Service provider don't require email but can provide 1 if they want. 
2. If they don't provide an email address, they will have their user email set to "client_id_1234@fieldworkmanager.com" or "service_id_1234@fieldworkmanager.com".
3. Technician and Project manager that are added have the email field required so we use the given value.

Now every new client, pm, ft and service provider will have email setup.

Thank you.

**Comment by damirius** [comment]
@bsaiken @FWAJL 

Great. Now we need that popup prompt with task forms which we will show as links, is that done?

**Comment by bsaiken** [comment]
@damirius @FWAJL @gsouvik 
I have Souvik working on this - Issue #941.
However, it is just some js, and needs to be applied to each UI where we have forms for the viewing, so if you want to implement this for your work, there may not be an overlap - we can divide and conquer.  I have already loaded the library files.  To keep everyone up on the progress, I would post a comment to Issue #941 stating the view where you implemented the js.  Since we work on different branches, this should avoid duplication of effort.

**Comment by gsouvik** [comment]
@bsaiken @FWAJL @damirius 
As I was mentioned in the last message, just to update, I've progressed quite a bit into this task and it should be ready in couple of hours.

**Comment by damirius** [comment]
@bsaiken @FWAJL 

OK, so this is the prompt for viewing the forms, but for this thing we need just a list of forms where PM can select one of them to add to the chat message right?
You said that I need to show this:
*2) Forms that are associated with the Task. So these form are already on the server.*

I know that we wanted to create copies of the forms when we activate the task, I don't know if we need those ones or just forms which are listed in the right panel on the forms tab under `Forms used for this task`

**Comment by damirius** [comment]
@bsaiken @FWAJL 

I've added local attachments for now. You can check it out on feature_thread branch.

You can check it out by going to Communications tab of some active task.
Activate some discussion with service provider.
Click Attach File button, upload box should show up after textarea. 
Choose some file, when it finished uploading, full path to the file should show up in the message text area. If you have already something there, file path should be added on the end of the message.
If you want you can click attach again to upload new file.
Keep in mind that currently our messages are limited to 500 characters, we could change this in the db if needed.

I was thinking of adding two radio buttons after 'attach file' button, one will be 'Upload' other will be 'Task form', depending of chosen button we will show upload box or prompt with list of task forms which are already on the server.

**Comment by WebDevJL** [comment]
@damirius 

>  Keep in mind that currently our messages are limited to 500 characters, we could change this in the db if needed.

We could add a character counter and the maxlength attribute on the textarea element to prevent over typing. What do you think?

**Comment by damirius** [comment]
@FWAJL 

Sure, that's a good idea. Do you think that we need to raise that char limit first?

**Comment by WebDevJL** [comment]
@damirius 

This is 1000 characters:

> Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. N

Make it configurable in the appsettings.xml and put a note that we need to update the database if raising the limit.
And update the size with a DB script.

**Comment by bsaiken** [comment]
@damirius @FWAJL 
Agreed.  The length at this point is not so important, so let's make it flexible until I discover the proper length.  
Is this ready for me to review?

**Comment by bsaiken** [comment]
@damirius @FWAJL 
As far as which forms are attachable, we limit the list to those that appear in the active task pane - the ones we created activating the task - the ones that are already listed on the forms tab.  So this list is already there.  

This excludes master and user form templates and maybe some other docs, but I will see if I need to include them later.

**Comment by damirius** [comment]
@bsaiken @FWAJL 

OK can you walk me through creation of those forms.
I'm trying to create them like this:
Go to Tasks->Add, enter the name of the new task.
Select "Task requires completion of a field form" so I get the form tab.
Go to form tab, I will get all user forms for that PM and all global template forms.
Promote some of them to this task.
Go to Tasks->List All, make this task active, right click it and select "Check task status".
Go to Forms tab. I can't see any forms in either left or right panel list.
I don't know if those changes are merged with my branch or not, or if this is the proper way to do it.

You can review the first part of this issue, local attachments. You can upload files from your machine. All of the files are stored in the discussion directory which will be created automatically.

**Comment by bsaiken** [comment]
@damirius @FWAJL 
It sounds like everything you did is correct, except:
There is one form created for each Location.  If you did not identify any Task Locations, there won't be any forms.

**Comment by damirius** [comment]
@bsaiken @FWAJL 

Oh, so that's it. Thanks! I'll work on that prompt for form attachments then.

**Comment by bsaiken** [comment]
@damirius 
I am not able to execute discussions on my local machine.  Is this because your work is in progress?
![screen shot 2015-05-05 at 12 25 00 pm](https://cloud.githubusercontent.com/assets/8228624/7481026/eb797052-f321-11e4-82d8-99414def4c2c.png)
![screen shot 2015-05-05 at 12 27 19 pm](https://cloud.githubusercontent.com/assets/8228624/7481050/17a3bee4-f322-11e4-9d96-15ed0a08cf5a.png)

**Comment by bsaiken** [comment]
@damirius @FWAJL 
Oops.  That was a false alarm.    We have Field Technicians in the system are not Users because they were put into the system prior to the auto-user generate code.  
I will clean up the database later today or tomorrow.

**Comment by damirius** [comment]
@bsaiken @FWAJL 

Also I think I need to change that error message, since it occurs when current discussion isn't set and that will occur every time when pm just logs in.

**Comment by bsaiken** [comment]
@damirius 
Error messsages are fine during the development phase.  I will eventually get rid of them.  This one, though, I agree is distracting because it is misleading.

**Comment by bsaiken** [comment]
@damirius  @FWAJL 
There is now one Service Provider if you login as `test:test`.
Their credentials are `TestSP@TestSP.com:TestSP@TestSP.com`

**Comment by damirius** [comment]
@bsaiken @FWAJL 

I've pushed new commit on feature_thread branch for the other part of this issue.

Go to Task->List All, right click on some active task which contains forms and services, select 'Check task status'.
Go to Communications tab, select some service from the list. Click on the arrow to active discussion between logged in PM and that Service provider.
Send and Attach File button will show up, you will see two radio buttons below them.
Choose 'Task Location form' and click 'Attach File' button.
Popup selector should be shown, choose one of those pdfs by clicking on it's title in the list. Click OK.
File will be read and it's filepath should be added to the message box, just like with local uploads.

**Comment by bsaiken** [comment]
@damirius 
Is there a database update needed for this?  My first attempt to test did not work.

**Comment by damirius** [comment]
@bsaiken

DB update is not needed. You just need to logout then login, since there are new routes added. If that doesn't help, can you tell me where it breaks?

**Comment by damirius** [comment]
@bsaiken

Here is the video demonstration:
https://drive.google.com/file/d/0B7Laiv0PjSvDZzJKRnBBbjJZLUU/view?usp=sharing

**Comment by bsaiken** [comment]
@damirius @FWAJL 
In order for this to work on my local machine, I need to have Service Providers that are users.  I tried to add a new Service Provider in order to initiate the new code that automatically makes them a user.  However, I am unable to insert a new Service Provider. 
I believe this problem is not worth solving because it is temporarily localized to the conditions on my machine.  This will correct itself as I update my local machine to the live site.
The video demonstration is sufficient for me to accept the code from a function review standpoint.
It also goes a long way knowing the Damir is a coding genius.

**Comment by bsaiken** [comment]
@FWAJL 
This seems to be working on the live site just fine.
