### ISSUE TITLE
Disscussion Thread Milestone E - Handling Attachments providing a link

### ISSUE THREAD

**Issue by bsaiken** [FWAJL/FieldWorkAssistantMVC#808]
Milestone E is to enable the user to send attachments to the Service Providers that are stored on the website.  We will call these “local attachments” to differentiate them from attachments that originate on the user’s computer.  

The forms that may be used as local attachments would be available to the user at the url: ../task/forms.  Include an alternative so the form may be selected from the list at /task/forms.  This may be in a popup Prompt box.  We have already implemented a suite of bootstrap popup boxes.   

When sending a message to a Service Provider, include a link that would allow the Service Provider to download the local attachment.

**Comment by damirius** [comment]
@bsaiken @FWAJL 

URLs in chatbox should be hyperlinked now, note that all 'a' tags have `display:block` set in css for some reason. Also links are black just like the rest of the text.

**Comment by bsaiken** [comment]
@damirius 
Works great.  One small change.  Shouldn't the attachment hyperlink text that is displayed be the Title (if the user entered one)?

**Comment by damirius** [comment]
@bsaiken

We are sending full path url through the message. Maybe we can add title on the end of url after hashtag, for example we have this url: http://localhost/FieldWorkAssistantMVC/Web/uploads/discussion/6_15cbbbdf-017c-4ee6-b1a6-991f00f074bd.jpg
If we add that picture with title url becomes this, http://localhost/FieldWorkAssistantMVC/Web/uploads/discussion/6_15cbbbdf-017c-4ee6-b1a6-991f00f074bd.jpg#Title.
Then when displaying the link in the chatbox we reformat it to `<a href="http://localhost/FieldWorkAssistantMVC/Web/uploads/discussion/6_15cbbbdf-017c-4ee6-b1a6-991f00f074bd.jpg" target="_blank">TITLE</a>`
