### ISSUE TITLE
Add password hint and change module

### ISSUE THREAD

**Issue by bsaiken** [FWAJL/FieldWorkAssistantMVC#814]
Add a module that will allow the user to change their password hint and their password.
This module will be added to the the following modules:

Pm/showForm.php
Technician/showForm.php

Also, add a module for the admin login, connected to the `glyphicon-user`, so that this admin can change their password.  The only form items for the admin/showForm module should be the usernname, password hint, and password.

**Comment by damirius** [comment]
@bsaiken @FWAJL 

Why don't we add all this to the user/showDetails page we have for changing other info as well?

**Comment by bsaiken** [comment]
@damirius @FWAJL 
The only reason I suggested a separate module is that Project Mangers have access to the Techncian's pages, and the PM would not be able to edit the Technician's password.  If it's a separate module, I can use roles to mix and match this way.
Of course, if it's a big coding hassle, and it slows us down from pressing on to more important matters, you could just add it to all, and then I could change it later if I decide it is really needed.

**Comment by bsaiken** [comment]
@damirius @FWAJL 
Damir,
I have someone working now on the mobile part of the website.  They will soon be wanting to work with the `/technician/showForm`, so I moved this Issue to highest priority for you.  If you need to split the work for adding the username/password module, please do the Field Technicians first.

**Comment by damirius** [comment]
@bsaiken @FWAJL 

Can you tell me what's up with that Issue which takes care of creating `user` record along with `technician` since our technicians don't have linked user account, just their `technician` record. We need to setup usernames/passwords and link them to appropriate technicians.

**Comment by bsaiken** [comment]
@damirius @FWAJL 
I was able to log in as the admin and add a new Project Manager user (newuser).  So, the method is already written.  If you navigate to `user/showForm` (you have to logged in as admin), the dropdown box shows two options: "Admin" and "pm_id".  
Please comment out "Admin" from the options and add "technician_id".  I think, with a few small code changes, I could then add a new technician in this way.  Normally, this would not be needed.  Just for development.
Normally, I want technicians added automatically whenever a PM adds a new technician.  Initially , the Technician would have a user name and password that are their email address.
I'd do more to split this into the appropriate Issue, but I am traveling today, so my communications windows are limited.

**Comment by bsaiken** [comment]
@damirius 
In reference to your previous comment - is creating the user record required to write the code for this Issue?

**Comment by damirius** [comment]
@bsaiken @FWAJL 

Yea it is required that we have user record, since that record contains username/pass combination together with 'password hint' which we want to change on technician/showForm page.

**Comment by damirius** [comment]
@bsaiken @FWAJL 

Added user form module to technician form page and to showDetails page (user details glyphicon button). Note that technicians still don't have user records, but for testing you can just add new `user` record. Make sure that you set `user_type` field to "technician_id" and `user_value` to id of the technician you want to link it to. `user_password` and `user_hint` can be whatever you like since you can change it from the technician showForm page as PM.

We should go back to Issue #812 I believe so that every new technician gets user credentials automatically but we also need to see what to do with existing FTs.

**Comment by FWAJL** [comment]
@damirius @bsaiken 

Go ahead with #812. It is a very small task anyway. And at least all the technician added from now on will have their user record.

Making the user records for existing technician will need to be done separately. I think only some SQL script is needed. I will look into it.

Thank you Damir.

**Comment by bsaiken** [comment]
@damirius @FWAJL 
I do not see that this was added.  What is the function I am supposed to be reviewing.

**Comment by damirius** [comment]
@bsaiken

Go to Technicians->Add, fill up the text fields with some data and click Save button to create new technician along with his generated user record. New technician user should be created where entered email is used as both user and password.
While you are still logged in as PM, go to Technicians->List All, find new technician and right click on it to edit him. User form with password and hint should be shown, fill up the hint field, if you want to change the password too type it in the password field and click save. FT user credentials will be updated. You can logout and login again with FT credentials.

Also all users will have user form as the part of their user/showDetail page (glyphicon user button).

**Comment by FWAJL** [comment]
@damirius @bsaiken 

One bug: I added a FT and his login saved is firstname@domain whereas I saved the email to be firstname@domain***.com***. See my commit for the fix.

@bsaiken just try to go to the logout url and login again.

**Comment by bsaiken** [comment]
@FWAJL @damirius 
Worked for me.
