### ISSUE TITLE
\Library\HttpRequest fetch_from_array issue

### ISSUE THREAD

**Issue by nadirhamid** [FWAJL/FieldWorkAssistantMVC#823]
So, theres an issues on HttpRequest\fetch_from_array

strip_tags($array[$index]);
could be 
strip_all_tags($array[$index]);
with respect to an array or object

This currently threw a warning and is hard to analyze in debugging

**Comment by FWAJL** [comment]
@nadirhamid 

In what case are you seeing the problem?
You can fix it. Test it by editing a project, a location, a service, a technician.

Commit go onto your branch feature_thread. 
Let me know if you need help.

Thank you.

**Comment by bsaiken** [comment]
@nadirhamid @FWAJL 
Hi Nadir.

Whenever you post a comment please reference both @FWAJL and @bsaiken, that way we know you have posed something.  Very handy tool in github.

Also, Jeremie (FWAJL) and I (bsaiken) should be the ones creating new Issues.  You can request a new Issue any time.  Often, a new Issue means something is out of scope, so I would need to know to make that determination.  I can't tell yet if the fetch_from_array is an out of scope Issue.  If it is, generally I will either want us to fix it, or make an arrangement with you to do it.  The way I wrote my contract, small items (<$50) can be added to your scope of work here, as long as I give the go-ahead.

**Comment by FWAJL** [comment]
@nadirhamid 

In what case are you seeing the problem? I'd like to replicate the issue, please.

**Comment by nadirhamid** [comment]
Hi @FWAJL 

So I am calling the dataService post method with an array,
so:
data = {
 "an_array": []
}

the data is being sanitized by HttpRequest's function select_many which is
not checking for array values in this structure

**Comment by FWAJL** [comment]
@nadirhamid @bsaiken 

I'm sure why you are trying to send an array. Can you explain the use case? I will be able to help you fully then.

If you look at the "Edit a project" (http://dev.fieldworkmanager.com/project/showForm?mode=edit&project_id=141 as test user), we send a JavaScript object to the PHP server, not an array. This object is built using the utils.retrieveInputs method in utils.js and is used by project_manager.edit.

Let me know.

Thank you.

**Comment by nadirhamid** [comment]
Hi @FWAJL,

So to expand on this project I am sending a JSON object which I assume while not having
checked is being encoded, one of its key values being an array is throwing a warning.
i.e try:

 project_manager.add = function(data, controller, action, isCopying) {
    isCopying = isCopying || false;
    data['array'] = ['one','two'];
    datacx.post(controller + "/" + action, data["project"]).
 }

this would try a warning. let me know if you need expansion on my explanation or if there is a work around

**Comment by FWAJL** [comment]
@nadirhamid @bsaiken 

In the current state of the framework, you need to make a JavaScript object with your array using the associative structure so that you have the following:

```
project_manager.add = function(data, controller, action, isCopying) {
    isCopying = isCopying || false;
    data["object"] = {"prop1": "one", "prop2": "two"};
    datacx.post(controller + "/" + action, data["object"]).
}
```

Can you do this instead?

**Comment by nadirhamid** [comment]
Hi @FWAJL,

Thanks while I can do this, my array having no key based structure would not benefit from it and the keys would hence become unused. So I am currently passing in a flat array of ids which are collected as per the user input (or checkboxes), analagous to
[1, 2, 3]

**Comment by FWAJL** [comment]
@nadirhamid 

Please tell us what is your use case? What is represented with your ids? Is an array the best solution?
Thank you

**Comment by nadirhamid** [comment]
i will temporarily switch to not using an array however was just passing ids of the Dal objects. this being collected in the page

**Comment by FWAJL** [comment]
@nadirhamid @bsaiken 

Same comment Brian's comment here regarding this issue #823: https://github.com/FWAJL/FieldWorkAssistantMVC/issues/842#issuecomment-91007749

Please clarify. Thank you.

**Comment by FWAJL** [comment]
@nadirhamid @bsaiken 

Just to answer this: if you are retrieving a list of object's ids, just build a csv variable that you add to the JavaScript object serialized to JSON. Then on the server side, you can use the split function in PHP to create the array of values you want.

See the examples in:
Client side: https://github.com/FWAJL/FieldWorkAssistantMVC/blob/dev/Web/js/app/controllers/location_manager.js#L46
Server side: https://github.com/FWAJL/FieldWorkAssistantMVC/blob/dev/Applications/PMTool/Helpers/LocationHelper.php#L162

So no need to adapt the HttpRequest class for now.

Also, please, accept the invitation to join the FWM-Team so you can receive the messages I send there. It is there that you should ask questions. Not here.

FWM-Team: https://github.com/FWM-Team/FWM-Backlog-Issues/issues

Thank you.
