### ISSUE TITLE
Admin can edit their password and hint (link to glyphicon-user).

### ISSUE THREAD

**Issue by bsaiken** [FWAJL/FieldWorkAssistantMVC#828]

**Comment by FWAJL** [comment]
@bsaiken @damirius 

similar to #814 ?

I think the username shouldn't be updated, as it is not common practice. Also, I have added a unique constraint to the user_login column.

**Comment by damirius** [comment]
@bsaiken @FWAJL 

Yea, we can run into problems if we let them change their usernames and like you said it's not a common practice. Keep in mind that admin can edit them too from user list, I'm thinking of removing "username" field from user form on user/showForm for admins when they are editing users, but I guess that's smaller priority since that one is admin only.

**Comment by FWAJL** [comment]
@bsaiken @damirius 

The constraint will prevent setting a login already taken anyway so we are safe.

I would suggest to disable the input. That's rather easy, no? @bsaiken : can you give us your opinion?

Thank you.

**Comment by FWAJL** [comment]
@bsaiken @damirius 

I think we also need a unique constraint on email values (technician, service provider, client...). I will take care adding it.

**Comment by bsaiken** [comment]
@damirius @FWAJL 
OK, so I can edit the admin's username directly in the database.  That's fine.

But, I want the ability to edit the password, which I cannot do.  "test" is not exactly a high security password.

**Comment by damirius** [comment]
@bsaiken @FWAJL 

As the part of the password/hint changing issue #814 you can now change your password as the admin as well. Click on the user glyphicon button and you'll see user form in which you can type new password and/or password hint.

**Comment by bsaiken** [comment]
@FWAJL 
Working.  I temporarily changed the admin password to "1111", so be aware of that.
