### ISSUE TITLE
Concern: ExecuteQuery and delete in BaseManager

### ISSUE THREAD

**Issue by nadirhamid** [FWAJL/FieldWorkAssistantMVC#843]
Status: Pending
Issue: #843
Assign To: N/A
Mention: @FWAJL @bsaiken
 
So while trying to extend delete method I was unable to get around some
'private' declarations, given my object context use. Is it possible to turn this
into protected? while I can call parent:: statically I'd like to
keep it in object context

example:
class NewClassDal extends Library\DAL\BaseManager {
   private function delete() { $this->ExecuteQuery(); // no good in context }
}

**Comment by FWAJL** [comment]
@nadirhamid @bsaiken 

Same commet as Brian's here: https://github.com/FWAJL/FieldWorkAssistantMVC/issues/842#issuecomment-91007749

Please clarify.

Thank you.

**Comment by bsaiken** [comment]
@nadirhamid 
Nadir,
I do not understand your actions.  You have created this new Issue and identified it as a bug, but there is no explanation, no assignee, and no reference to an Issue in your scope of work.  Please clarify.
