### ISSUE TITLE
Milestone A - Landing page for Field Technician users

### ISSUE THREAD

**Issue by bsaiken** [FWAJL/FieldWorkAssistantMVC#845]
The live FT test user is:

login: joe@fwm.com
password: test
linked: to technician_id=1

**Comment by bsaiken** [comment]
@testingbydev @FWAJL 

One of the key things you will need to do for this Issue is to add the routes to: 
/Applications/PMTool/Config/routes.xml

Since you are creating the mobile pages, all your views will have the route attribute `role="3"`.  
You will see in the `user` table that the login above (joe@fwm.com) has the `user_role_id=3`.
In the case where are you displaying an existing page (e.g. /technician/showForm), you can specify more than one role for the route by adding role="1,2,3" and so on. So just add role_ids separated by commas.

**Comment by FWAJL** [comment]
@bsaiken @testingbydev 

Please use this database script to get all the data from the live server: https://github.com/FWAJL/FieldWorkAssistantMVC/blob/feature_mobile/Database/Scripts/Online-backups/baiken_fwm_1_20150413.sql

The user mentioned above is found in it.

**Comment by FWAJL** [comment]
@testingbydev 

Also, can you tell me if you received the invitation to this Team: https://github.com/FWM-Team ? This is where we can talk about general questions. Also, I send general info to all the team members on a regular basis (release, database updates, etc...).
I have sent you several requests but you have not yet accepted any.

Thank you.

**Comment by testingbydev** [comment]
@FWAJL

If we create a new page then where all do we need to specify that in the code files. Or if you have any manual/Guide on how to use this MVC that would be helpful too . We have created a page and that shows error.

**Comment by bsaiken** [comment]
@testingbydev 
I may be able to help if you can show me the error.  
Did you modify routes.xml?

**Comment by testingbydev** [comment]
@FWAJL

Yes we have modified routes.xml file. We are not able to understand the internal routing. we have created a new page and need to set routing for that page.I would try to commit the changes that we have done for creating new page.

**Comment by testingbydev** [comment]
@FWAJL

We are able to create the "WECOME" page , now should i commit the page and push on repository ?

please suggest

**Comment by FWAJL** [comment]
@testingbydev @bsaiken 

Please commit the work to the feature_mobile branch. Please follow the steps described in https://github.com/FWAJL/FieldWorkAssistantMVC/wiki/4.Git-branching-model to link your local feature_mobile branch to the remote feature_mobile branch.

Please read this document (https://github.com/FWM-Team/FWM-Backlog-Issues/issues/4) also and follow the workflow described (set the proper status, set the proper assignee).

Also, please accept the request to be part of the FWM team: https://github.com/FWM-Team
Thank you.

**Comment by testingbydev** [comment]
@FWAJL

Can you let me know the repository url where we need to commit the code . Also we need the information to add a  key pair from my system to commit the code on your repository. 

On https://github.com/FWM-Team I am not able to see how can i accept the request and be a part of team.Please guide on this as well.

**Comment by FWAJL** [comment]
@testingbydev @bsaiken 

I'm sorry, did you not follow the wiki for Installation? (it is found here: https://github.com/FWAJL/FieldWorkAssistantMVC/wiki/2.Installation)
How do you retrieve the repository?

**Comment by FWAJL** [comment]
@testingbydev 

Regarding the FWM team, I have sent you a request to join several time. You should have received an email from GitHub. I will look into it.

**Comment by testingbydev** [comment]
We retrieved the repository from
https://github.com/FWAJL/FieldWorkAssistantMVC
 and used the command "git clone https://github.com/FWAJL/FieldWorkAssistantMVC.git"

**Comment by FWAJL** [comment]
@testingbydev 

Good. Please make sure to follow the guidelines to submit the code, especially selecting your branch "feature_mobile". Thank you.

**Comment by testingbydev** [comment]
@FWAJL

We are facing an error in committing  the code on repository, Attaching an screenshot for the same. Can you please see where i am going wrong. 
![screenshot from 2015-04-20 17_31_45](https://cloud.githubusercontent.com/assets/9897157/7231061/63d34246-e790-11e4-804b-be35fb5d6897.png)

**Comment by bsaiken** [comment]
@testingbydev 
The instructions for committing code are here:
https://github.com/FWAJL/FieldWorkAssistantMVC/wiki/3.Use-the-repository-with-Git
You must follow each step.
You may only commit code to the feature_mobile only.
I am available to help if needed.

**Comment by FWAJL** [comment]
@testingbydev @bsaiken 

I see that you are on the wrong repository. We work on https://github.com/FWAJL/FieldWorkAssistantMVC. Please follow the guidelines as Brian stated. Thank you.

**Comment by testingbydev** [comment]
![error](https://cloud.githubusercontent.com/assets/9897157/7233018/5d40cf82-e79c-11e4-99e1-5a491e497214.png)

We are using the correct repository, screenshot i sent you was for test repository that we created.

Please make sure you have the correct access rights
and the repository exists.
 Repository URL : git remote add origin git@github.com:/FWAJL/FieldWorkAssistantMVC

**Comment by bsaiken** [comment]
@testingbydev 
You are not following the instructions to commit code that is described here:
https://github.com/FWAJL/FieldWorkAssistantMVC/wiki/3.Use-the-repository-with-Git

**Comment by bsaiken** [comment]
@testingbydev 
If you need additional help committing code to the repository, I can be available at Skype or we can use TeamViewer to review your steps.  Let me know.

**Comment by testingbydev** [comment]
@bsaiken 

I would try more but still If you can be available tomorrow on skype then it would be helpful.

**Comment by bsaiken** [comment]
@testingbydev 
Tomorrow (Tuesday) is a travel day for me.  I am available, from 1pm - 3pm Pacific Daylight Time.  I could also be available tomorrow 6am - 8am Central Daylight Time if you notify me in advance.

**Comment by testingbydev** [comment]
@FWAJL
Issue #845 has been resolved. uploaded code on repository featured_mobile branch.

**Comment by FWAJL** [comment]
@testingbydev @bsaiken 

Please always include Brian's @mention in your messages.
Please set the status and assignee to the correct value when you are done. Please read our [Workflow document](https://docs.google.com/document/d/1COa-OrxiAMfBzTmQfwsDU2xYbwZBWwRpbOxLzmWKvW0/edit?usp=sharing)

Now, please revert your change in appsettings.xml as in the [Installation manual](https://github.com/FWAJL/FieldWorkAssistantMVC/wiki/2.Installation), we do say not to change the appsettings.xml. This is to keep an application working for everyone. Please make you carry out the database setup properly. Thank you.

Also remove the following files:
https://github.com/FWAJL/FieldWorkAssistantMVC/blob/9364e03cbcd136e67a836dda37875b60e5a7cc29/Applications/PMTool/Config/~~appsettings.xml
https://github.com/FWAJL/FieldWorkAssistantMVC/blob/9364e03cbcd136e67a836dda37875b60e5a7cc29/Applications/PMTool/Config/~~routes.xml
https://github.com/FWAJL/FieldWorkAssistantMVC/blob/9364e03cbcd136e67a836dda37875b60e5a7cc29/Web/js/app/controllers/~~auth.js

Finally, can you make sure you have done a git pull as I have pushed to your branch the latest updates this morning but your commit doesn't include them. Always do a git pull before pushing code. 

Thank you.

**Comment by testingbydev** [comment]
@bsaiken

Make changes that you have requested.

**Comment by bsaiken** [comment]
@testingbydev 
If you want me to review your code, you need to:
Change the Labels to `status: function review`
Change the Assignee to: bsaiken

**Comment by bsaiken** [comment]
@testingbydev @FWAJL 
I can see the Welcome page - now we are over the biggest hurdle!

You need to move the view module (welcome.php) from /Views/Project/ to /Views/Mobile.
 The Project module is only for Project pages.

Line 698 of the routes.xml file will look like this:
<route url="mobile/welcome" module="Mobile" action="welcome" resxfile="mobile" type="ui" role=“3”>

Lines 713 - 719 in routes.xml should be removed.  Only list the modules you need.  I do not know if any of the modules we have will work for the mobile site or not - you will need to decide.

You will be making a map page, but I do not know if you will need line 702 of routes.xml, so I recommend commenting it out. 

Since you have a separate View, you will need the following:

a Controller file with the same name, so you will need /Controllers/MobileController.php  
So, you will need to move lines 79 - 91 in your ProjectController.php file to MobileController.php.   I do not think lines 82 - 87 are relevant, so yo may want to remove them.

You will very likely need to create a Helper Class at /PMTool/Helpers.  The file name will be MobileHelper.php.

a separate js file.  The js file will be /Web/js/app/controllers/mobile_manager.js.  All your js for the mobile site should go in this file.  You will need to change line 701 of routes.mxl

a separate CSS file: /Web/css/app/mobile.css   You will need to change line 706 of routes.xml

a separate resource file.  The resource file will be:  /Resources/Local/mobile.en.xml.  All text that appears on the pages should be in this file.  No in-line text.

you may need to add keys at /Resources/Enums

Once you have re-done the structure, I will want you to have some minimal formatting so that I can see wiat the page will look like on a mobile device.  For testing purposes, just make the “Welcome” message a clickable button.  For now, you could just have a link to an alert box, or something very simple.

**Comment by bsaiken** [comment]
@tarun_nagar @FWAJL 
You are not a contributor - will you be committing code?

**Comment by bsaiken** [comment]
@testingbydev 
Please help me understand who is going to be contributing code to the site.  

We have had code committed by tarun_nagar, but they are not identified as a github contributor, nor are they identified in the github system.  I am concerned about the site security if anyone can commit code without being identified as a contributor.  Can you confirm the identity of tarun_nagar?  If they are going to be the one commiting code to the site, can you have them set up their own github account?

If I have comments do the code, to whom should I address the comments?

**Comment by bsaiken** [comment]
@testingbydev 
FYI: I will be doing the function review of your work using an iPad mini.  When I send you screen shots requesting changes they will be taken using my iPad mini.  Of course, I want the views to look good on all platforms, but I did want you to know I will do all function reviews with a mobile device.  So, make sure you test with a mobile device before releasing for me to review.
Thanks!

**Comment by anuj-yadav** [comment]
@bsaiken 
Please Can you suggest us to resolved some task such as 
Adding Keys at "/Resources/Enums"
We didn't get this Point.

**Comment by testingbydev** [comment]
@bsaiken 
Please Can you suggest us to resolved some task such as
Adding Keys at "/Resources/Enums"
We didn't get this Point.

**Comment by bsaiken** [comment]
Coding questions should be put to FWAJL

**Comment by bsaiken** [comment]
@testingbydev @FWAJL 
You must put coding questions to Jeremie (FWAJL).

**Comment by testingbydev** [comment]
@FWAJL
Please Can you suggest us to resolved some task such as
Adding Keys at "/Resources/Enums"
We didn't get this Point.

**Comment by FWAJL** [comment]
@testingbydev @bsaiken 

Please be more specific in your question. Do you need:

1. to add a constant key in one of the files at https://github.com/FWAJL/FieldWorkAssistantMVC/tree/dev/Applications/PMTool/Resources/Enums
2. to know what is the use of https://github.com/FWAJL/FieldWorkAssistantMVC/tree/dev/Applications/PMTool/Resources/Enums
3. to know how to add constant key values and in which to put it in?
4. other question?

A question to you: what is your use case?
Thank you.

**Comment by testingbydev** [comment]
@FWAJL 
we have done pages for mobile site for user Role 3 according the project structure.

**Comment by bsaiken** [comment]
@testingbydev 
The proper next step is to change the status to `status: function review`, and set me as the asignee (bsaiken).  I did it for you, but it will move things along more smoothly if you do it.

**Comment by bsaiken** [comment]
@testingbydev @FWAJL 
I was able to review the result and it looks like a good start.  There are some coding problems that I caught, so I will provide them here.  Normally, I will not do a code review, but the site was not working and I needed to make some changes. 

You must review your code to make sure it works prior to making a commit.

Here are code problems I found:
1) You must modify line 53 of auth.js to read: `window.location.replace("mobile/welcome");`
This is why the site was not working.  The re-direct was not pointing to the mobile module.
2) You created a resource file, but you did not use it.  There can be no in-line text in the module views.  For example, change line 6 of `welcome.php`. 
Instead of:   `<h2> Welcome User </h2>`, 
use:  `<h2><?php echo $resx["h2_welcome"]; ?> </h2>`
Then you will need to add a line to `mobile.en.xml` to read:
`<resource key="h2_welcome">Welcome User</resource>`
3)  I see that you added the class `.mobile_main` to line 3 of left.php.  I do not think we need the left menu, so this is one way to hide the left menu margins - but we should ask Jeremie if it is better to not display the left.php module at all - and how to do that.
4) Related to 3), since there will not be a left menu, we want the view to span the entire width.  If you remove line 5 from `welcome.php` (and the associated </div>), the view spans the entire page.  Not sure this is the best way to do this, but it is the look I want on the front end.
5) I think it will be beneficial, perhaps necessary, to use our module structure.  To do that, you need to make these changes:
 - move the `welcome.php` module to: `/Applications/PMTool/Views/Mobile/Modules/welcome.php`
 - create a view page, `loadView.php` at: `/Applications/PMTool/Views/Mobile/loadView.php`
The loadView page simply sets the container and calls the required module(s), so the code would be:
`<?php if (!defined('__EXECUTION_ACCESS_RESTRICTION__')) exit('No direct script access allowed'); ?>
<div class="col-lg-12 col-md-12">
<?php require $form_modules["welcome"]; ?>
</div>`
 - You will need to modify line 666 in `routes.xml` to point to the loadView page:
`<route url="mobile/welcome" module="Mobile" action="loadView" resxfile="mobile" type="ui" role="3">`
and, you need to add the `welcome.php` page as a module.  Add the following lines after line 677:
`<php_modules>
<php_module key="welcome" file_name="welcome.php" />
</php_modules>
 - Finally, you need to initialize the module(s) in `MobileController.php`
Line 40 needs to be modified to:
`public function executeloadView(\Library\HttpRequest $rq) {`
because you are calling `loadView`, not `welcome`
Then, the module view `welcome.php` can be loaded using one of our standard code snippets:
`//Load Modules for view
$this->page->addVar(
        \Applications\PMTool\Resources\Enums\ViewVariablesKeys::form_modules, $this->app()->router()->selectedRoute()->phpModules());`
***************************************************************************

I have one question.  Is it possible to use css to change how the header looks?  The logo and glyphicons are rather small for a mobile device.  

I saw that you included css files from the main site:
	    <css_file value="Web/css/app/nav.css" />
	    <css_file value="Web/css/app/app-theme.css" />
	    <css_file value="Web/css/app/style.css" />
I think it will be better to have all the necessary css in the mobile.css file.  Then, if we change the css for the header elements, there is no conflict.

**Comment by testingbydev** [comment]
@FWAJL  @bsaiken

We have made all the required changes that you have suggested above, Now regarding the new header look can you suggest how it should look like, any recommendations from your side ? After that we would push the code to repository.  Also let us know what all sections would come in this panel .

**Comment by bsaiken** [comment]
@testingbydev @FWAJL 
Perhaps you made the changes, but you did not commit the code to github; therefore, I cannot review.

**Comment by bsaiken** [comment]
@testingbydev 
As far as how the page looks, I just had a questions about whether we could use to change how it looks.   I played round with the CSS and made the glypicons and logo bigger, so I answered that for myself.   There is no need for you to do that in this stage.  Just move all the CSS for the mobile pages into a new CSS file and include only the mobile CSS file in the routes.

Here is the CSS changes I made, on an iPad and iPhone.  I like this better than what we have.  So when you start making pages that actually have content, they should look more like this.

![img_3218](https://cloud.githubusercontent.com/assets/8228624/7358793/015ab146-eced-11e4-892a-5c49951bf82b.PNG)

![img_0059](https://cloud.githubusercontent.com/assets/8228624/7358796/06162b8e-eced-11e4-8e0e-37679de84fa5.PNG)

**Comment by testingbydev** [comment]
@FWAJL @bsaiken
We have Redone the code structure according to MVC coding structure  and changing the Header Design For mobile and Tablet. please review the code.

**Comment by WebDevJL** [comment]
@testingbydev 

Be careful in the commenting of your commit: the syntax is `Issue #845` without the [ ].

Adding reference to commit:https://github.com/FWAJL/FieldWorkAssistantMVC/commit/2939413459adbbce0ea0d417db1cffb861caded0

**Comment by testingbydev** [comment]
@WebDevJL 

Sure i would take care next time.
Let me know if code has been approved and we can move to next issue

**Comment by testingbydev** [comment]
@FWAJL @bsaiken

Do i need to follow any step for sending code to review ?

**Comment by bsaiken** [comment]
@testingbydev 
See my comment from April 24.  set status to `function review`.  Assign `bsaiken` as assignee.
Also, per Jeremie's comments, reference the Issue number when you make the commit.
If you do these things, everything moves along smoothly.  If you do not, it will delay our review.  
Also, we have asked several times to follow our instructions and you have not.  Please ask questions if you are not clear.

**Comment by bsaiken** [comment]
@testingbydev  @FWAJL 
You did not make the required change to the auth.js file, as I had instructed in my previous comment.  Therefore, the cannot not work.
Please do not commit code that does not work.  Do you review your code before you commit it?
You must make another commit and follow the instructions for submitting code.

**Comment by FWAJL** [comment]
@testingbydev @bsaiken 

As per our [comment](https://github.com/FWAJL/FieldWorkAssistantMVC/issues/845#issuecomment-94378746), we have a clear procedure written that everyone follows. Please read it in details. Thank you.

https://docs.google.com/document/d/1COa-OrxiAMfBzTmQfwsDU2xYbwZBWwRpbOxLzmWKvW0/edit?usp=sharing

Thank you.

**Comment by testingbydev** [comment]
@FWAJL   @bsaiken
Now we have done to make changes for line 53 in auth.js " window.location.replace("mobile/welcome");"
I have checked it on browser tab and mobile screen but unable to check it on mobile device due to ethernet issue.

**Comment by bsaiken** [comment]
@testingbydev @FWAJL 
This works, thank you.  And thank you for following our code submission procedure - it will really help with things as we move forward.
Now Jeremie will do code testing and we will get back to you soon about starting the next Issue.
DO not start the next Issue until we get his approval.

I see that we are still displaying the `left-aside` section.  We do not need this, but we can work it out in the next Issue.

I use Chrome browser for testing, which has a mobile emulator (see screen shot below).  This is very easy to set up.  Let me know if you need help doing this.  For future Issues, #848 for example, you will need to do live testing on your local server with a mobile device to make certain all the behaviors and functions work.

**Comment by testingbydev** [comment]
@bsaiken
Thank you for feedback. i will use the mobile emulator and setup the site on our development server so i can checkout in mobile device also.
