### ISSUE TITLE
Milestone E (1) – Create the Location Map page & (2) – Create the Location List page 

### ISSUE THREAD

**Issue by bsaiken** [FWAJL/FieldWorkAssistantMVC#848]
Milestone E(1) – Create the Location Map page. 
This page contains the same map as the PM page: http://dev.fieldworkmanager.com/map/taskLocations

Use the module that has been created for PMs with the URL http://dev.fieldworkmanager.com/map/taskLocations.  

Each Location marker shall be selectable.  Selecting the Location marker sets the session variable $currentLocation.  When a Location is selected, an info window appears.  We have already set up info windows for marker, but the info windows that the FT sees is different than the PM.  The FT info window includes: 
Location name (not-editable), 
a button to upload a photo (stored on the device, or with the camera)
textarea for notes (stored in location.location_desc)
a button to “Collect Data” which re-directs to m.fieldworkmanager.com/forms.html 
a button to get directions to the Location (walking or driving, with walking being the default)

Additional modifications to the map page shall be performed by others. 
Milestone E(2) – Create the Location List page.  
This page shall include the list of Task Locations.  It is the same list as the Project Manager page at url: http://dev.fieldworkmanager.com/task/locations (goup_list_left module only)

Each Location in the list marker shall be selectable.  Selecting the Location marker from the list has the same function as in E(1) EXCEPT there is one additional option in the info window:  “Mark Location”.  The option “Mark Location” shall use the current device coordinates and save this data to location.location_lat and location.location_long.

**Comment by damirius** [comment]
@bsaiken

I've added custom task location infowindows for mobile map.
If you open up some location, you will have few new options. 
'Mark' fetches user's coordinates and populates, lat/lng fields, clicking on save button will update that marker.
'Collect data' will just redirect the user to mobile/forms, that page isn't yet done.
'Directions' will fetch users position and calculate the route from it to marker's position. Choosing 'Drive'/'Walk' from dropdown menu will set that option as the primary travel mode.

It's on feature_mobile branch. No database updates for this one.

**Comment by bsaiken** [comment]
@damirius 
This is great.  Working just the way I had hoped.

**Comment by bsaiken** [comment]
@damirius 
FYI - I made a commit to this Issue...

**Comment by bsaiken** [comment]
@damirius 
If this, or any other "to merge" Issue has been merged, please change the status to "to release".

**Comment by bsaiken** [comment]
@FWAJL @damirius 
The mobile UI is not working on the live site.  When a FT logs in, the default landing page is `/user/showDetails`.  
I created a new Task and assigned a FT user to the Task, and the landing page is still `/user/showDetails`.  This situation should land on the map page for that Task.

**Comment by bsaiken** [comment]
@FWAJL 
Isn't this now working on the feature_mobile branch?

**Comment by WebDevJL** [comment]
@bsaiken 

I don't know. Maybe the new release fixes that?
