### ISSUE TITLE
Milestone E (5) – Create the Communications page & (6) – Create Services page

### ISSUE THREAD

**Issue by bsaiken** [FWAJL/FieldWorkAssistantMVC#850]
Milestone E(5) – Create the Communications page.  

This page is similar to the notes page, except a recipient must be identified.  Possible recipients include:
The Project Manager
Other Field Technicians assigned to the Task  (This is the same list as the Project Manager page at url: http://dev.fieldworkmanager.com/activetask/communications?task_id=x (Technicians) - except that FTs cannot send a message to themselves.
Any of the service providers assigned to the Task (This is the same list as the Project Manager page at url: http://dev.fieldworkmanager.com/activetask/communications?task_id=x (Service Providers)

For the development of the mobile UI, the field contents get saved to the server.  Other functions, such as forwarding the message to the PM as a txt message (for example) shall be developed separately.

Milestone E(6) – Create Services page.  

This page shall include the list of Service Providers.  It is the same list as the Project Manager page at url: http://dev.fieldworkmanager.com/activetask/communications?task_id=x (Service Providers)

Each service provider shall have a clickable link that will display a new page with the Service Provider info.  This is the same info that is displayed by the PM Tool page: dev.fieldworkmanager.com/service/showForm?mode=edit&service_id=X
except the data is not in a form and is not editable.

The FT can use the Service Provider info page to phone the Service Provider (by clicking the phone number) or email the Service Provider (by  clicking the email address) or get directions by clicking the address.

**Comment by damirius** [comment]
@bsaiken @FWAJL 

It took some more time than I planned but it's here.
Workflow is similar to PM's communications tab on active tasks. FTs can start discussions with PMs, other FTs and service providers. They can't send attachments.

You can find it on feature_mobile.

**Comment by bsaiken** [comment]
@damirius @FWAJL 
Works great!
Jeremie - everything on the mobile UI works on the feature_mobile branch.  So if you merge the feature_mobile branch, it should clear up some of the other "bugs" I caught unit testing.

**Comment by FWAJL** [comment]
@bsaiken @damirius 

Every link, except logout and userDetails, that I click has an error when logged in as a FT.

![screen shot 2015-05-29 at 07 15 33](https://cloud.githubusercontent.com/assets/7524388/7876871/a13b7d28-05d2-11e5-92c6-e669e89df246.png)
![screen shot 2015-05-29 at 07 15 42](https://cloud.githubusercontent.com/assets/7524388/7876870/a139ef6c-05d2-11e5-9c0d-35b46eafea61.png)
![screen shot 2015-05-29 at 07 15 58](https://cloud.githubusercontent.com/assets/7524388/7876873/a13cc2c8-05d2-11e5-9ab9-f673ffdca41c.png)
![screen shot 2015-05-29 at 07 16 06](https://cloud.githubusercontent.com/assets/7524388/7876872/a13c836c-05d2-11e5-8a95-6c0f19f2a434.png)

**Comment by damirius** [comment]
@bsaiken @FWAJL 

OK, so first two errors are showing because user is being redirected to wrong page. I've changed that redirect on all pages to redirect the user without activetasks on mobile/listTasks. That page will show that there are no active tasks for logged in FT. All the errors were showing for the FT users without active tasks, so keep that in mind when testing.
Other than that, there were some changes caused from merging I guess. Auth.js was changed, landing page should be mobile/listTasks. Since in that case we don't need popup prompt for choosing task, also if only one task is listed it will be chosen automatically and user will be redirected to the map.

**Comment by bsaiken** [comment]
@damirius @FWAJL 
This worked for me.  No active active tasks lands on a page instead of an error.  I wasn't expecting we'd get this done, but I like.
If there is an active Task, it goes straight to the map page.  Check.
If there are two or more active Tasks, I get  a list of tasks to choose from. Check.
