### ISSUE TITLE
Milestone B(1) – Send message to Field Technician

### ISSUE THREAD

**Issue by FWAJL** [FWAJL/FieldWorkAssistantMVC#867]
Entering text in the left hand column will activate the “Send” button in order to send the message.  

All messages shall be stored in the database to build a discussion thread history. You will need to request a new table (e.g. “discussion”) to store the discussion thread history.  

The table shall include the columns:

- discussion_id
- task_id. 

A another table (“discussion_content”) will hold the messages for a discussion so the columns will be:
- discussion_content_id, 
- discussion_id, 
- discussion_content_category_type (e.g. technician_id) 
- discussion_content_category_value (id value of the discussion_content_category_type ) 
- discussion_content_value (the actual message sent at a given time).  

The tables structure may be modified on request.

The message shall be sent to the FT.  The method for delivering the message is at your (the developer) discretion.  This can be done via email, txt, integrated into the Field Technician interface, or some other method.  Initially, I prefer the most readily available, cost effective method - we may add more messaging options to the site in the future.  The FT shall have some simple (single click) method to respond.  

Discussions with Field Technicians can be text only.

**Comment by FWAJL** [comment]
@nadirhamid @bsaiken 

Please read the wiki as you don't need to change the appsettings to setup your local database. For an easier process, everyone has the same config: https://github.com/FWAJL/FieldWorkAssistantMVC/wiki/2.Installation

I recommend that you read all the wikis.

Please run the schema script to get the database ready with the live server data: 
https://github.com/FWAJL/FieldWorkAssistantMVC/blob/7a45d005686662953533d33e2c8e823b53267ed0/Database/Scripts/Online-backups/baiken_fwm_1_20150413.sql

And the update script for your work: https://github.com/FWAJL/FieldWorkAssistantMVC/blob/7a45d005686662953533d33e2c8e823b53267ed0/Database/Scripts/Updates/2015-04-14.sql

Thank you.

**Comment by nadirhamid** [comment]
As per issue #862 my method of messaging will be email,
UI being used for the pm, and what is currently there

if you have any objections let me know if not I can start right away

**Comment by FWAJL** [comment]
@nadirhamid @bsaiken 

Make sure that the message sent is also store in the `discussion_content` table for the discussion selected.

Also, can you tell me if you received the invitation to this Team: https://github.com/FWM-Team ? This is where we can talk about general questions. Also, I send general info to all the team members on a regular basis (release, database updates, etc...).
I have sent you several requests but you have not yet accepted any.

Thank you.

**Comment by bsaiken** [comment]
@nadirhamid @FWAJL 
I should have done this for each Issue - I will copy the Milestone requirements form the SOW for each Milestone.  That is what I will be looking for when I do a Function Review.

**Comment by nadirhamid** [comment]
@bsaiken @FWAJL

 you should be ready to review this

**Comment by nadirhamid** [comment]
Hold: 
@bsaiken  @FWAJL 

I need to work on a file I will update you when I have completed

**Comment by bsaiken** [comment]
@nadirhamid 
I do not see that you commited any code.  Instructions to commit and push code are in the Wiki:
https://github.com/FWAJL/FieldWorkAssistantMVC/wiki/3.Use-the-repository-with-Git
To push updates, use the following in order:

    git status
    git add -A
    git status

PLEASE USE THE NAMING OF THE COMMIT AS FOLLOWS:

    git commit -m "Issue #[IssueId]" -m "Some additional message if you need" (be as explicit as possible, the last part is not mandatory but appreciated)
    git reset --soft HEAD~1(if you need to modify the last commit message and add something you forgot. This uncommit the last commit). You need to start back from git add -A)
    git push (login required)

**Comment by bsaiken** [comment]
@FWAJL @nadirhamid  
Jeremie,
Why did you create this Issue?  This is Issue #803.  
Nadir, please review the comments on Issue #803 as they may be relevant.
