### ISSUE TITLE
Create user for each Service Provider created

### ISSUE THREAD

**Issue by FWAJL** [FWAJL/FieldWorkAssistantMVC#878]
When adding a service provider, we will add a user too. Their email will be their initial login and password.

It should be done like it is done for the technicians (see #812)

1. Make the service provider email required.
2. Add a user row for the service provider

**Comment by bsaiken** [comment]
@FWAJL 
Yes, this is what I want, but a low priority item.

**Comment by bsaiken** [comment]
@FWAJL 
I thought this was done, and we already set up a default email and username so the Service Provider email field was not required...

**Comment by FWAJL** [comment]
@bsaiken 

Same comment as #881.

Closing.
