### ISSUE TITLE
Add unique constraint on email values

### ISSUE THREAD

**Issue by FWAJL** [FWAJL/FieldWorkAssistantMVC#879]
To add constraint to:

1. technician table
2. service table
3. client table
4. other?

@bsaiken NB: a same email can be set at least once all three tables but no email can be set twice in a same table.

**Comment by bsaiken** [comment]
@FWAJL 
One of the advantages of emails is that they are inherently unique.  Why do we need a constraint?

**Comment by FWAJL** [comment]
@bsaiken 

To be safe ;)

**Comment by FWAJL** [comment]
#916 is implementing email in the user object. This is not necessary anymore.
