### ISSUE TITLE
Additions on discussions table

### ISSUE THREAD

**Issue by nadirhamid** [FWAJL/FieldWorkAssistantMVC#880]
@bsaiken  @FWAJL 
#880

I will be adding the following fields to discussion, and discussion_content

discussion:
discussion_time:
a time when the discussion was started

discussion_content:
discussion_content_is_receiver
Whether a pm sent the message or it was a response
discussion_content_time
A time for the reply, or initial post

**Comment by FWAJL** [comment]
@nadirhamid @bsaiken 

Please don't create new issues. Just comment the issue you are doing the work for.
See the comment I will post on #803.

Thank you.
