### ISSUE TITLE
Create user for each Client created

### ISSUE THREAD

**Issue by FWAJL** [FWAJL/FieldWorkAssistantMVC#881]
When adding a client, we will add a user too. Their email will be their initial login and password.

It should be done like it is done for the technicians (see #812)

1. Make the service provider email required.
2. Add a user row for the client

**Comment by bsaiken** [comment]
@FWAJL 
Isn't this implemented now?
The thing is, We do NOT want the client email to be required, but we already got around that, no?

**Comment by FWAJL** [comment]
@bsaiken 

Implemented in #916. Email is not required anymore as per comment here: https://github.com/FWAJL/FieldWorkAssistantMVC/issues/805#issuecomment-98177542.

Closing.
