### ISSUE TITLE
List common lab and field analytes on the right hand column at `/analyte/uploadCommons` (& /labanalyte/...) - admin UI

### ISSUE THREAD

**Issue by bsaiken** [FWAJL/FieldWorkAssistantMVC#893]
This is related to Issue #892.
Also, provide a contextual menu to view (edit) and delete common analytes in both cases.

**Comment by gsouvik** [comment]
@bsaiken 
The common Lab and Field analytes are now listed on the right hand side list. The analytes could be deleted from the contextual menu. 

I have a question for the Edit menu. Would there be a prompt box where the analyte name which is being edited, would be loaded and presented to the user, and then the user could save it. What are the validations needed? What if the user selects a name which is already existing, would there be an alert box describing the same to the user?

**Comment by bsaiken** [comment]
@gsouvik 
Yes, please add validation that checks for a duplicate entry, just like we have done in other parts of the website.
Also, any time something is deleted, please add your confirm popup.

**Comment by bsaiken** [comment]
@gsouvik 
Make sure you add a redirect to refresh the page so the newly added analytes appear in the list.  
The confirm popup for analytes also applies to master forms.

**Comment by gsouvik** [comment]
@bsaiken 
Ok, shall do that, thanks.

**Comment by bsaiken** [comment]
@gsouvik 
I changed the priority to #767 since it is essentially the same behavior - checking for a unique analyte name.  Makes sense to do it now.

**Comment by bsaiken** [comment]
@gsouvik 
By the same token, I changed the priority of #891, since it is the same behavior - checking for a unique name.

**Comment by bsaiken** [comment]
@gsouvik 
and #768

**Comment by gsouvik** [comment]
@bsaiken 
In the admin UI, while editing the common analytes, unique check validation is added. Actual edit functionality added and  when deleting them, confirm box added.
