### ISSUE TITLE
Consolidate AddUser function in code

### ISSUE THREAD

**Issue by FWAJL** [FWAJL/FieldWorkAssistantMVC#916]
In order to create user for each type (pm, admin, ft, service and client), we need to consolidate the code to be reusable.

**Comment by FWAJL** [comment]
@damirius 

Please run the script for this update on your branch => Issue #917.

**Comment by FWAJL** [comment]
@damirius 

Please `git pull`on the feature thread branch. Thank you.

**Comment by bsaiken** [comment]
@FWAJL 
I am not sure how I would unit test this.  Please advise, or close the Issue.

**Comment by FWAJL** [comment]
@bsaiken 

Logged as a PM:

1. Add a project with a client email address. Is it successful?
2. Add a technician with email address. Is it successful?
3. Add a service provider with email address. Is it successful?

Logged as an Admin:

1. Add a PM with an email address. Is it successful?

Finally:

1. Can you log in with all the users created above?

Thank you.

**Comment by bsaiken** [comment]
@FWAJL 
If I try to log in as client or service provider, I get a successful toastr message, but it does not load anything.
If I try to login as a FT it goes to the wrong page.
I can't add a PM in the admin UI because it is requiring the user password and user login fields to be filled out.  So I can't test to see if the email field might get used to create the PM login credentials.  
If you are OK with all of that, yes, it works great.

**Comment by FWAJL** [comment]
> @bsaiken 
> If I try to log in as client or service provider, I get a successful toastr message, but it does not load anything.

That's normal. We don't have a page to display yet but the successful notification means you logged in.

> If I try to login as a FT it goes to the wrong page.

If you mean "wrong page as not the page the Mobile team has built", then it is normal. The default on live server is what Damir did.

> I can't add a PM in the admin UI because it is requiring the user password and user login fields to be filled out. So I can't test to see if the email field might get used to create the PM login credentials.

And if you type the credentials? I did try and it works.
![screen shot 2015-05-01 at 10 06 41](https://cloud.githubusercontent.com/assets/7524388/7428088/023654bc-efea-11e4-8f66-34a009d27aef.png)
![screen shot 2015-05-01 at 10 06 52](https://cloud.githubusercontent.com/assets/7524388/7428094/27f821bc-efea-11e4-9e9e-5329838e0293.png)
![screen shot 2015-05-01 at 10 07 31](https://cloud.githubusercontent.com/assets/7524388/7428095/2e69b560-efea-11e4-94f0-d43f0380923d.png)
