### ISSUE TITLE
Edit email edition for existing users

### ISSUE THREAD

**Issue by FWAJL** [FWAJL/FieldWorkAssistantMVC#926]
For Admin, Client, Technician and Service providers, allow the email address to be modified in their user row in the database.

**Comment by bsaiken** [comment]
@FWAJL 
Why would we need to do this?  Everyone can edit their email address.
Besides, I thought I could always edit any entry in the database.  The only weird one is the password, because it is encrypted.

**Comment by WebDevJL** [comment]
@bsaiken 

With #916, the PMs, FTs, Client and Service providers have their user row created when providing their email. Then, a PM or an Admin or themselves can edit their email after creation and at the moment, it updates the tables project_manager, client, technician and service. It should update the table user instead as the email value should only be there to create consistency in the application.

**Comment by bsaiken** [comment]
@FWAJL 
I understand this, in the context of your comment on #805.
