### ISSUE TITLE
Enable form viewing using right-click

### ISSUE THREAD

**Issue by bsaiken** [FWAJL/FieldWorkAssistantMVC#941]
@gsouvik @FWAJL 
Souvik,
This slipped though the cracks, so I just created a new Issue.
This is operating on my sister-site: http://dev.fieldworkassistant.net/
You can login there using the test:test credentials.
There, you can navigate to `/task/listAll`.  If you select the Task `Task`, and right-click to edit, you will see on the `Forms` tab a form listed: `Well Purge`.  Right click on this, and you can view the form.  
The js we are using to display the form is `fancybox`.
The js is pretty straightforward:
`$(document).ready(function() {
    $.contextMenu({
    selector: '.select_item',
    callback: function(key, options) {
      if (key === "view") {
        //location_manager.retrieveLocation(options.$trigger);
		var name = $(this).text();
		console.log(name);
		$.ajax({
			type: "POST",
			url: "/Web/includes/masterform_link.php",
			data: { title: name },
			success: function(e) {
				$.fancybox({
					href: '/Web/uploads/master_form/'+e,
					type: 'iframe',
					openEffect  : 'none',
					closeEffect : 'none',
					iframe : {
					preload: false
					}
				});
			}
		});
    } 
    },
    items: {
      "view": {name: "View"}
    }
      });//Manages the context menu`

The file `masterform_link.php` just fetches the form:
`<?php require_once 'config.php';
$tbl_name = "master_form";
//title name form mast form on web page
$title = htmlentities($_POST['title']);
mysql_connect("$host", "$username", "$password")or die("Cannot connect"); 
mysql_select_db("$db_name")or die("Cannot select DB");
$sql = "SELECT * FROM $tbl_name WHERE title = '$title' LIMIT 1";
$result = mysql_query($sql);
$arr = mysql_fetch_array($result);
if($result){
	echo $arr['value'];
}
else {
	echo "Error";
}
?>`

This isn't how we fetch items, so that's why I want you to modify the code so it fits our structure.  

I have already uploaded the fancybox library to our main site: `/Web/js/addons/fancyapps/

Let me know if you need anything else.

**Comment by gsouvik** [comment]
@bsaiken @FWAJL 
I've coded the feature so that forms are fetched dynamically and opened using the Fancy box. Currently I've implemented it on the following routes:
activetask/forms
task/forms

Let me know if this needs to be implemented on other places too and I shall do that. Thank you.

**Comment by bsaiken** [comment]
@gsouvik 
Beautiful.  Thanks.
