### ISSUE TITLE
Add text overflow truncation to the matrix table.

### ISSUE THREAD

**Issue by bsaiken** [FWAJL/FieldWorkAssistantMVC#958]
This is related to Issue #815.  I want to clean up the look a bit more.
Sometimes, the text is too long to fit in the box and it does not display cleanly. 
I found some simple ways to do this, here is just one: 
https://css-tricks.com/snippets/css/truncate-string-with-ellipsis/
The trouble with this option, is I don't see a way to view the whole text string, which is important too.
I want the user to see the complete text string on mouseover.

**Comment by WebDevJL** [comment]
@bsaiken @gsouvik 

What about using Souvik's tooltips?

**Comment by bsaiken** [comment]
@FWAJL 
That's find, but that won't truncate the text.

**Comment by gsouvik** [comment]
@bsaiken @WebDevJL 
Yes, we can use the tooltips we developed previously. On a separate note the solution with CSS ellipses has some drawbacks on certain browsers it seems. To bypass that problem we can simple truncate the text using PHP whenever it exceeds certain predefined character count.

So "A very long text" would look like "A very..." when we truncate it based on 10 character limit. However we can still show only 7 characters if we were to include the trailing "...". But the full text remains visible in the tooltip.

**Comment by bsaiken** [comment]
@gsouvik 
I did not intend for you to use CSS, just pointing out one possibility.  I trust you to come up with the right solution.

**Comment by gsouvik** [comment]
@bsaiken 
Ok, so truncating the text using Php and using our tool tip to show the full text when user hovers over it.

**Comment by bsaiken** [comment]
@gsouvik @FWAJL 
Super.  I look forward to seeing it.
Also, please modularize (if that's the correct word) the code so it could be used in other contexts.  As per the final comment on Issue #906.

**Comment by gsouvik** [comment]
@bsaiken @FWAJL 
The field and lab analyte matrix cells now support ellipsis and our tool tip shows the complete text on mouse hover. In truest sense this can be applied to any container which is holding some text. That makes it completely reusable anywhere across the code base.

I've used our tooltipandpopupstrings.en.xml file to store the settings for each Controller/Action pair, so the number of characters based on which clipping comes into effect, is fully controllable and independent to the controllers.

Please review and let me know of any changes, if required. Thank you.

**Comment by bsaiken** [comment]
@gsouvik 
There are still a few things I want to change.
We will need more than a 13 character limit.  that's only 10 characters with the `...`.  For the items we will display, that is much to few, even for the abbreviation.
So, I tried reducing the font size.  That helps some.  Then I see that the cell allows the text to wrap.  That helps, but no if there is a very long word, like in the example.  In my field, words like `1,1,1-trichloroethane` are common.  But, when there is a single word that is VERY long, you see in the example that wrapping does not work.
If we are going to use just one line to display the text (no wrapping) the cell holding text does not need to have a large height.
Solutions?

**Comment by gsouvik** [comment]
@bsaiken @FWAJL 
In any case we have a fixed height and width. So we can allow for fixed characters width wise and at most 2 lines of text. In other words we can user wrapping and ellipsis together to make the best of the space available. Writing some Php, the name `1,1,1-trichloroethane` could be made to look like:

1,1,1-trichlo
roethane

And if it is bigger than that, for example `1,1,1-trichloroethane_andevenbigger` it would look like:

1,1,1-trichlo
roethane_...

The full text in this case would be visible in the tooltip we created. 
Let me know your thoughts.

**Comment by bsaiken** [comment]
@gsouvik 
I am trying to imagine all contexts this would be needed.  And other alternatives.  

Almost every long-named chemical that would be a Field of Lab Analyte has an abbreviation.  For example, 1,1,1-trichloroethane = 1,1,1-TCA.  So, I could add a column `analyte_abbrev` to each of the tables `lab_analyte` and `filed_analyte`.  Then we could place a restriction on `analyte_abbrev` so that the data type is `varchar(13)`, or whatever width we choose.  If there is a NULL entry in the `analyte_abbrev` column, then we go with `lab_analyte_name` or `field_analyte_name_unit`.  If the abbreviated name is the one displayed, then the tooltip shows the full name.   In a mush earlier version of the website, this is what I was doing.  

This use of abbreviations would only be for analytes.  If there are other places in the website we implement the ellipsis, it would be like it is now.

In terms of text wrapping for long words, I would much prefer:

1,1,1-tric...
to
1,1,1-trichlo
roethane_...
or 
1,1,1-trichlo
roethane

We only wrap the text if the words are small enough to allow it.  But, if I'm making things too complex, I don't want you to spend an inordinate amount of time on this.

**Comment by gsouvik** [comment]
@bsaiken 
so I'm not touching it right now, or should I implement the wrapping I suggested?

**Comment by bsaiken** [comment]
@gsouvik @FWAJL 

I don't think what Jeremie is suggesting will change anything, he is just moving the truncation code in the BaseController, so it could work anywhere.  And there are indeed may other contexts where this is going to be useful.  

Still, let's make sure you and Jeremie are on the same page.  I'm not sure he saw my earlier comment.
You can work on other things until Jeremie chimes in again.

**Comment by WebDevJL** [comment]
@bsaiken @gsouvik 

The update I made is independent of the way you trim the analyte name. In fact it is only about how to get and store the tooltips in memory. The trimming remains a separate function. 

So you can both continue your work on deciding how to display / trim the analyte name the best way possible. 

Thank you.

**Comment by gsouvik** [comment]
@WebDevJL @bsaiken 
On a separate note just wanted to update that the page at `task/labMatrix` is broken, however `task/fieldMatrix` looks fine.

**Comment by bsaiken** [comment]
@gsouvik @FWAJL 
Yes, I see that.  Is this on you or Jeremie?

**Comment by gsouvik** [comment]
@bsaiken @FWAJL 
This may be due to the refactored code, the view files were changed only for `task/fieldMatrix` or some variable mismatch. If you want me to fix it, I'll do so the next time I'll work on these according to issue priority.

**Comment by FWAJL** [comment]
@bsaiken @gsouvik 

This is fixed in the last commit on that branch.

**Comment by bsaiken** [comment]
@FWAJL @gsouvik 
Then I think this moves to code review.
