### ISSUE TITLE
Error editng Field Anayte names

### ISSUE THREAD

**Issue by bsaiken** [FWAJL/FieldWorkAssistantMVC#965]
![screen shot 2015-05-07 at 9 25 39 am](https://cloud.githubusercontent.com/assets/8228624/7520511/0f2b4932-f49c-11e4-9abe-ef427dfbfc4f.png)
![screen shot 2015-05-07 at 9 25 36 am](https://cloud.githubusercontent.com/assets/8228624/7520520/17806a9a-f49c-11e4-8a2c-7f877058b397.png)

**Comment by bsaiken** [comment]
@gsouvik 
Both are important.  I'd work in the way that is most efficient for you.

**Comment by gsouvik** [comment]
@bsaiken 
This bug is now fixed. 
The bug was - `analyte_manager.js` had a function whose signature was changed, but the call was not updated accordingly. 
https://github.com/FWAJL/FieldWorkAssistantMVC/commit/1ddbc6fedd7299927772c9b3857a46529af1e5af

Please review and let me know. Thank you.
