### ISSUE TITLE
Error displaying Boundary when Facility name is changed

### ISSUE THREAD

**Issue by bsaiken** [FWAJL/FieldWorkAssistantMVC#967]
Select a Project with a Boundary (or draw a boundary).  Then, edit the Facility name in Project Edit mode.  The boundary disappears.  
Video uploaded to eLance.

**Comment by damirius** [comment]
@bsaiken

This should be fixed on feature_damir branch. Here is the video: https://drive.google.com/file/d/0B7Laiv0PjSvDUXJTT0haaGxQalE/view?usp=sharing

@FWAJL 
I see that you have added EditUser method for client edit, I assume to add generated email address if it isn't set. Only problem is that method isn't finished and it isn't properly called from the client/edit method so it breaks.

**Comment by FWAJL** [comment]
@damirius 

You can finish the implementation if you can..

**Comment by bsaiken** [comment]
@damirius 
I see from your video that this works, but i am unable to test because my local machine database was reset and I don't have any facilities with boundaries.  The tool to draw boundaries is disabled (I assume this is temporary pending other Issue completion).  So I will wait to complete the function review.

Per Jeremie's comment - can you fix the EditUser method?  I will make a new Issue.
