### ISSUE TITLE
Changes to Mapping - Task Locations view

### ISSUE THREAD

**Issue by bsaiken** [FWAJL/FieldWorkAssistantMVC#968]
1) Add heading to sidebar to show Task Locations separated from Project Locations.
2) Exclude Project Locations that do not have coordinates.
3) Reduce the size of Project Location markers in the Task Location map view.

See images below:
![screen shot 2015-05-08 at 10 55 42 am](https://cloud.githubusercontent.com/assets/8228624/7542428/89382daa-f571-11e4-95c7-8c5e9938afb4.png)
![screen shot 2015-05-08 at 10 55 45 am](https://cloud.githubusercontent.com/assets/8228624/7542445/9d38599c-f571-11e4-9199-9e71b1f810b1.png)
![screen shot 2015-05-08 at 10 55 47 am](https://cloud.githubusercontent.com/assets/8228624/7542458/a63b8442-f571-11e4-9ca8-a854da0502be.png)

4) Like other pages, remove the sidebar menu and make the Google menu all the time.  On this map, enable the `Draw a line` and `Draw a shape` menu items.  Put the resulting values (area or distance) next to the feature that was drawn.  

5) Change the sidebar icon for Location with no coordinates to match the new legend (red_maps.png).

**Comment by damirius** [comment]
@bsaiken @FWAJL 

You can check out new task map. Headings are added to the sidebar, controls are hidden. Icons for project locations are smaller than icons for task locations. Ruler controls are shown all the time and info window will popup with distance/area measurements when overlay is complete.
Also Project Locations with no coordinates are hidden and Task Locations with no coordinates have the same icon as regular Task Locations, but keep in mind that task map doesn't allow marker editing. So there will be no popup window on Task Locations that aren't set on the map already.
Tell me if I missed something.

You can find this changes on feature_damir branch.
