### ISSUE TITLE
Changes to Mapping - Selected Project view

### ISSUE THREAD

**Issue by bsaiken** [FWAJL/FieldWorkAssistantMVC#970]
Use the newly created popup view `popup_current_project_info.php`
Remove the sidebar (this view only)
Make the google map menu always available in this view.  Include `Draw a shape` only - to be used to draw Facility boundaries.

**Comment by damirius** [comment]
@bsaiken

Removed controls. Boundary can be edited from the popup by clicking 'edit boundary'.
