### ISSUE TITLE
Changes to Mapping - Project Locations view

### ISSUE THREAD

**Issue by bsaiken** [FWAJL/FieldWorkAssistantMVC#971]
1) Enable drag and drop of Locations without coordinates from the sidebar to the map area.  Update coordinates automatically (like we do now when we more Location markers on the map).
2) Like other pages, remove the sidebar menu and make the Google menu all the time.  On this map, enable the `Draw a line` and `Draw a shape` menu items.  Put the resulting values (area or distance) next to the feature that was drawn.

**Comment by damirius** [comment]
@bsaiken @FWAJL 

You can check out the video with new drag and drop functionality here: https://drive.google.com/file/d/0B7Laiv0PjSvDemgwUmxlR3BXbXM/view?usp=sharing
Along with few other stuff.
Keep in mind that in video sidebar for Current Project map isn't hidden, but it's hidden in the code.

**Comment by bsaiken** [comment]
@damirius 
I am getting some bizarre behaviors.  Did you make any changes to the database?

**Comment by damirius** [comment]
@bsaiken

No I didn't make any changes to the db. Can you provide more details about those behaviors?

**Comment by bsaiken** [comment]
@damirius 
There are so many that something must be different about our machines.  I uploaded a video to eLance showing that the marker does not land where I drop it.

**Comment by bsaiken** [comment]
@damirius 
Here are some other Issues I am seeing:
In this Project's Locations map, There is a Location with coordinates, but the auto-zoom still goes to the Facility Boundary extents.  As long as there is at least one Location with coordinates, the centering should be to the Location(s) extents.
![screen shot 2015-05-18 at 8 33 25 am](https://cloud.githubusercontent.com/assets/8228624/7684170/e8770da8-fd38-11e4-9ddd-dcea4c09f462.png)
![screen shot 2015-05-18 at 8 33 25 am](https://cloud.githubusercontent.com/assets/8228624/7684175/f14eaf94-fd38-11e4-9abf-c367b221de32.png)

**Comment by bsaiken** [comment]
@damirius 
In the All Project's Loctions map, we should remove the js for clicking in the boundary area.  If we need to edit a boundary, let's do it only from the Selected Project map view.  
It does not make sense in this view.  For example, one of the info window options is "Confirm relocated marker position", but the Project marker does not appear in the Project's Locations view, so this is confusing.

**Comment by damirius** [comment]
@bsaiken 

I've changed fitZoom to fit markers even if boundary is set. Also I've removed infowindow for boundary on project locations and task locations maps.
I can't open the video on elance that you've sent me. I think they have some problems with their servers currently, couldn't open messages for few minutes either.

**Comment by bsaiken** [comment]
@damirius 
The marker is not dropping where I put it.  It flies back toward the sidebar and eventually lands, but the place it lands seems to be random.

**Comment by damirius** [comment]
@bsaiken

This seems like some bug with draggable plugin of jquery, since it should register on mouse up. I'll try to recreate the bug

**Comment by bsaiken** [comment]
@damirius 
I had some other thoughts.  Perhaps rather than drag and drop, it can be click and drop, that would likely eliminate the flyback.  
Also, let's put the Latitude and Longitude values back into the info windows for Locations so they can be viewed and edited in the info window.
When a Location has no coordinates, the info window currently does not pop up - that sort of gave me the idea for the click and drop.  However, I should still be able to see an info window for Locations that do not have coordinates.  This info window would be the same (including the lat/long form elements), but would not include the "Zoom to selected location" because there is no place to zoom.  So, another idea, open an info window for markers that do not have coordinates and add a button in the info window to "Place onto the map" - then the info window disappears and the next click is the dropped location.

**Comment by damirius** [comment]
@bsaiken

Well we had something like that, you had to click on marker control button then on marker and then on map. So instead of that we open the infowindow and show "place onto the map" link right?

**Comment by bsaiken** [comment]
@damirius 
Yes, I remember, but we got rid of the marker control button.  So antoher way to think of it is we put the "marker control button" in the info window.

**Comment by damirius** [comment]
@bsaiken

You can see the changes on feature_damir branch. You can click now on marker rows in the sidebar which doesn't contain any coordinates, infowindow will popup with the option to place the marker on the map. Click on it, infowindow will be hidden and you can click on the map to place the marker. You can click on the marker row in the sidebar again to check updated infowindow, with zoom link and coordinates.

**Comment by bsaiken** [comment]
@damirius 
Every time I click it looks like the marker is dropped.  See the video.

https://www.dropbox.com/s/zbqfz594k3a1kkw/click%20and%20drop.mov?dl=0

There is really only one marker there.  If I refresh the page, I only see one.

**Comment by damirius** [comment]
@bsaiken 

Should be fixed now in the new commit

**Comment by bsaiken** [comment]
@damirius 
Yes, this is working, so we can apply to the Task Locations map as well.

**Comment by damirius** [comment]
@bsaiken

I've added infowindow to task locations without coordinates, you can add them to the map now just like on project locations map.

**Comment by bsaiken** [comment]
@damirius 
Add lat/long and description to the info window.

I reviewed this on the dev branch, so if it is already done, ignore this comment and remove the function review.
Thanks

**Comment by damirius** [comment]
@bsaiken

It's on feature_damir branch. It wasn't mentioned that we need description and lat/long there, I think that we intentionally removed it from task info windows when we made them.

**Comment by bsaiken** [comment]
@damirius 
I see it, thanks.

**Comment by WebDevJL** [comment]
@bsaiken @damirius 

Merged.

**Comment by bsaiken** [comment]
@FWAJL 
Let's make the final release a separate Issue so we can close all the merged Issues.
