### ISSUE TITLE
Changes to Mapping - Legends and info windows

### ISSUE THREAD

**Issue by bsaiken** [FWAJL/FieldWorkAssistantMVC#972]
Custom legend for each view and modify info windows to follow the same format as the forms pages.

**Comment by bsaiken** [comment]
@FWAJL 
Can you release this so we can move forward with Issue #973?

**Comment by WebDevJL** [comment]
@bsaiken 

This is merged on all branches. Will release when I get the chance. 

Thank you.

**Comment by bsaiken** [comment]
@FWAJL 
Oh, of course that's good enough.  Thanks!
