### ISSUE TITLE
Modify the Active Task maps tab

### ISSUE THREAD

**Issue by bsaiken** [FWAJL/FieldWorkAssistantMVC#973]
Related to Issue #726 (closed).
Add a legend glyphicon.
Use the same (new) legend for the Task Locations map page.
Add info windows.
Use the same (new) info window for the Task Locations page.
Release of Issue #972 is a prerequisite.

**Comment by gsouvik** [comment]
@bsaiken @FWAJL 
Status of #972 is set to "to release", but for this task to be started, the prerequisite is that issue must be "released". So should I start with this, do I have all code/modules available in my branch.

**Comment by bsaiken** [comment]
@gsouvik @FWAJL 
Given Jeremie's status (preoccupied with new twins) we can't wait for the release.  Issue #972 is on the DEV branch and should be updated on your branch, so you should be OK to go.

**Comment by gsouvik** [comment]
@bsaiken @FWAJL 
I've added the legend popup which was used on `map/taskLocations`. the info window is a shared module and it was already in use in the active task tab. I've also re-used the relevant tooltips which was available on the `map/taskLocations`. Please review and let me know if the integration looks good.
Thank you.

**Comment by bsaiken** [comment]
@gsouvik @FWAJL @damirius 
Souvik,
With Jeremie temporarily unavailable to merge branches, please commit these changes to the feature_damir branch.  He recently did a lot of mapping upgrades, so if you work from his branch, the mapping working will be better integrated.

**Comment by damirius** [comment]
@gsouvik @bsaiken 

We can perform the merge from mapping and from devsupport branches to dev and then merge that back into feature branches, it's not a problem.

**Comment by gsouvik** [comment]
@damirius @bsaiken 
Yes that sounds good, so I'll sync with the dev branch, please merge your work on dev when you have a chance and let me know, I'll pull, merge and commit back these changes.

**Comment by damirius** [comment]
@gsouvik @bsaiken 

I've merged both feature_damir and feature_devsupport into dev branch. You can merge dev now into feature_devsupport when you are ready.

Thanks

**Comment by bsaiken** [comment]
@damirius @gsouvik 
Perfect.  We can continue to work on the feature branches.  Once the new code get's past the `function review`, then merge them to the DEV branch.  That's what Jeremie had been doing, but with the extra step of checking the code (which is less necessary now since you both are masters of our code style).  I need you both to forge ahead coding, so I will continue to do unit tests on the DEV branch to see if there are any resulting conflicts.

**Comment by gsouvik** [comment]
@bsaiken @damirius 
I've merged dev into my local feature_devsupport so my branch has all the updated code now. I'll keep merging to dev and update you, as I complete other issues. 
Thanks.
