### ISSUE TITLE
Enable new roles for Service and Client

### ISSUE THREAD

**Issue by FWAJL** [FWAJL/FieldWorkAssistantMVC#986]
- Add the roles id 6 and 7 to the database.
- Update the classes \Library\Enums\UserRoleType and \Library\Enums\UserRole appropriately.
- Update UserHelper::GetTypeFromRoleId method to use the new roles

**Comment by bsaiken** [comment]
@FWAJL 
Easy enough - I'll take this on.

**Comment by bsaiken** [comment]
@FWAJL 
I made the necessary changes.  
I also reset the redirect in auth.js for users with no views to: /logout.
The redirect for SPs is still set to serviceprovider/discussion for now, even though that will need to be changed, right?

**Comment by FWAJL** [comment]
@bsaiken 

Yes to your question.
