### ISSUE TITLE
Database updates for release 1.6.22

### ISSUE THREAD

**Issue by WebDevJL** [FWAJL/FieldWorkAssistantMVC#994]
@bsaiken @damirius @gsouvik 

Please paste here all the sql scripts to run for the next release. Links to the scripts are enough. 

Also, when making table modifications, please update the reset script accordingly. It is located in Database/Scripts. 

Thank you.

**Comment by WebDevJL** [comment]
@bsaiken @gsouvik @damirius 

I'm not back on duty yet but thinking ahead so please give me the all info regarding database updates. 

Thank you.

**Comment by damirius** [comment]
@WebDevJL 

Not the best place for this, but first off CONGRATS Jeremie!
I'll see that I find all scripts which we used and paste their links here.

**Comment by gsouvik** [comment]
@WebDevJL 
Here's the script which I created recently which might be needed for this release:
https://github.com/FWAJL/FieldWorkAssistantMVC/blob/feature_devsupport/Database/Scripts/Updates/2015-05-15.sql

**Comment by damirius** [comment]
@WebDevJL 

https://github.com/FWAJL/FieldWorkAssistantMVC/blob/feature_mobile/Database/Scripts/Updates/2015-05-22.SQL
https://github.com/FWAJL/FieldWorkAssistantMVC/blob/feature_mobile/Database/Scripts/Updates/2015-05-19.sql

**Comment by WebDevJL** [comment]
@damirius @gsouvik 

Thank you guys :+1:
