### ISSUE TITLE
Add functions to Datepicker

### ISSUE THREAD

**Issue by bsaiken** [FWAJL/FieldWorkAssistantMVC#995]
@damirius 
At `/task/showForm` I have a Datepicker widget.  It works fine, except some of the functions are not turned on.  Currently, it is only possible to pick a date from the current month.  It is not possible to switch months or years.

**Comment by damirius** [comment]
@bsaiken

Datepicker worked normally, there was some missing images so you didn't notice left/right arrows for choosing month.

It's on feature_damir

**Comment by bsaiken** [comment]
@damirius @FWAJL 
Great - thanks.
